/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.13 Tue Jul 15 20:43:55 2025.
 */

#ifndef CHARGER_H
#define CHARGER_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define CHARGER_NLG5_ST_FRAME_ID (0x610u)
#define CHARGER_NLG5_ACT_I_FRAME_ID (0x611u)
#define CHARGER_NLG5_ACT_II_FRAME_ID (0x612u)
#define CHARGER_NLG5_TEMP_FRAME_ID (0x613u)
#define CHARGER_NLG5_ERR_FRAME_ID (0x614u)
#define CHARGER_NLG5_CTL_FRAME_ID (0x618u)
#define CHARGER_NLG5_DIAG_RX_FRAME_ID (0x718u)
#define CHARGER_NLG5_DIAG_TX_FRAME_ID (0x71au)

/* Frame lengths in bytes. */
#define CHARGER_NLG5_ST_LENGTH (4u)
#define CHARGER_NLG5_ACT_I_LENGTH (8u)
#define CHARGER_NLG5_ACT_II_LENGTH (8u)
#define CHARGER_NLG5_TEMP_LENGTH (8u)
#define CHARGER_NLG5_ERR_LENGTH (5u)
#define CHARGER_NLG5_CTL_LENGTH (7u)
#define CHARGER_NLG5_DIAG_RX_LENGTH (8u)
#define CHARGER_NLG5_DIAG_TX_LENGTH (8u)

/* Extended or standard frame types. */
#define CHARGER_NLG5_ST_IS_EXTENDED (0)
#define CHARGER_NLG5_ACT_I_IS_EXTENDED (0)
#define CHARGER_NLG5_ACT_II_IS_EXTENDED (0)
#define CHARGER_NLG5_TEMP_IS_EXTENDED (0)
#define CHARGER_NLG5_ERR_IS_EXTENDED (0)
#define CHARGER_NLG5_CTL_IS_EXTENDED (0)
#define CHARGER_NLG5_DIAG_RX_IS_EXTENDED (0)
#define CHARGER_NLG5_DIAG_TX_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */


/* Frame Names. */
#define CHARGER_NLG5_ST_NAME "NLG5_ST"
#define CHARGER_NLG5_ACT_I_NAME "NLG5_ACT_I"
#define CHARGER_NLG5_ACT_II_NAME "NLG5_ACT_II"
#define CHARGER_NLG5_TEMP_NAME "NLG5_TEMP"
#define CHARGER_NLG5_ERR_NAME "NLG5_ERR"
#define CHARGER_NLG5_CTL_NAME "NLG5_CTL"
#define CHARGER_NLG5_DIAG_RX_NAME "NLG5_DIAG_RX"
#define CHARGER_NLG5_DIAG_TX_NAME "NLG5_DIAG_TX"

/* Signal Names. */
#define CHARGER_NLG5_ST_NLG5_S_CP_DT_NAME "NLG5_S_CP_DT"
#define CHARGER_NLG5_ST_NLG5_S_UM_II_NAME "NLG5_S_UM_II"
#define CHARGER_NLG5_ST_NLG5_S_UM_I_NAME "NLG5_S_UM_I"
#define CHARGER_NLG5_ST_NLG5_S_EUM_NAME "NLG5_S_EUM"
#define CHARGER_NLG5_ST_NLG5_S_FAN_NAME "NLG5_S_FAN"
#define CHARGER_NLG5_ST_NLG5_S_WAR_NAME "NLG5_S_WAR"
#define CHARGER_NLG5_ST_NLG5_S_ERR_NAME "NLG5_S_ERR"
#define CHARGER_NLG5_ST_NLG5_S_HE_NAME "NLG5_S_HE"
#define CHARGER_NLG5_ST_NLG5_S_L_PMAX_NAME "NLG5_S_L_PMAX"
#define CHARGER_NLG5_ST_NLG5_S_L_CP_NAME "NLG5_S_L_CP"
#define CHARGER_NLG5_ST_NLG5_S_L_PI_NAME "NLG5_S_L_PI"
#define CHARGER_NLG5_ST_NLG5_S_L_MC_NAME "NLG5_S_L_MC"
#define CHARGER_NLG5_ST_NLG5_S_L_OC_NAME "NLG5_S_L_OC"
#define CHARGER_NLG5_ST_NLG5_S_L_OV_NAME "NLG5_S_L_OV"
#define CHARGER_NLG5_ST_NLG5_S_BPD_II_NAME "NLG5_S_BPD_II"
#define CHARGER_NLG5_ST_NLG5_S_BPD_I_NAME "NLG5_S_BPD_I"
#define CHARGER_NLG5_ST_NLG5_S_L_T_BATT_NAME "NLG5_S_L_T_BATT"
#define CHARGER_NLG5_ST_NLG5_S_L_T_TR_NAME "NLG5_S_L_T_TR"
#define CHARGER_NLG5_ST_NLG5_S_L_T_DIO_NAME "NLG5_S_L_T_DIO"
#define CHARGER_NLG5_ST_NLG5_S_L_T_POW_NAME "NLG5_S_L_T_POW"
#define CHARGER_NLG5_ST_NLG5_S_L_T_CPRIM_NAME "NLG5_S_L_T_CPRIM"
#define CHARGER_NLG5_ST_NLG5_S_L_MO_MAX_NAME "NLG5_S_L_MO_MAX"
#define CHARGER_NLG5_ST_NLG5_S_L_OC_MAX_NAME "NLG5_S_L_OC_MAX"
#define CHARGER_NLG5_ST_NLG5_S_L_MC_MAX_NAME "NLG5_S_L_MC_MAX"
#define CHARGER_NLG5_ST_NLG5_S_AAC_NAME "NLG5_S_AAC"
#define CHARGER_NLG5_ACT_I_NLG5_MC_ACT_NAME "NLG5_MC_ACT"
#define CHARGER_NLG5_ACT_I_NLG5_MV_ACT_NAME "NLG5_MV_ACT"
#define CHARGER_NLG5_ACT_I_NLG5_OV_ACT_NAME "NLG5_OV_ACT"
#define CHARGER_NLG5_ACT_I_NLG5_OC_ACT_NAME "NLG5_OC_ACT"
#define CHARGER_NLG5_ACT_II_NLG5_S_MC_M_CP_NAME "NLG5_S_MC_M_CP"
#define CHARGER_NLG5_ACT_II_NLG5_S_MC_M_PI_NAME "NLG5_S_MC_M_PI"
#define CHARGER_NLG5_ACT_II_NLG5_ABV_NAME "NLG5_ABV"
#define CHARGER_NLG5_TEMP_NLG5_P_TMP_NAME "NLG5_P_TMP"
#define CHARGER_NLG5_TEMP_NLG5_TMP_EXT1_NAME "NLG5_TMP_EXT1"
#define CHARGER_NLG5_TEMP_NLG5_TMP_EXT2_NAME "NLG5_TMP_EXT2"
#define CHARGER_NLG5_TEMP_NLG5_TMP_EXT3_NAME "NLG5_TMP_EXT3"
#define CHARGER_NLG5_ERR_NLG5_E_MF_NAME "NLG5_E_MF"
#define CHARGER_NLG5_ERR_NLG5_E_OF_NAME "NLG5_E_OF"
#define CHARGER_NLG5_ERR_NLG5_E_P_MV_NAME "NLG5_E_P_MV"
#define CHARGER_NLG5_ERR_NLG5_E_P_OM_NAME "NLG5_E_P_OM"
#define CHARGER_NLG5_ERR_NLG5_E_SC_NAME "NLG5_E_SC"
#define CHARGER_NLG5_ERR_NLG5_E_MOV_I_NAME "NLG5_E_MOV_I"
#define CHARGER_NLG5_ERR_NLG5_E_MOV_II_NAME "NLG5_E_MOV_II"
#define CHARGER_NLG5_ERR_NLG5_E_OOV_NAME "NLG5_E_OOV"
#define CHARGER_NLG5_ERR_NLG5_E_T_EXT3_NAME "NLG5_E_T_EXT3"
#define CHARGER_NLG5_ERR_NLG5_E_T_EXT2_NAME "NLG5_E_T_EXT2"
#define CHARGER_NLG5_ERR_NLG5_E_T_EXT1_NAME "NLG5_E_T_EXT1"
#define CHARGER_NLG5_ERR_NLG5_E_T_TR_NAME "NLG5_E_T_TR"
#define CHARGER_NLG5_ERR_NLG5_E_T_DIO_NAME "NLG5_E_T_DIO"
#define CHARGER_NLG5_ERR_NLG5_E_T_POW_NAME "NLG5_E_T_POW"
#define CHARGER_NLG5_ERR_NLG5_E_T_C_NAME "NLG5_E_T_C"
#define CHARGER_NLG5_ERR_NLG5_E_B_P_NAME "NLG5_E_B_P"
#define CHARGER_NLG5_ERR_NLG5_E_C_OFF_NAME "NLG5_E_C_OFF"
#define CHARGER_NLG5_ERR_NLG5_E_C_TO_NAME "NLG5_E_C_TO"
#define CHARGER_NLG5_ERR_NLG5_E_INIT_NAME "NLG5_E_INIT"
#define CHARGER_NLG5_ERR_NLG5_E_WDT_NAME "NLG5_E_WDT"
#define CHARGER_NLG5_ERR_NLG5_E_EP_CRC_NAME "NLG5_E_EP_CRC"
#define CHARGER_NLG5_ERR_NLG5_E_ES_CRC_NAME "NLG5_E_ES_CRC"
#define CHARGER_NLG5_ERR_NLG5_E_NV_CRC_NAME "NLG5_E_NV_CRC"
#define CHARGER_NLG5_ERR_NLG5_E_F_CRC_NAME "NLG5_E_F_CRC"
#define CHARGER_NLG5_ERR_NLG5_E_SDT_CT_NAME "NLG5_E_SDT_CT"
#define CHARGER_NLG5_ERR_NLG5_E_SDT_AH_NAME "NLG5_E_SDT_AH"
#define CHARGER_NLG5_ERR_NLG5_E_SDT_BV_NAME "NLG5_E_SDT_BV"
#define CHARGER_NLG5_ERR_NLG5_E_SDT_BT_NAME "NLG5_E_SDT_BT"
#define CHARGER_NLG5_ERR_NLG5_E_C_RX_NAME "NLG5_E_C_RX"
#define CHARGER_NLG5_ERR_NLG5_E_C_TX_NAME "NLG5_E_C_TX"
#define CHARGER_NLG5_ERR_NLG5_W_SC_M_NAME "NLG5_W_SC_M"
#define CHARGER_NLG5_ERR_NLG5_W_OD_NAME "NLG5_W_OD"
#define CHARGER_NLG5_ERR_NLG5_W_CM_NA_NAME "NLG5_W_CM_NA"
#define CHARGER_NLG5_ERR_NLG5_W_C_VOR_NAME "NLG5_W_C_VOR"
#define CHARGER_NLG5_ERR_NLG5_W_PL_IT_NAME "NLG5_W_PL_IT"
#define CHARGER_NLG5_ERR_NLG5_W_PL_BV_NAME "NLG5_W_PL_BV"
#define CHARGER_NLG5_ERR_NLG5_W_PL_MV_NAME "NLG5_W_PL_MV"
#define CHARGER_NLG5_CTL_NLG5_C_MR_NAME "NLG5_C_MR"
#define CHARGER_NLG5_CTL_NLG5_C_CP_V_NAME "NLG5_C_CP_V"
#define CHARGER_NLG5_CTL_NLG5_C_C_EL_NAME "NLG5_C_C_EL"
#define CHARGER_NLG5_CTL_NLG5_C_C_EN_NAME "NLG5_C_C_EN"
#define CHARGER_NLG5_CTL_NLG5_MC_MAX_NAME "NLG5_MC_MAX"
#define CHARGER_NLG5_CTL_NLG5_OV_COM_NAME "NLG5_OV_COM"
#define CHARGER_NLG5_CTL_NLG5_OC_COM_NAME "NLG5_OC_COM"
#define CHARGER_NLG5_DIAG_RX_LAD_D_PARAM_RQ_NAME "LAD_D_ParamRq"
#define CHARGER_NLG5_DIAG_TX_LAD_D_PARAM_RP_NAME "LAD_D_ParamRp"

/**
 * Signals in message NLG5_ST.
 *
 * NLG5 Status (cycle_time: 100)
 *
 * All signal values are as on the CAN bus.
 */
struct charger_nlg5_st_t {
    /**
     * Control pilot signal (SAE J1772) detected
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_s_cp_dt;

    /**
     * US mains level 2 (240 V AC / 60 Hz) detected
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_s_um_ii;

    /**
     * US mains level 1 (120 V AC / 60 Hz) detected
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_s_um_i;

    /**
     * European mains input detected (230 V, 50 Hz)
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_s_eum;

    /**
     * Charger cooling fan is active
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_s_fan;

    /**
     * Warning condition on, i.e. charging power limited due to any limiting condition; red LED is blinking
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_s_war;

    /**
     * An error has been detected, red LED is ON, no power is output
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_s_err;

    /**
     * Indicates if hardware enabled, i.e. a high or low signal is fed to the 'Power On' pin (pin3 of control connector)
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_s_he;

    /**
     * Output power limited by maximum power capability of NLG5
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_s_l_pmax;

    /**
     * Output power limited by control pilot signal (SAE J1772)
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_s_l_cp;

    /**
     * Output power limited by analogue input 'power indicator' (PI) limit
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_s_l_pi;

    /**
     * Output power limited by mains current limit
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_s_l_mc;

    /**
     * Output power limited by battery output current limit
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_s_l_oc;

    /**
     * Output power limited by battery output voltage limit
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_s_l_ov;

    /**
     * Bypass detection bit 2; 00: no bypass, 01: DC bypass detected, 10: AC bypass in phase, 11: AC bypass not in phase
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_s_bpd_ii;

    /**
     * Bypass detection bit 1; 00: no bypass, 01: DC bypass detected, 10: AC bypass in phase, 11: AC bypass not in phase
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_s_bpd_i;

    /**
     * Output power limited by battery temperature
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_s_l_t_batt;

    /**
     * Output power limited by temperature of transformer
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_s_l_t_tr;

    /**
     * Output power limited by temperature of diodes
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_s_l_t_dio;

    /**
     * Output power limited by temperature of power stage
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_s_l_t_pow;

    /**
     * Output power limited by temperature of primary capacitors
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_s_l_t_cprim;

    /**
     * Output power limited by maximum output voltage capability of NLG5
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_s_l_mo_max;

    /**
     * Output power limited by maximum output current capability of NLG5
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_s_l_oc_max;

    /**
     * Output power limited by maximum mains current capability of NLG5
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_s_l_mc_max;

    /**
     * AUX 12 V Automatic Charging Active
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_s_aac;
};

/**
 * Signals in message NLG5_ACT_I.
 *
 * NLG5 Actual Values I (cycle_time: 100)
 *
 * All signal values are as on the CAN bus.
 */
struct charger_nlg5_act_i_t {
    /**
     * Actual mains current
     *
     * Range: 0..5000 (0..50 A)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t nlg5_mc_act;

    /**
     * Actual mains voltage
     *
     * Range: 0..5000 (0..500 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t nlg5_mv_act;

    /**
     * Actual battery output voltage
     *
     * Range: 0..10000 (0..1000 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t nlg5_ov_act;

    /**
     * Output current to the battery
     *
     * Range: 0..15000 (0..150 A)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t nlg5_oc_act;
};

/**
 * Signals in message NLG5_ACT_II.
 *
 * NLG5 Actual Values II (cycle_time: 100)
 *
 * All signal values are as on the CAN bus.
 */
struct charger_nlg5_act_ii_t {
    /**
     * Value of mains current limit, commanded by the control pilot (SAE J1772) signal
     *
     * Range: 0..1000 (0..100 A)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t nlg5_s_mc_m_cp;

    /**
     * Value of mains current limit, commanded by the 'power indicator' (PI) analogue input signal
     *
     * Range: 0..200 (0..20 A)
     * Scale: 0.1
     * Offset: 0
     */
    uint8_t nlg5_s_mc_m_pi;

    /**
     * Aux battery voltage
     *
     * Range: 0..250 (0..25 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint8_t nlg5_abv;
};

/**
 * Signals in message NLG5_TEMP.
 *
 * NLG5 Temp Feedback (cycle_time: 1000)
 *
 * All signal values are as on the CAN bus.
 */
struct charger_nlg5_temp_t {
    /**
     * Power stage temperature
     *
     * Range: -400..3000 (-40..300 Â°C)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t nlg5_p_tmp;

    /**
     * Value of external battery temperature sensor #1 (if connected and enabled)
     *
     * Range: -400..3000 (-40..300 Â°C)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t nlg5_tmp_ext1;

    /**
     * Value of external battery temperature sensor #2 (if connected and enabled)
     *
     * Range: -400..3000 (-40..300 Â°C)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t nlg5_tmp_ext2;

    /**
     * Value of external battery temperature sensor #3 (if connected and enabled)
     *
     * Range: -400..3000 (-40..300 Â°C)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t nlg5_tmp_ext3;
};

/**
 * Signals in message NLG5_ERR.
 *
 * NLG5 Errors/Warnings (cycle_time: 1000)
 *
 * All signal values are as on the CAN bus.
 */
struct charger_nlg5_err_t {
    /**
     * Mains fuse defective
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_e_mf;

    /**
     * Output fuse defective
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_e_of;

    /**
     * Plausibility mains voltage measurement wrong
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_e_p_mv;

    /**
     * Plausibility battery output voltage measurement wrong
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_e_p_om;

    /**
     * Power stage short circuit condition detected; error can only be cleared by cycling power ON-OFF-ON
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_e_sc;

    /**
     * Mains over-voltage 1 detected
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_e_mov_i;

    /**
     * Mains over-voltage 2 detected
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_e_mov_ii;

    /**
     * Battery output over-voltage; error can only be cleared by cycling power ON-OFF-ON
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_e_oov;

    /**
     * Ext. temperature sensor 3 defective (if enabled)
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_e_t_ext3;

    /**
     * Ext. temperature sensor 2 defective (if enabled), ext. temperature sensor 2 defective (if enabled)
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_e_t_ext2;

    /**
     * Ext. temperature sensor 1 defective (if enabled)
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_e_t_ext1;

    /**
     * Temperature sensor for transformer defective
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_e_t_tr;

    /**
     * Temperature sensor for diodes defective
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_e_t_dio;

    /**
     * Temperature sensor for prim power stage defective
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_e_t_pow;

    /**
     * Temperature sensor for prim capacitor defective
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_e_t_c;

    /**
     * Wrong battery polarity; error can only be cleared by cycling power ON-OFF-ON
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_e_b_p;

    /**
     * CAN off, transmit buffer >255
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_e_c_off;

    /**
     * CAN timeout, no control message received for >300 ms
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_e_c_to;

    /**
     * Initialisation error
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_e_init;

    /**
     * Internal Watchdog Timeout
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_e_wdt;

    /**
     * Pow EEPROM checksum failure
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_e_ep_crc;

    /**
     * Sys EEPROM checksum failure
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_e_es_crc;

    /**
     * NVSRAM check sum failure; contains most of the scaling & calibration values, CAN ID's and charging profile etc.
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_e_nv_crc;

    /**
     * Flash memory checksum failure
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_e_f_crc;

    /**
     * Emergency shutdown threshold 'Charging Time' is exceeded; see ChargeStar help section 'protective features'; error can only be cleared by cycling power ON-OFF-ON
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_e_sdt_ct;

    /**
     * Emergency shutdown threshold 'Amp Hours' is exceeded; see ChargeStar help section 'protective features'; error can only be cleared by cycling power ON-OFF-ON
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_e_sdt_ah;

    /**
     * Emergency shutdown threshold 'Battery Voltage' is exceeded; see ChargeStar help section 'protective features'; error can only be cleared by cycling power ON-OFF-ON
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_e_sdt_bv;

    /**
     * Emergency shutdown threshold 'Battery Temperature' is exceeded; see ChargeStar help section 'protective features'; error can only be cleared by cycling power ON-OFF-ON
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_e_sdt_bt;

    /**
     * CAN receiver buffer >127
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_e_c_rx;

    /**
     * CAN transmit buffer >127
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_e_c_tx;

    /**
     * Save-Charging-Mode reduces primary current to 3.95 A as long as one of the four internal temperature sensors indicates -18Â° C or less
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_w_sc_m;

    /**
     * LED output driver defective, LEDs can't be controlled by NLG5 anymore. Charging is still possible.
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_w_od;

    /**
     * NLG5 control message not active
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_w_cm_na;

    /**
     * Commanded value is out of specified range; max or min applicable value is assumed instead
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_w_c_vor;

    /**
     * Output power limited by charger internal excessive temperature
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_w_pl_it;

    /**
     * Output power limited by low battery voltage
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_w_pl_bv;

    /**
     * Output power limited by low mains voltage
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_w_pl_mv;
};

/**
 * Signals in message NLG5_CTL.
 *
 * NLG5 Control (cycle_time: 100)
 *
 * All signal values are as on the CAN bus.
 */
struct charger_nlg5_ctl_t {
    /**
     * Enables CP-State C to request mains voltage
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_c_mr;

    /**
     * Special signal to tell a charging station equipped with the Control pilot interface (SAE J1772) to switch on the facility's ventilation (in order to get rid of battery gases like hydrogen, e.g.)
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_c_cp_v;

    /**
     * Cycle this value 0-1-0 to clear all latched charger errors
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_c_c_el;

    /**
     * Must be ON to enable power stage of the charger
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nlg5_c_c_en;

    /**
     * Maximum current to be drawn from the mains outlet, usually 16 A. Must always contain a valid value in order to keep on charging
     *
     * Range: 0..500 (0..50 A)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t nlg5_mc_max;

    /**
     * Desired voltage to be output to the battery. Must always contain a valid value in order to keep on charging
     *
     * Range: 0..10000 (0..1000 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t nlg5_ov_com;

    /**
     * Desired battery current. Must always contain a valid value in order to keep on charging
     *
     * Range: 0..1500 (0..150 A)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t nlg5_oc_com;
};

/**
 * Signals in message NLG5_DIAG_RX.
 *
 * NLG5 Diag Rx
 *
 * All signal values are as on the CAN bus.
 */
struct charger_nlg5_diag_rx_t {
    /**
     * Diag requested data from host
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint64_t lad_d_param_rq;
};

/**
 * Signals in message NLG5_DIAG_TX.
 *
 * NLG5 Diag Tx
 *
 * All signal values are as on the CAN bus.
 */
struct charger_nlg5_diag_tx_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint64_t lad_d_param_rp;
};

/**
 * Pack message NLG5_ST.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int charger_nlg5_st_pack(
    uint8_t *dst_p,
    const struct charger_nlg5_st_t *src_p,
    size_t size);

/**
 * Unpack message NLG5_ST.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int charger_nlg5_st_unpack(
    struct charger_nlg5_st_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from NLG5_ST.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int charger_nlg5_st_init(struct charger_nlg5_st_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_st_nlg5_s_cp_dt_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_st_nlg5_s_cp_dt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_st_nlg5_s_cp_dt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_st_nlg5_s_um_ii_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_st_nlg5_s_um_ii_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_st_nlg5_s_um_ii_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_st_nlg5_s_um_i_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_st_nlg5_s_um_i_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_st_nlg5_s_um_i_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_st_nlg5_s_eum_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_st_nlg5_s_eum_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_st_nlg5_s_eum_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_st_nlg5_s_fan_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_st_nlg5_s_fan_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_st_nlg5_s_fan_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_st_nlg5_s_war_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_st_nlg5_s_war_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_st_nlg5_s_war_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_st_nlg5_s_err_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_st_nlg5_s_err_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_st_nlg5_s_err_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_st_nlg5_s_he_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_st_nlg5_s_he_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_st_nlg5_s_he_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_st_nlg5_s_l_pmax_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_st_nlg5_s_l_pmax_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_st_nlg5_s_l_pmax_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_st_nlg5_s_l_cp_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_st_nlg5_s_l_cp_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_st_nlg5_s_l_cp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_st_nlg5_s_l_pi_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_st_nlg5_s_l_pi_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_st_nlg5_s_l_pi_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_st_nlg5_s_l_mc_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_st_nlg5_s_l_mc_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_st_nlg5_s_l_mc_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_st_nlg5_s_l_oc_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_st_nlg5_s_l_oc_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_st_nlg5_s_l_oc_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_st_nlg5_s_l_ov_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_st_nlg5_s_l_ov_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_st_nlg5_s_l_ov_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_st_nlg5_s_bpd_ii_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_st_nlg5_s_bpd_ii_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_st_nlg5_s_bpd_ii_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_st_nlg5_s_bpd_i_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_st_nlg5_s_bpd_i_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_st_nlg5_s_bpd_i_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_st_nlg5_s_l_t_batt_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_st_nlg5_s_l_t_batt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_st_nlg5_s_l_t_batt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_st_nlg5_s_l_t_tr_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_st_nlg5_s_l_t_tr_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_st_nlg5_s_l_t_tr_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_st_nlg5_s_l_t_dio_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_st_nlg5_s_l_t_dio_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_st_nlg5_s_l_t_dio_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_st_nlg5_s_l_t_pow_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_st_nlg5_s_l_t_pow_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_st_nlg5_s_l_t_pow_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_st_nlg5_s_l_t_cprim_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_st_nlg5_s_l_t_cprim_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_st_nlg5_s_l_t_cprim_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_st_nlg5_s_l_mo_max_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_st_nlg5_s_l_mo_max_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_st_nlg5_s_l_mo_max_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_st_nlg5_s_l_oc_max_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_st_nlg5_s_l_oc_max_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_st_nlg5_s_l_oc_max_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_st_nlg5_s_l_mc_max_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_st_nlg5_s_l_mc_max_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_st_nlg5_s_l_mc_max_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_st_nlg5_s_aac_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_st_nlg5_s_aac_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_st_nlg5_s_aac_is_in_range(uint8_t value);

/**
 * Pack message NLG5_ACT_I.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int charger_nlg5_act_i_pack(
    uint8_t *dst_p,
    const struct charger_nlg5_act_i_t *src_p,
    size_t size);

/**
 * Unpack message NLG5_ACT_I.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int charger_nlg5_act_i_unpack(
    struct charger_nlg5_act_i_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from NLG5_ACT_I.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int charger_nlg5_act_i_init(struct charger_nlg5_act_i_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t charger_nlg5_act_i_nlg5_mc_act_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_act_i_nlg5_mc_act_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_act_i_nlg5_mc_act_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t charger_nlg5_act_i_nlg5_mv_act_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_act_i_nlg5_mv_act_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_act_i_nlg5_mv_act_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t charger_nlg5_act_i_nlg5_ov_act_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_act_i_nlg5_ov_act_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_act_i_nlg5_ov_act_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t charger_nlg5_act_i_nlg5_oc_act_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_act_i_nlg5_oc_act_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_act_i_nlg5_oc_act_is_in_range(uint16_t value);

/**
 * Pack message NLG5_ACT_II.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int charger_nlg5_act_ii_pack(
    uint8_t *dst_p,
    const struct charger_nlg5_act_ii_t *src_p,
    size_t size);

/**
 * Unpack message NLG5_ACT_II.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int charger_nlg5_act_ii_unpack(
    struct charger_nlg5_act_ii_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from NLG5_ACT_II.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int charger_nlg5_act_ii_init(struct charger_nlg5_act_ii_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t charger_nlg5_act_ii_nlg5_s_mc_m_cp_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_act_ii_nlg5_s_mc_m_cp_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_act_ii_nlg5_s_mc_m_cp_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_act_ii_nlg5_s_mc_m_pi_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_act_ii_nlg5_s_mc_m_pi_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_act_ii_nlg5_s_mc_m_pi_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_act_ii_nlg5_abv_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_act_ii_nlg5_abv_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_act_ii_nlg5_abv_is_in_range(uint8_t value);

/**
 * Pack message NLG5_TEMP.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int charger_nlg5_temp_pack(
    uint8_t *dst_p,
    const struct charger_nlg5_temp_t *src_p,
    size_t size);

/**
 * Unpack message NLG5_TEMP.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int charger_nlg5_temp_unpack(
    struct charger_nlg5_temp_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from NLG5_TEMP.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int charger_nlg5_temp_init(struct charger_nlg5_temp_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t charger_nlg5_temp_nlg5_p_tmp_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_temp_nlg5_p_tmp_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_temp_nlg5_p_tmp_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t charger_nlg5_temp_nlg5_tmp_ext1_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_temp_nlg5_tmp_ext1_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_temp_nlg5_tmp_ext1_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t charger_nlg5_temp_nlg5_tmp_ext2_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_temp_nlg5_tmp_ext2_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_temp_nlg5_tmp_ext2_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t charger_nlg5_temp_nlg5_tmp_ext3_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_temp_nlg5_tmp_ext3_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_temp_nlg5_tmp_ext3_is_in_range(uint16_t value);

/**
 * Pack message NLG5_ERR.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int charger_nlg5_err_pack(
    uint8_t *dst_p,
    const struct charger_nlg5_err_t *src_p,
    size_t size);

/**
 * Unpack message NLG5_ERR.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int charger_nlg5_err_unpack(
    struct charger_nlg5_err_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from NLG5_ERR.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int charger_nlg5_err_init(struct charger_nlg5_err_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_e_mf_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_e_mf_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_e_mf_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_e_of_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_e_of_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_e_of_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_e_p_mv_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_e_p_mv_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_e_p_mv_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_e_p_om_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_e_p_om_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_e_p_om_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_e_sc_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_e_sc_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_e_sc_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_e_mov_i_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_e_mov_i_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_e_mov_i_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_e_mov_ii_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_e_mov_ii_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_e_mov_ii_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_e_oov_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_e_oov_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_e_oov_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_e_t_ext3_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_e_t_ext3_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_e_t_ext3_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_e_t_ext2_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_e_t_ext2_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_e_t_ext2_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_e_t_ext1_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_e_t_ext1_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_e_t_ext1_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_e_t_tr_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_e_t_tr_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_e_t_tr_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_e_t_dio_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_e_t_dio_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_e_t_dio_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_e_t_pow_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_e_t_pow_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_e_t_pow_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_e_t_c_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_e_t_c_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_e_t_c_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_e_b_p_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_e_b_p_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_e_b_p_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_e_c_off_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_e_c_off_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_e_c_off_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_e_c_to_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_e_c_to_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_e_c_to_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_e_init_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_e_init_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_e_init_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_e_wdt_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_e_wdt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_e_wdt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_e_ep_crc_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_e_ep_crc_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_e_ep_crc_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_e_es_crc_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_e_es_crc_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_e_es_crc_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_e_nv_crc_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_e_nv_crc_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_e_nv_crc_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_e_f_crc_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_e_f_crc_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_e_f_crc_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_e_sdt_ct_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_e_sdt_ct_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_e_sdt_ct_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_e_sdt_ah_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_e_sdt_ah_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_e_sdt_ah_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_e_sdt_bv_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_e_sdt_bv_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_e_sdt_bv_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_e_sdt_bt_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_e_sdt_bt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_e_sdt_bt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_e_c_rx_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_e_c_rx_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_e_c_rx_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_e_c_tx_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_e_c_tx_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_e_c_tx_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_w_sc_m_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_w_sc_m_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_w_sc_m_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_w_od_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_w_od_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_w_od_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_w_cm_na_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_w_cm_na_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_w_cm_na_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_w_c_vor_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_w_c_vor_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_w_c_vor_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_w_pl_it_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_w_pl_it_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_w_pl_it_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_w_pl_bv_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_w_pl_bv_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_w_pl_bv_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_err_nlg5_w_pl_mv_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_err_nlg5_w_pl_mv_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_err_nlg5_w_pl_mv_is_in_range(uint8_t value);

/**
 * Pack message NLG5_CTL.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int charger_nlg5_ctl_pack(
    uint8_t *dst_p,
    const struct charger_nlg5_ctl_t *src_p,
    size_t size);

/**
 * Unpack message NLG5_CTL.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int charger_nlg5_ctl_unpack(
    struct charger_nlg5_ctl_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from NLG5_CTL.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int charger_nlg5_ctl_init(struct charger_nlg5_ctl_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_ctl_nlg5_c_mr_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_ctl_nlg5_c_mr_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_ctl_nlg5_c_mr_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_ctl_nlg5_c_cp_v_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_ctl_nlg5_c_cp_v_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_ctl_nlg5_c_cp_v_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_ctl_nlg5_c_c_el_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_ctl_nlg5_c_c_el_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_ctl_nlg5_c_c_el_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t charger_nlg5_ctl_nlg5_c_c_en_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_ctl_nlg5_c_c_en_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_ctl_nlg5_c_c_en_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t charger_nlg5_ctl_nlg5_mc_max_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_ctl_nlg5_mc_max_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_ctl_nlg5_mc_max_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t charger_nlg5_ctl_nlg5_ov_com_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_ctl_nlg5_ov_com_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_ctl_nlg5_ov_com_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t charger_nlg5_ctl_nlg5_oc_com_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_ctl_nlg5_oc_com_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_ctl_nlg5_oc_com_is_in_range(uint16_t value);

/**
 * Pack message NLG5_DIAG_RX.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int charger_nlg5_diag_rx_pack(
    uint8_t *dst_p,
    const struct charger_nlg5_diag_rx_t *src_p,
    size_t size);

/**
 * Unpack message NLG5_DIAG_RX.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int charger_nlg5_diag_rx_unpack(
    struct charger_nlg5_diag_rx_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from NLG5_DIAG_RX.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int charger_nlg5_diag_rx_init(struct charger_nlg5_diag_rx_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint64_t charger_nlg5_diag_rx_lad_d_param_rq_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_diag_rx_lad_d_param_rq_decode(uint64_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_diag_rx_lad_d_param_rq_is_in_range(uint64_t value);

/**
 * Pack message NLG5_DIAG_TX.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int charger_nlg5_diag_tx_pack(
    uint8_t *dst_p,
    const struct charger_nlg5_diag_tx_t *src_p,
    size_t size);

/**
 * Unpack message NLG5_DIAG_TX.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int charger_nlg5_diag_tx_unpack(
    struct charger_nlg5_diag_tx_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from NLG5_DIAG_TX.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int charger_nlg5_diag_tx_init(struct charger_nlg5_diag_tx_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint64_t charger_nlg5_diag_tx_lad_d_param_rp_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float charger_nlg5_diag_tx_lad_d_param_rp_decode(uint64_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool charger_nlg5_diag_tx_lad_d_param_rp_is_in_range(uint64_t value);


#ifdef __cplusplus
}
#endif

#endif
