/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.3 Wed Jan 31 12:04:17 2024.
 */

#include <string.h>

#include "inverter.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int inverter_emcu_status_1_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_status_1_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u32(src_p->uptime, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->uptime, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->uptime, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->uptime, 24u, 0xffu);

    return (4);
}

int inverter_emcu_status_1_unpack(
    struct inverter_emcu_status_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->uptime = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->uptime |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->uptime |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->uptime |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);

    return (0);
}

int inverter_emcu_status_1_init(struct inverter_emcu_status_1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_status_1_t));

    return 0;
}

uint32_t inverter_emcu_status_1_uptime_encode(float value)
{
    return (uint32_t)(value);
}

float inverter_emcu_status_1_uptime_decode(uint32_t value)
{
    return ((float)value);
}

bool inverter_emcu_status_1_uptime_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int inverter_emcu_status_2_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_status_2_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u8(src_p->pwr_stg_bit_state, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->em_ctrl_foc_bit_state, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->app_state_app, 0u, 0xffu);

    return (3);
}

int inverter_emcu_status_2_unpack(
    struct inverter_emcu_status_2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    dst_p->pwr_stg_bit_state = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->em_ctrl_foc_bit_state = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->app_state_app = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

int inverter_emcu_status_2_init(struct inverter_emcu_status_2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_status_2_t));

    return 0;
}

uint8_t inverter_emcu_status_2_pwr_stg_bit_state_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_status_2_pwr_stg_bit_state_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_status_2_pwr_stg_bit_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t inverter_emcu_status_2_em_ctrl_foc_bit_state_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_status_2_em_ctrl_foc_bit_state_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_status_2_em_ctrl_foc_bit_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t inverter_emcu_status_2_app_state_app_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_status_2_app_state_app_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_status_2_app_state_app_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int inverter_emcu_status_3_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_status_3_t *src_p,
    size_t size)
{
    uint16_t current_d;
    uint16_t current_q;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    current_d = (uint16_t)src_p->current_d;
    dst_p[0] |= pack_left_shift_u16(current_d, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(current_d, 8u, 0xffu);
    current_q = (uint16_t)src_p->current_q;
    dst_p[2] |= pack_left_shift_u16(current_q, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(current_q, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->volt_modulus, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->volt_modulus, 8u, 0x0fu);

    return (8);
}

int inverter_emcu_status_3_unpack(
    struct inverter_emcu_status_3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t current_d;
    uint16_t current_q;

    if (size < 8u) {
        return (-EINVAL);
    }

    current_d = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    current_d |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->current_d = (int16_t)current_d;
    current_q = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    current_q |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->current_q = (int16_t)current_q;
    dst_p->volt_modulus = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->volt_modulus |= unpack_left_shift_u16(src_p[5], 8u, 0x0fu);

    return (0);
}

int inverter_emcu_status_3_init(struct inverter_emcu_status_3_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_status_3_t));

    return 0;
}

int16_t inverter_emcu_status_3_current_d_encode(float value)
{
    return (int16_t)(value / 0.03125f);
}

float inverter_emcu_status_3_current_d_decode(int16_t value)
{
    return ((float)value * 0.03125f);
}

bool inverter_emcu_status_3_current_d_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t inverter_emcu_status_3_current_q_encode(float value)
{
    return (int16_t)(value / 0.03125f);
}

float inverter_emcu_status_3_current_q_decode(int16_t value)
{
    return ((float)value * 0.03125f);
}

bool inverter_emcu_status_3_current_q_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

uint16_t inverter_emcu_status_3_volt_modulus_encode(float value)
{
    return (uint16_t)(value);
}

float inverter_emcu_status_3_volt_modulus_decode(uint16_t value)
{
    return ((float)value);
}

bool inverter_emcu_status_3_volt_modulus_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

int inverter_emcu_status_4_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_status_4_t *src_p,
    size_t size)
{
    uint8_t dp_temp;
    uint8_t e_machine_temp_1;
    uint8_t e_machine_temp_2;
    uint8_t pwr_stg_temp;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    pwr_stg_temp = (uint8_t)src_p->pwr_stg_temp;
    dst_p[0] |= pack_left_shift_u8(pwr_stg_temp, 0u, 0xffu);
    dp_temp = (uint8_t)src_p->dp_temp;
    dst_p[1] |= pack_left_shift_u8(dp_temp, 0u, 0xffu);
    e_machine_temp_1 = (uint8_t)src_p->e_machine_temp_1;
    dst_p[2] |= pack_left_shift_u8(e_machine_temp_1, 0u, 0xffu);
    e_machine_temp_2 = (uint8_t)src_p->e_machine_temp_2;
    dst_p[3] |= pack_left_shift_u8(e_machine_temp_2, 0u, 0xffu);

    return (4);
}

int inverter_emcu_status_4_unpack(
    struct inverter_emcu_status_4_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t dp_temp;
    uint8_t e_machine_temp_1;
    uint8_t e_machine_temp_2;
    uint8_t pwr_stg_temp;

    if (size < 4u) {
        return (-EINVAL);
    }

    pwr_stg_temp = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->pwr_stg_temp = (int8_t)pwr_stg_temp;
    dp_temp = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->dp_temp = (int8_t)dp_temp;
    e_machine_temp_1 = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->e_machine_temp_1 = (int8_t)e_machine_temp_1;
    e_machine_temp_2 = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->e_machine_temp_2 = (int8_t)e_machine_temp_2;

    return (0);
}

int inverter_emcu_status_4_init(struct inverter_emcu_status_4_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_status_4_t));

    return 0;
}

int8_t inverter_emcu_status_4_pwr_stg_temp_encode(float value)
{
    return (int8_t)(value);
}

float inverter_emcu_status_4_pwr_stg_temp_decode(int8_t value)
{
    return ((float)value);
}

bool inverter_emcu_status_4_pwr_stg_temp_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t inverter_emcu_status_4_dp_temp_encode(float value)
{
    return (int8_t)(value);
}

float inverter_emcu_status_4_dp_temp_decode(int8_t value)
{
    return ((float)value);
}

bool inverter_emcu_status_4_dp_temp_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t inverter_emcu_status_4_e_machine_temp_1_encode(float value)
{
    return (int8_t)(value);
}

float inverter_emcu_status_4_e_machine_temp_1_decode(int8_t value)
{
    return ((float)value);
}

bool inverter_emcu_status_4_e_machine_temp_1_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t inverter_emcu_status_4_e_machine_temp_2_encode(float value)
{
    return (int8_t)(value);
}

float inverter_emcu_status_4_e_machine_temp_2_decode(int8_t value)
{
    return ((float)value);
}

bool inverter_emcu_status_4_e_machine_temp_2_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int inverter_emcu_status_5_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_status_5_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u8(src_p->cmd_src_app, 0u, 0x07u);
    dst_p[0] |= pack_left_shift_u8(src_p->ctrl_type_app, 3u, 0x38u);
    dst_p[1] |= pack_left_shift_u8(src_p->ctrl_mode_app, 0u, 0x0fu);
    dst_p[1] |= pack_left_shift_u8(src_p->pos_fb_src_app, 4u, 0xf0u);

    return (2);
}

int inverter_emcu_status_5_unpack(
    struct inverter_emcu_status_5_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->cmd_src_app = unpack_right_shift_u8(src_p[0], 0u, 0x07u);
    dst_p->ctrl_type_app = unpack_right_shift_u8(src_p[0], 3u, 0x38u);
    dst_p->ctrl_mode_app = unpack_right_shift_u8(src_p[1], 0u, 0x0fu);
    dst_p->pos_fb_src_app = unpack_right_shift_u8(src_p[1], 4u, 0xf0u);

    return (0);
}

int inverter_emcu_status_5_init(struct inverter_emcu_status_5_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_status_5_t));

    return 0;
}

uint8_t inverter_emcu_status_5_cmd_src_app_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_status_5_cmd_src_app_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_status_5_cmd_src_app_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t inverter_emcu_status_5_ctrl_type_app_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_status_5_ctrl_type_app_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_status_5_ctrl_type_app_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t inverter_emcu_status_5_ctrl_mode_app_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_status_5_ctrl_mode_app_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_status_5_ctrl_mode_app_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t inverter_emcu_status_5_pos_fb_src_app_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_status_5_pos_fb_src_app_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_status_5_pos_fb_src_app_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

int inverter_emcu_status_6_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_status_6_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u16(src_p->dem, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->dem, 8u, 0xffu);

    return (2);
}

int inverter_emcu_status_6_unpack(
    struct inverter_emcu_status_6_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->dem = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->dem |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

int inverter_emcu_status_6_init(struct inverter_emcu_status_6_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_status_6_t));

    return 0;
}

uint16_t inverter_emcu_status_6_dem_encode(float value)
{
    return (uint16_t)(value);
}

float inverter_emcu_status_6_dem_decode(uint16_t value)
{
    return ((float)value);
}

bool inverter_emcu_status_6_dem_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int inverter_emcu_setpoint_1_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_setpoint_1_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->app_state_req, 0u, 0xffu);

    return (1);
}

int inverter_emcu_setpoint_1_unpack(
    struct inverter_emcu_setpoint_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->app_state_req = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int inverter_emcu_setpoint_1_init(struct inverter_emcu_setpoint_1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_setpoint_1_t));

    return 0;
}

uint8_t inverter_emcu_setpoint_1_app_state_req_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_setpoint_1_app_state_req_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_setpoint_1_app_state_req_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int inverter_emcu_setpoint_2_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_setpoint_2_t *src_p,
    size_t size)
{
    uint16_t current_d_req;
    uint16_t current_q_req;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    current_d_req = (uint16_t)src_p->current_d_req;
    dst_p[0] |= pack_left_shift_u16(current_d_req, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(current_d_req, 8u, 0xffu);
    current_q_req = (uint16_t)src_p->current_q_req;
    dst_p[2] |= pack_left_shift_u16(current_q_req, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(current_q_req, 8u, 0xffu);

    return (4);
}

int inverter_emcu_setpoint_2_unpack(
    struct inverter_emcu_setpoint_2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t current_d_req;
    uint16_t current_q_req;

    if (size < 4u) {
        return (-EINVAL);
    }

    current_d_req = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    current_d_req |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->current_d_req = (int16_t)current_d_req;
    current_q_req = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    current_q_req |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->current_q_req = (int16_t)current_q_req;

    return (0);
}

int inverter_emcu_setpoint_2_init(struct inverter_emcu_setpoint_2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_setpoint_2_t));

    return 0;
}

int16_t inverter_emcu_setpoint_2_current_d_req_encode(float value)
{
    return (int16_t)(value / 0.03125f);
}

float inverter_emcu_setpoint_2_current_d_req_decode(int16_t value)
{
    return ((float)value * 0.03125f);
}

bool inverter_emcu_setpoint_2_current_d_req_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t inverter_emcu_setpoint_2_current_q_req_encode(float value)
{
    return (int16_t)(value / 0.03125f);
}

float inverter_emcu_setpoint_2_current_q_req_decode(int16_t value)
{
    return ((float)value * 0.03125f);
}

bool inverter_emcu_setpoint_2_current_q_req_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int inverter_emcu_setpoint_3_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_setpoint_3_t *src_p,
    size_t size)
{
    uint16_t torque_req;

    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    torque_req = (uint16_t)src_p->torque_req;
    dst_p[0] |= pack_left_shift_u16(torque_req, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(torque_req, 8u, 0xffu);

    return (2);
}

int inverter_emcu_setpoint_3_unpack(
    struct inverter_emcu_setpoint_3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t torque_req;

    if (size < 2u) {
        return (-EINVAL);
    }

    torque_req = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    torque_req |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->torque_req = (int16_t)torque_req;

    return (0);
}

int inverter_emcu_setpoint_3_init(struct inverter_emcu_setpoint_3_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_setpoint_3_t));

    return 0;
}

int16_t inverter_emcu_setpoint_3_torque_req_encode(float value)
{
    return (int16_t)(value);
}

float inverter_emcu_setpoint_3_torque_req_decode(int16_t value)
{
    return ((float)value);
}

bool inverter_emcu_setpoint_3_torque_req_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}
