/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.3 Mon Jan 22 12:15:42 2024.
 */

#ifndef INVERTER_H
#define INVERTER_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define INVERTER_EMCU_STATUS_1_FRAME_ID (0x760u)
#define INVERTER_EMCU_STATUS_2_FRAME_ID (0x761u)
#define INVERTER_EMCU_STATUS_3_FRAME_ID (0x762u)
#define INVERTER_EMCU_STATUS_4_FRAME_ID (0x763u)
#define INVERTER_EMCU_STATUS_5_FRAME_ID (0x764u)
#define INVERTER_EMCU_STATUS_6_FRAME_ID (0x765u)
#define INVERTER_EMCU_SETPOINT_1_FRAME_ID (0x660u)
#define INVERTER_EMCU_SETPOINT_2_FRAME_ID (0x661u)
#define INVERTER_EMCU_SETPOINT_3_FRAME_ID (0x662u)

/* Frame lengths in bytes. */
#define INVERTER_EMCU_STATUS_1_LENGTH (4u)
#define INVERTER_EMCU_STATUS_2_LENGTH (3u)
#define INVERTER_EMCU_STATUS_3_LENGTH (8u)
#define INVERTER_EMCU_STATUS_4_LENGTH (4u)
#define INVERTER_EMCU_STATUS_5_LENGTH (2u)
#define INVERTER_EMCU_STATUS_6_LENGTH (2u)
#define INVERTER_EMCU_SETPOINT_1_LENGTH (1u)
#define INVERTER_EMCU_SETPOINT_2_LENGTH (4u)
#define INVERTER_EMCU_SETPOINT_3_LENGTH (2u)

/* Extended or standard frame types. */
#define INVERTER_EMCU_STATUS_1_IS_EXTENDED (0)
#define INVERTER_EMCU_STATUS_2_IS_EXTENDED (0)
#define INVERTER_EMCU_STATUS_3_IS_EXTENDED (0)
#define INVERTER_EMCU_STATUS_4_IS_EXTENDED (0)
#define INVERTER_EMCU_STATUS_5_IS_EXTENDED (0)
#define INVERTER_EMCU_STATUS_6_IS_EXTENDED (0)
#define INVERTER_EMCU_SETPOINT_1_IS_EXTENDED (0)
#define INVERTER_EMCU_SETPOINT_2_IS_EXTENDED (0)
#define INVERTER_EMCU_SETPOINT_3_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */


/* Frame Names. */
#define INVERTER_EMCU_STATUS_1_NAME "EMCU_STATUS_1"
#define INVERTER_EMCU_STATUS_2_NAME "EMCU_STATUS_2"
#define INVERTER_EMCU_STATUS_3_NAME "EMCU_STATUS_3"
#define INVERTER_EMCU_STATUS_4_NAME "EMCU_STATUS_4"
#define INVERTER_EMCU_STATUS_5_NAME "EMCU_STATUS_5"
#define INVERTER_EMCU_STATUS_6_NAME "EMCU_STATUS_6"
#define INVERTER_EMCU_SETPOINT_1_NAME "EMCU_SETPOINT_1"
#define INVERTER_EMCU_SETPOINT_2_NAME "EMCU_SETPOINT_2"
#define INVERTER_EMCU_SETPOINT_3_NAME "EMCU_SETPOINT_3"

/* Signal Names. */
#define INVERTER_EMCU_STATUS_1_UPTIME_NAME "Uptime"
#define INVERTER_EMCU_STATUS_2_PWR_STG_BIT_STATE_NAME "PwrStg_BitState"
#define INVERTER_EMCU_STATUS_2_EM_CTRL_FOC_BIT_STATE_NAME "EMCtrl_FOC_BitState"
#define INVERTER_EMCU_STATUS_2_APP_STATE_APP_NAME "App_State_App"
#define INVERTER_EMCU_STATUS_3_CURRENT_D_NAME "Current_D"
#define INVERTER_EMCU_STATUS_3_CURRENT_Q_NAME "Current_Q"
#define INVERTER_EMCU_STATUS_3_VOLT_MODULUS_NAME "Volt_Modulus"
#define INVERTER_EMCU_STATUS_4_PWR_STG_TEMP_NAME "PwrStg_Temp"
#define INVERTER_EMCU_STATUS_4_DP_TEMP_NAME "DP_Temp"
#define INVERTER_EMCU_STATUS_4_E_MACHINE_TEMP_1_NAME "EMachine_Temp_1"
#define INVERTER_EMCU_STATUS_4_E_MACHINE_TEMP_2_NAME "EMachine_Temp_2"
#define INVERTER_EMCU_STATUS_5_CMD_SRC_APP_NAME "Cmd_Src_App"
#define INVERTER_EMCU_STATUS_5_CTRL_TYPE_APP_NAME "Ctrl_Type_App"
#define INVERTER_EMCU_STATUS_5_CTRL_MODE_APP_NAME "Ctrl_Mode_App"
#define INVERTER_EMCU_STATUS_5_POS_FB_SRC_APP_NAME "PosFb_Src_App"
#define INVERTER_EMCU_STATUS_6_DEM_NAME "Dem"
#define INVERTER_EMCU_SETPOINT_1_APP_STATE_REQ_NAME "App_State_Req"
#define INVERTER_EMCU_SETPOINT_2_CURRENT_D_REQ_NAME "Current_D_Req"
#define INVERTER_EMCU_SETPOINT_2_CURRENT_Q_REQ_NAME "Current_Q_Req"
#define INVERTER_EMCU_SETPOINT_3_TORQUE_REQ_NAME "Torque_Req"

/**
 * Signals in message EMCU_STATUS_1.
 *
 * All signal values are as on the CAN bus.
 */
struct inverter_emcu_status_1_t {
    /**
     * Control unit uptime in ms
     *
     * Range: 0..4294970000 (0..4294970000 -)
     * Scale: 1
     * Offset: 0
     */
    uint32_t uptime;
};

/**
 * Signals in message EMCU_STATUS_2.
 *
 * All signal values are as on the CAN bus.
 */
struct inverter_emcu_status_2_t {
    /**
     * Power Stage Status bitfield
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t pwr_stg_bit_state;

    /**
     * FOC controller status bitfield
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t em_ctrl_foc_bit_state;

    /**
     * Application state
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t app_state_app;
};

/**
 * Signals in message EMCU_STATUS_3.
 *
 * All signal values are as on the CAN bus.
 */
struct inverter_emcu_status_3_t {
    /**
     * Current feedback D-axis
     *
     * Range: -32768..32767 (-1024..1023.97 -)
     * Scale: 0.03125
     * Offset: 0
     */
    int16_t current_d;

    /**
     * Current feedback Q-axis
     *
     * Range: -32768..32767 (-1024..1023.97 -)
     * Scale: 0.03125
     * Offset: 0
     */
    int16_t current_q;

    /**
     * Voltage modulus
     *
     * Range: 0..4095 (0..4095 -)
     * Scale: 1
     * Offset: 0
     */
    uint16_t volt_modulus;
};

/**
 * Signals in message EMCU_STATUS_4.
 *
 * All signal values are as on the CAN bus.
 */
struct inverter_emcu_status_4_t {
    /**
     * Power Stage tempereture
     *
     * Range: -128..127 (-128..127 -)
     * Scale: 1
     * Offset: 0
     */
    int8_t pwr_stg_temp;

    /**
     * Digital platform temperature
     *
     * Range: -128..127 (-128..127 -)
     * Scale: 1
     * Offset: 0
     */
    int8_t dp_temp;

    /**
     * Machine temperature
     *
     * Range: -128..127 (-128..127 -)
     * Scale: 1
     * Offset: 0
     */
    int8_t e_machine_temp_1;

    /**
     * Machine temperature
     *
     * Range: -128..127 (-128..127 -)
     * Scale: 1
     * Offset: 0
     */
    int8_t e_machine_temp_2;
};

/**
 * Signals in message EMCU_STATUS_5.
 *
 * All signal values are as on the CAN bus.
 */
struct inverter_emcu_status_5_t {
    /**
     * Comands source
     *
     * Range: 0..7 (0..7 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t cmd_src_app;

    /**
     * Control Type
     *
     * Range: 0..7 (0..7 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ctrl_type_app;

    /**
     * Control Mode
     *
     * Range: 0..15 (0..15 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ctrl_mode_app;

    /**
     * Position Feedback source
     *
     * Range: 0..15 (0..15 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t pos_fb_src_app;
};

/**
 * Signals in message EMCU_STATUS_6.
 *
 * All signal values are as on the CAN bus.
 */
struct inverter_emcu_status_6_t {
    /**
     * Range: 0..65535 (0..65535 -)
     * Scale: 1
     * Offset: 0
     */
    uint16_t dem;
};

/**
 * Signals in message EMCU_SETPOINT_1.
 *
 * All signal values are as on the CAN bus.
 */
struct inverter_emcu_setpoint_1_t {
    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t app_state_req;
};

/**
 * Signals in message EMCU_SETPOINT_2.
 *
 * All signal values are as on the CAN bus.
 */
struct inverter_emcu_setpoint_2_t {
    /**
     * Current Setpoint
     *
     * Range: -32768..32767 (-1024..1023.97 -)
     * Scale: 0.03125
     * Offset: 0
     */
    int16_t current_d_req;

    /**
     * Current Setpoint
     *
     * Range: -32768..32767 (-1024..1023.97 -)
     * Scale: 0.03125
     * Offset: 0
     */
    int16_t current_q_req;
};

/**
 * Signals in message EMCU_SETPOINT_3.
 *
 * All signal values are as on the CAN bus.
 */
struct inverter_emcu_setpoint_3_t {
    /**
     * Torque Setponit
     *
     * Range: -32768..32767 (-32768..32767 -)
     * Scale: 1
     * Offset: 0
     */
    int16_t torque_req;
};

/**
 * Pack message EMCU_STATUS_1.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int inverter_emcu_status_1_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_status_1_t *src_p,
    size_t size);

/**
 * Unpack message EMCU_STATUS_1.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int inverter_emcu_status_1_unpack(
    struct inverter_emcu_status_1_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from EMCU_STATUS_1.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int inverter_emcu_status_1_init(struct inverter_emcu_status_1_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t inverter_emcu_status_1_uptime_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float inverter_emcu_status_1_uptime_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool inverter_emcu_status_1_uptime_is_in_range(uint32_t value);

/**
 * Pack message EMCU_STATUS_2.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int inverter_emcu_status_2_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_status_2_t *src_p,
    size_t size);

/**
 * Unpack message EMCU_STATUS_2.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int inverter_emcu_status_2_unpack(
    struct inverter_emcu_status_2_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from EMCU_STATUS_2.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int inverter_emcu_status_2_init(struct inverter_emcu_status_2_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t inverter_emcu_status_2_pwr_stg_bit_state_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float inverter_emcu_status_2_pwr_stg_bit_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool inverter_emcu_status_2_pwr_stg_bit_state_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t inverter_emcu_status_2_em_ctrl_foc_bit_state_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float inverter_emcu_status_2_em_ctrl_foc_bit_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool inverter_emcu_status_2_em_ctrl_foc_bit_state_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t inverter_emcu_status_2_app_state_app_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float inverter_emcu_status_2_app_state_app_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool inverter_emcu_status_2_app_state_app_is_in_range(uint8_t value);

/**
 * Pack message EMCU_STATUS_3.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int inverter_emcu_status_3_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_status_3_t *src_p,
    size_t size);

/**
 * Unpack message EMCU_STATUS_3.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int inverter_emcu_status_3_unpack(
    struct inverter_emcu_status_3_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from EMCU_STATUS_3.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int inverter_emcu_status_3_init(struct inverter_emcu_status_3_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t inverter_emcu_status_3_current_d_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float inverter_emcu_status_3_current_d_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool inverter_emcu_status_3_current_d_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t inverter_emcu_status_3_current_q_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float inverter_emcu_status_3_current_q_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool inverter_emcu_status_3_current_q_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t inverter_emcu_status_3_volt_modulus_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float inverter_emcu_status_3_volt_modulus_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool inverter_emcu_status_3_volt_modulus_is_in_range(uint16_t value);

/**
 * Pack message EMCU_STATUS_4.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int inverter_emcu_status_4_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_status_4_t *src_p,
    size_t size);

/**
 * Unpack message EMCU_STATUS_4.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int inverter_emcu_status_4_unpack(
    struct inverter_emcu_status_4_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from EMCU_STATUS_4.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int inverter_emcu_status_4_init(struct inverter_emcu_status_4_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t inverter_emcu_status_4_pwr_stg_temp_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float inverter_emcu_status_4_pwr_stg_temp_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool inverter_emcu_status_4_pwr_stg_temp_is_in_range(int8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t inverter_emcu_status_4_dp_temp_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float inverter_emcu_status_4_dp_temp_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool inverter_emcu_status_4_dp_temp_is_in_range(int8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t inverter_emcu_status_4_e_machine_temp_1_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float inverter_emcu_status_4_e_machine_temp_1_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool inverter_emcu_status_4_e_machine_temp_1_is_in_range(int8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t inverter_emcu_status_4_e_machine_temp_2_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float inverter_emcu_status_4_e_machine_temp_2_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool inverter_emcu_status_4_e_machine_temp_2_is_in_range(int8_t value);

/**
 * Pack message EMCU_STATUS_5.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int inverter_emcu_status_5_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_status_5_t *src_p,
    size_t size);

/**
 * Unpack message EMCU_STATUS_5.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int inverter_emcu_status_5_unpack(
    struct inverter_emcu_status_5_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from EMCU_STATUS_5.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int inverter_emcu_status_5_init(struct inverter_emcu_status_5_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t inverter_emcu_status_5_cmd_src_app_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float inverter_emcu_status_5_cmd_src_app_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool inverter_emcu_status_5_cmd_src_app_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t inverter_emcu_status_5_ctrl_type_app_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float inverter_emcu_status_5_ctrl_type_app_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool inverter_emcu_status_5_ctrl_type_app_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t inverter_emcu_status_5_ctrl_mode_app_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float inverter_emcu_status_5_ctrl_mode_app_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool inverter_emcu_status_5_ctrl_mode_app_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t inverter_emcu_status_5_pos_fb_src_app_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float inverter_emcu_status_5_pos_fb_src_app_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool inverter_emcu_status_5_pos_fb_src_app_is_in_range(uint8_t value);

/**
 * Pack message EMCU_STATUS_6.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int inverter_emcu_status_6_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_status_6_t *src_p,
    size_t size);

/**
 * Unpack message EMCU_STATUS_6.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int inverter_emcu_status_6_unpack(
    struct inverter_emcu_status_6_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from EMCU_STATUS_6.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int inverter_emcu_status_6_init(struct inverter_emcu_status_6_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t inverter_emcu_status_6_dem_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float inverter_emcu_status_6_dem_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool inverter_emcu_status_6_dem_is_in_range(uint16_t value);

/**
 * Pack message EMCU_SETPOINT_1.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int inverter_emcu_setpoint_1_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_setpoint_1_t *src_p,
    size_t size);

/**
 * Unpack message EMCU_SETPOINT_1.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int inverter_emcu_setpoint_1_unpack(
    struct inverter_emcu_setpoint_1_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from EMCU_SETPOINT_1.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int inverter_emcu_setpoint_1_init(struct inverter_emcu_setpoint_1_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t inverter_emcu_setpoint_1_app_state_req_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float inverter_emcu_setpoint_1_app_state_req_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool inverter_emcu_setpoint_1_app_state_req_is_in_range(uint8_t value);

/**
 * Pack message EMCU_SETPOINT_2.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int inverter_emcu_setpoint_2_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_setpoint_2_t *src_p,
    size_t size);

/**
 * Unpack message EMCU_SETPOINT_2.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int inverter_emcu_setpoint_2_unpack(
    struct inverter_emcu_setpoint_2_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from EMCU_SETPOINT_2.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int inverter_emcu_setpoint_2_init(struct inverter_emcu_setpoint_2_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t inverter_emcu_setpoint_2_current_d_req_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float inverter_emcu_setpoint_2_current_d_req_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool inverter_emcu_setpoint_2_current_d_req_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t inverter_emcu_setpoint_2_current_q_req_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float inverter_emcu_setpoint_2_current_q_req_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool inverter_emcu_setpoint_2_current_q_req_is_in_range(int16_t value);

/**
 * Pack message EMCU_SETPOINT_3.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int inverter_emcu_setpoint_3_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_setpoint_3_t *src_p,
    size_t size);

/**
 * Unpack message EMCU_SETPOINT_3.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int inverter_emcu_setpoint_3_unpack(
    struct inverter_emcu_setpoint_3_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from EMCU_SETPOINT_3.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int inverter_emcu_setpoint_3_init(struct inverter_emcu_setpoint_3_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t inverter_emcu_setpoint_3_torque_req_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float inverter_emcu_setpoint_3_torque_req_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool inverter_emcu_setpoint_3_torque_req_is_in_range(int16_t value);


#ifdef __cplusplus
}
#endif

#endif
