/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.3 Sat Jan 20 16:44:11 2024.
 */

#include <string.h>

#include "te_r23.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int te_r23_power_accu_pack(
    uint8_t *dst_p,
    const struct te_r23_power_accu_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u32(src_p->power, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->power, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->power, 16u, 0xffu);

    return (3);
}

int te_r23_power_accu_unpack(
    struct te_r23_power_accu_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    dst_p->power = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->power |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->power |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);

    return (0);
}

int te_r23_power_accu_init(struct te_r23_power_accu_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct te_r23_power_accu_t));

    return 0;
}

uint32_t te_r23_power_accu_power_encode(float value)
{
    return (uint32_t)(value);
}

float te_r23_power_accu_power_decode(uint32_t value)
{
    return ((float)value);
}

bool te_r23_power_accu_power_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

int te_r23_sensors_front_pack(
    uint8_t *dst_p,
    const struct te_r23_sensors_front_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->sens_f_accel1_adc, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->sens_f_accel1_adc, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->sens_f_accel2_adc, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->sens_f_accel2_adc, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->sens_f_accels_mean, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->lv_dash_bl_status, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->lv_dash_brake_adc, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->lv_dash_brake_adc, 8u, 0xffu);

    return (8);
}

int te_r23_sensors_front_unpack(
    struct te_r23_sensors_front_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->sens_f_accel1_adc = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->sens_f_accel1_adc |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->sens_f_accel2_adc = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->sens_f_accel2_adc |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->sens_f_accels_mean = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->lv_dash_bl_status = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->lv_dash_brake_adc = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->lv_dash_brake_adc |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int te_r23_sensors_front_init(struct te_r23_sensors_front_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct te_r23_sensors_front_t));

    return 0;
}

uint16_t te_r23_sensors_front_sens_f_accel1_adc_encode(float value)
{
    return (uint16_t)(value);
}

float te_r23_sensors_front_sens_f_accel1_adc_decode(uint16_t value)
{
    return ((float)value);
}

bool te_r23_sensors_front_sens_f_accel1_adc_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t te_r23_sensors_front_sens_f_accel2_adc_encode(float value)
{
    return (uint16_t)(value);
}

float te_r23_sensors_front_sens_f_accel2_adc_decode(uint16_t value)
{
    return ((float)value);
}

bool te_r23_sensors_front_sens_f_accel2_adc_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t te_r23_sensors_front_sens_f_accels_mean_encode(float value)
{
    return (uint8_t)(value);
}

float te_r23_sensors_front_sens_f_accels_mean_decode(uint8_t value)
{
    return ((float)value);
}

bool te_r23_sensors_front_sens_f_accels_mean_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t te_r23_sensors_front_lv_dash_bl_status_encode(float value)
{
    return (uint8_t)(value);
}

float te_r23_sensors_front_lv_dash_bl_status_decode(uint8_t value)
{
    return ((float)value);
}

bool te_r23_sensors_front_lv_dash_bl_status_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t te_r23_sensors_front_lv_dash_brake_adc_encode(float value)
{
    return (uint16_t)(value);
}

float te_r23_sensors_front_lv_dash_brake_adc_decode(uint16_t value)
{
    return ((float)value);
}

bool te_r23_sensors_front_lv_dash_brake_adc_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int te_r23_sensors_rear_pack(
    uint8_t *dst_p,
    const struct te_r23_sensors_rear_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->sens_r_multiplexor, 0u, 0xffu);

    switch (src_p->sens_r_multiplexor) {

    case 16:
        dst_p[1] |= pack_left_shift_u16(src_p->sens_r_refri_temp1, 0u, 0xffu);
        dst_p[2] |= pack_right_shift_u16(src_p->sens_r_refri_temp1, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->sens_r_refri_temp2, 0u, 0xffu);
        dst_p[4] |= pack_right_shift_u16(src_p->sens_r_refri_temp2, 8u, 0xffu);
        break;

    case 17:
        dst_p[1] |= pack_left_shift_u16(src_p->sens_r_refri_temp3, 0u, 0xffu);
        dst_p[2] |= pack_right_shift_u16(src_p->sens_r_refri_temp3, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->sens_r_refri_temp4, 0u, 0xffu);
        dst_p[4] |= pack_right_shift_u16(src_p->sens_r_refri_temp4, 8u, 0xffu);
        break;

    case 32:
        dst_p[1] |= pack_left_shift_u16(src_p->sens_r_w_speed_r_adc, 0u, 0xffu);
        dst_p[2] |= pack_right_shift_u16(src_p->sens_r_w_speed_r_adc, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->sens_r_w_speed_l_adc, 0u, 0xffu);
        dst_p[4] |= pack_right_shift_u16(src_p->sens_r_w_speed_l_adc, 8u, 0xffu);
        break;

    case 33:
        dst_p[1] |= pack_left_shift_u16(src_p->sens_r_suspen_r, 0u, 0xffu);
        dst_p[2] |= pack_right_shift_u16(src_p->sens_r_suspen_r, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->sens_r_suspen_l, 0u, 0xffu);
        dst_p[4] |= pack_right_shift_u16(src_p->sens_r_suspen_l, 8u, 0xffu);
        break;

    default:
        break;
    }

    return (8);
}

int te_r23_sensors_rear_unpack(
    struct te_r23_sensors_rear_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->sens_r_multiplexor = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    switch (dst_p->sens_r_multiplexor) {

    case 16:
        dst_p->sens_r_refri_temp1 = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
        dst_p->sens_r_refri_temp1 |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->sens_r_refri_temp2 = unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        dst_p->sens_r_refri_temp2 |= unpack_left_shift_u16(src_p[4], 8u, 0xffu);
        break;

    case 17:
        dst_p->sens_r_refri_temp3 = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
        dst_p->sens_r_refri_temp3 |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->sens_r_refri_temp4 = unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        dst_p->sens_r_refri_temp4 |= unpack_left_shift_u16(src_p[4], 8u, 0xffu);
        break;

    case 32:
        dst_p->sens_r_w_speed_r_adc = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
        dst_p->sens_r_w_speed_r_adc |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->sens_r_w_speed_l_adc = unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        dst_p->sens_r_w_speed_l_adc |= unpack_left_shift_u16(src_p[4], 8u, 0xffu);
        break;

    case 33:
        dst_p->sens_r_suspen_r = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
        dst_p->sens_r_suspen_r |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->sens_r_suspen_l = unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        dst_p->sens_r_suspen_l |= unpack_left_shift_u16(src_p[4], 8u, 0xffu);
        break;

    default:
        break;
    }

    return (0);
}

int te_r23_sensors_rear_init(struct te_r23_sensors_rear_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct te_r23_sensors_rear_t));

    return 0;
}

uint8_t te_r23_sensors_rear_sens_r_multiplexor_encode(float value)
{
    return (uint8_t)(value);
}

float te_r23_sensors_rear_sens_r_multiplexor_decode(uint8_t value)
{
    return ((float)value);
}

bool te_r23_sensors_rear_sens_r_multiplexor_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t te_r23_sensors_rear_sens_r_w_speed_r_adc_encode(float value)
{
    return (uint16_t)(value);
}

float te_r23_sensors_rear_sens_r_w_speed_r_adc_decode(uint16_t value)
{
    return ((float)value);
}

bool te_r23_sensors_rear_sens_r_w_speed_r_adc_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t te_r23_sensors_rear_sens_r_suspen_r_encode(float value)
{
    return (uint16_t)(value);
}

float te_r23_sensors_rear_sens_r_suspen_r_decode(uint16_t value)
{
    return ((float)value);
}

bool te_r23_sensors_rear_sens_r_suspen_r_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t te_r23_sensors_rear_sens_r_refri_temp3_encode(float value)
{
    return (uint16_t)(value);
}

float te_r23_sensors_rear_sens_r_refri_temp3_decode(uint16_t value)
{
    return ((float)value);
}

bool te_r23_sensors_rear_sens_r_refri_temp3_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t te_r23_sensors_rear_sens_r_refri_temp1_encode(float value)
{
    return (uint16_t)(value);
}

float te_r23_sensors_rear_sens_r_refri_temp1_decode(uint16_t value)
{
    return ((float)value);
}

bool te_r23_sensors_rear_sens_r_refri_temp1_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t te_r23_sensors_rear_sens_r_w_speed_l_adc_encode(float value)
{
    return (uint16_t)(value);
}

float te_r23_sensors_rear_sens_r_w_speed_l_adc_decode(uint16_t value)
{
    return ((float)value);
}

bool te_r23_sensors_rear_sens_r_w_speed_l_adc_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t te_r23_sensors_rear_sens_r_suspen_l_encode(float value)
{
    return (uint16_t)(value);
}

float te_r23_sensors_rear_sens_r_suspen_l_decode(uint16_t value)
{
    return ((float)value);
}

bool te_r23_sensors_rear_sens_r_suspen_l_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t te_r23_sensors_rear_sens_r_refri_temp4_encode(float value)
{
    return (uint16_t)(value);
}

float te_r23_sensors_rear_sens_r_refri_temp4_decode(uint16_t value)
{
    return ((float)value);
}

bool te_r23_sensors_rear_sens_r_refri_temp4_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t te_r23_sensors_rear_sens_r_refri_temp2_encode(float value)
{
    return (uint16_t)(value);
}

float te_r23_sensors_rear_sens_r_refri_temp2_decode(uint16_t value)
{
    return ((float)value);
}

bool te_r23_sensors_rear_sens_r_refri_temp2_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int te_r23_lv_rear_dash_pack(
    uint8_t *dst_p,
    const struct te_r23_lv_rear_dash_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u8(src_p->lv_rear_car_status, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->lv_rear_dash_tsms, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->lv_rear_dash_bspd, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->lv_rear_dash_ams, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->lv_rear_dash_imd, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->bspd_imp, 0u, 0xffu);

    return (6);
}

int te_r23_lv_rear_dash_unpack(
    struct te_r23_lv_rear_dash_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->lv_rear_car_status = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->lv_rear_dash_tsms = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->lv_rear_dash_bspd = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->lv_rear_dash_ams = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->lv_rear_dash_imd = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->bspd_imp = unpack_right_shift_u8(src_p[5], 0u, 0xffu);

    return (0);
}

int te_r23_lv_rear_dash_init(struct te_r23_lv_rear_dash_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct te_r23_lv_rear_dash_t));

    return 0;
}

uint8_t te_r23_lv_rear_dash_lv_rear_car_status_encode(float value)
{
    return (uint8_t)(value);
}

float te_r23_lv_rear_dash_lv_rear_car_status_decode(uint8_t value)
{
    return ((float)value);
}

bool te_r23_lv_rear_dash_lv_rear_car_status_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t te_r23_lv_rear_dash_lv_rear_dash_tsms_encode(float value)
{
    return (uint8_t)(value);
}

float te_r23_lv_rear_dash_lv_rear_dash_tsms_decode(uint8_t value)
{
    return ((float)value);
}

bool te_r23_lv_rear_dash_lv_rear_dash_tsms_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t te_r23_lv_rear_dash_lv_rear_dash_bspd_encode(float value)
{
    return (uint8_t)(value);
}

float te_r23_lv_rear_dash_lv_rear_dash_bspd_decode(uint8_t value)
{
    return ((float)value);
}

bool te_r23_lv_rear_dash_lv_rear_dash_bspd_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t te_r23_lv_rear_dash_lv_rear_dash_ams_encode(float value)
{
    return (uint8_t)(value);
}

float te_r23_lv_rear_dash_lv_rear_dash_ams_decode(uint8_t value)
{
    return ((float)value);
}

bool te_r23_lv_rear_dash_lv_rear_dash_ams_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t te_r23_lv_rear_dash_lv_rear_dash_imd_encode(float value)
{
    return (uint8_t)(value);
}

float te_r23_lv_rear_dash_lv_rear_dash_imd_decode(uint8_t value)
{
    return ((float)value);
}

bool te_r23_lv_rear_dash_lv_rear_dash_imd_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t te_r23_lv_rear_dash_bspd_imp_encode(float value)
{
    return (uint8_t)(value);
}

float te_r23_lv_rear_dash_bspd_imp_decode(uint8_t value)
{
    return ((float)value);
}

bool te_r23_lv_rear_dash_bspd_imp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int te_r23_lv_dash_pack(
    uint8_t *dst_p,
    const struct te_r23_lv_dash_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u8(src_p->button, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->lv_dash_conduction_mode, 0u, 0xffu);

    return (2);
}

int te_r23_lv_dash_unpack(
    struct te_r23_lv_dash_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->button = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->lv_dash_conduction_mode = unpack_right_shift_u8(src_p[1], 0u, 0xffu);

    return (0);
}

int te_r23_lv_dash_init(struct te_r23_lv_dash_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct te_r23_lv_dash_t));

    return 0;
}

uint8_t te_r23_lv_dash_button_encode(float value)
{
    return (uint8_t)(value);
}

float te_r23_lv_dash_button_decode(uint8_t value)
{
    return ((float)value);
}

bool te_r23_lv_dash_button_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t te_r23_lv_dash_lv_dash_conduction_mode_encode(float value)
{
    return (uint8_t)(value);
}

float te_r23_lv_dash_lv_dash_conduction_mode_decode(uint8_t value)
{
    return ((float)value);
}

bool te_r23_lv_dash_lv_dash_conduction_mode_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int te_r23_lv_bms_pack(
    uint8_t *dst_p,
    const struct te_r23_lv_bms_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->lv_bms_multiplexor, 0u, 0xffu);

    switch (src_p->lv_bms_multiplexor) {

    case 16:
        dst_p[1] |= pack_left_shift_u16(src_p->lv_bms_cell_v_1, 0u, 0xffu);
        dst_p[2] |= pack_right_shift_u16(src_p->lv_bms_cell_v_1, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->lv_bms_cell_v_2, 0u, 0xffu);
        dst_p[4] |= pack_right_shift_u16(src_p->lv_bms_cell_v_2, 8u, 0xffu);
        dst_p[5] |= pack_left_shift_u16(src_p->lv_bms_cell_v_3, 0u, 0xffu);
        dst_p[6] |= pack_right_shift_u16(src_p->lv_bms_cell_v_3, 8u, 0xffu);
        break;

    case 17:
        dst_p[1] |= pack_left_shift_u16(src_p->lv_bms_cell_v_4, 0u, 0xffu);
        dst_p[2] |= pack_right_shift_u16(src_p->lv_bms_cell_v_4, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->lv_bms_cell_v_5, 0u, 0xffu);
        dst_p[4] |= pack_right_shift_u16(src_p->lv_bms_cell_v_5, 8u, 0xffu);
        dst_p[5] |= pack_left_shift_u16(src_p->lv_bms_cell_v_6, 0u, 0xffu);
        dst_p[6] |= pack_right_shift_u16(src_p->lv_bms_cell_v_6, 8u, 0xffu);
        break;

    case 32:
        dst_p[1] |= pack_left_shift_u16(src_p->lv_bms_temp_1, 0u, 0xffu);
        dst_p[2] |= pack_right_shift_u16(src_p->lv_bms_temp_1, 8u, 0x0fu);
        dst_p[3] |= pack_left_shift_u16(src_p->lv_bms_temp_2, 0u, 0xffu);
        dst_p[4] |= pack_right_shift_u16(src_p->lv_bms_temp_2, 8u, 0x0fu);
        dst_p[5] |= pack_left_shift_u16(src_p->lv_bms_temp_3, 0u, 0xffu);
        dst_p[6] |= pack_right_shift_u16(src_p->lv_bms_temp_3, 8u, 0x0fu);
        break;

    case 33:
        dst_p[1] |= pack_left_shift_u16(src_p->lv_bms_current, 0u, 0xffu);
        dst_p[2] |= pack_right_shift_u16(src_p->lv_bms_current, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->lv_bms_vtot, 0u, 0xffu);
        dst_p[4] |= pack_right_shift_u16(src_p->lv_bms_vtot, 8u, 0xffu);
        break;

    case 48:
        dst_p[1] |= pack_left_shift_u8(src_p->lv_bms_status, 0u, 0xffu);
        dst_p[2] |= pack_left_shift_u16(src_p->lv_bms_min, 0u, 0xffu);
        dst_p[3] |= pack_right_shift_u16(src_p->lv_bms_min, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(src_p->lv_bms_mean, 0u, 0xffu);
        dst_p[5] |= pack_right_shift_u16(src_p->lv_bms_mean, 8u, 0xffu);
        dst_p[6] |= pack_left_shift_u16(src_p->lv_bms_max, 0u, 0xffu);
        dst_p[7] |= pack_right_shift_u16(src_p->lv_bms_max, 8u, 0xffu);
        break;

    default:
        break;
    }

    return (8);
}

int te_r23_lv_bms_unpack(
    struct te_r23_lv_bms_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->lv_bms_multiplexor = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    switch (dst_p->lv_bms_multiplexor) {

    case 16:
        dst_p->lv_bms_cell_v_1 = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
        dst_p->lv_bms_cell_v_1 |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->lv_bms_cell_v_2 = unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        dst_p->lv_bms_cell_v_2 |= unpack_left_shift_u16(src_p[4], 8u, 0xffu);
        dst_p->lv_bms_cell_v_3 = unpack_right_shift_u16(src_p[5], 0u, 0xffu);
        dst_p->lv_bms_cell_v_3 |= unpack_left_shift_u16(src_p[6], 8u, 0xffu);
        break;

    case 17:
        dst_p->lv_bms_cell_v_4 = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
        dst_p->lv_bms_cell_v_4 |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->lv_bms_cell_v_5 = unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        dst_p->lv_bms_cell_v_5 |= unpack_left_shift_u16(src_p[4], 8u, 0xffu);
        dst_p->lv_bms_cell_v_6 = unpack_right_shift_u16(src_p[5], 0u, 0xffu);
        dst_p->lv_bms_cell_v_6 |= unpack_left_shift_u16(src_p[6], 8u, 0xffu);
        break;

    case 32:
        dst_p->lv_bms_temp_1 = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
        dst_p->lv_bms_temp_1 |= unpack_left_shift_u16(src_p[2], 8u, 0x0fu);
        dst_p->lv_bms_temp_2 = unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        dst_p->lv_bms_temp_2 |= unpack_left_shift_u16(src_p[4], 8u, 0x0fu);
        dst_p->lv_bms_temp_3 = unpack_right_shift_u16(src_p[5], 0u, 0xffu);
        dst_p->lv_bms_temp_3 |= unpack_left_shift_u16(src_p[6], 8u, 0x0fu);
        break;

    case 33:
        dst_p->lv_bms_current = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
        dst_p->lv_bms_current |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->lv_bms_vtot = unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        dst_p->lv_bms_vtot |= unpack_left_shift_u16(src_p[4], 8u, 0xffu);
        break;

    case 48:
        dst_p->lv_bms_status = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
        dst_p->lv_bms_min = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
        dst_p->lv_bms_min |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        dst_p->lv_bms_mean = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        dst_p->lv_bms_mean |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
        dst_p->lv_bms_max = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
        dst_p->lv_bms_max |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
        break;

    default:
        break;
    }

    return (0);
}

int te_r23_lv_bms_init(struct te_r23_lv_bms_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct te_r23_lv_bms_t));

    return 0;
}

uint8_t te_r23_lv_bms_lv_bms_multiplexor_encode(float value)
{
    return (uint8_t)(value);
}

float te_r23_lv_bms_lv_bms_multiplexor_decode(uint8_t value)
{
    return ((float)value);
}

bool te_r23_lv_bms_lv_bms_multiplexor_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t te_r23_lv_bms_lv_bms_temp_1_encode(float value)
{
    return (uint16_t)(value);
}

float te_r23_lv_bms_lv_bms_temp_1_decode(uint16_t value)
{
    return ((float)value);
}

bool te_r23_lv_bms_lv_bms_temp_1_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint8_t te_r23_lv_bms_lv_bms_status_encode(float value)
{
    return (uint8_t)(value);
}

float te_r23_lv_bms_lv_bms_status_decode(uint8_t value)
{
    return ((float)value);
}

bool te_r23_lv_bms_lv_bms_status_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t te_r23_lv_bms_lv_bms_current_encode(float value)
{
    return (uint16_t)(value);
}

float te_r23_lv_bms_lv_bms_current_decode(uint16_t value)
{
    return ((float)value);
}

bool te_r23_lv_bms_lv_bms_current_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t te_r23_lv_bms_lv_bms_cell_v_4_encode(float value)
{
    return (uint16_t)(value);
}

float te_r23_lv_bms_lv_bms_cell_v_4_decode(uint16_t value)
{
    return ((float)value);
}

bool te_r23_lv_bms_lv_bms_cell_v_4_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t te_r23_lv_bms_lv_bms_cell_v_1_encode(float value)
{
    return (uint16_t)(value);
}

float te_r23_lv_bms_lv_bms_cell_v_1_decode(uint16_t value)
{
    return ((float)value);
}

bool te_r23_lv_bms_lv_bms_cell_v_1_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t te_r23_lv_bms_lv_bms_min_encode(float value)
{
    return (uint16_t)(value);
}

float te_r23_lv_bms_lv_bms_min_decode(uint16_t value)
{
    return ((float)value);
}

bool te_r23_lv_bms_lv_bms_min_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t te_r23_lv_bms_lv_bms_vtot_encode(float value)
{
    return (uint16_t)(value);
}

float te_r23_lv_bms_lv_bms_vtot_decode(uint16_t value)
{
    return ((float)value);
}

bool te_r23_lv_bms_lv_bms_vtot_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t te_r23_lv_bms_lv_bms_temp_2_encode(float value)
{
    return (uint16_t)(value / 1.61167f);
}

float te_r23_lv_bms_lv_bms_temp_2_decode(uint16_t value)
{
    return ((float)value * 1.61167f);
}

bool te_r23_lv_bms_lv_bms_temp_2_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t te_r23_lv_bms_lv_bms_cell_v_5_encode(float value)
{
    return (uint16_t)(value);
}

float te_r23_lv_bms_lv_bms_cell_v_5_decode(uint16_t value)
{
    return ((float)value);
}

bool te_r23_lv_bms_lv_bms_cell_v_5_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t te_r23_lv_bms_lv_bms_cell_v_2_encode(float value)
{
    return (uint16_t)(value);
}

float te_r23_lv_bms_lv_bms_cell_v_2_decode(uint16_t value)
{
    return ((float)value);
}

bool te_r23_lv_bms_lv_bms_cell_v_2_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t te_r23_lv_bms_lv_bms_mean_encode(float value)
{
    return (uint16_t)(value);
}

float te_r23_lv_bms_lv_bms_mean_decode(uint16_t value)
{
    return ((float)value);
}

bool te_r23_lv_bms_lv_bms_mean_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t te_r23_lv_bms_lv_bms_temp_3_encode(float value)
{
    return (uint16_t)(value);
}

float te_r23_lv_bms_lv_bms_temp_3_decode(uint16_t value)
{
    return ((float)value);
}

bool te_r23_lv_bms_lv_bms_temp_3_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t te_r23_lv_bms_lv_bms_cell_v_6_encode(float value)
{
    return (uint16_t)(value);
}

float te_r23_lv_bms_lv_bms_cell_v_6_decode(uint16_t value)
{
    return ((float)value);
}

bool te_r23_lv_bms_lv_bms_cell_v_6_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t te_r23_lv_bms_lv_bms_cell_v_3_encode(float value)
{
    return (uint16_t)(value);
}

float te_r23_lv_bms_lv_bms_cell_v_3_decode(uint16_t value)
{
    return ((float)value);
}

bool te_r23_lv_bms_lv_bms_cell_v_3_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t te_r23_lv_bms_lv_bms_max_encode(float value)
{
    return (uint16_t)(value);
}

float te_r23_lv_bms_lv_bms_max_decode(uint16_t value)
{
    return ((float)value);
}

bool te_r23_lv_bms_lv_bms_max_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

int te_r23_implausibility_pack(
    uint8_t *dst_p,
    const struct te_r23_implausibility_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->apps_imp, 0u, 0xffu);

    return (1);
}

int te_r23_implausibility_unpack(
    struct te_r23_implausibility_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->apps_imp = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int te_r23_implausibility_init(struct te_r23_implausibility_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct te_r23_implausibility_t));

    return 0;
}

uint8_t te_r23_implausibility_apps_imp_encode(float value)
{
    return (uint8_t)(value);
}

float te_r23_implausibility_apps_imp_decode(uint8_t value)
{
    return ((float)value);
}

bool te_r23_implausibility_apps_imp_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int te_r23_hv_acc_sl_pack(
    uint8_t *dst_p,
    const struct te_r23_hv_acc_sl_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u8(src_p->hv_acc_sl_bms, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->hv_acc_sl_imd, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->hv_acc_sl_tsms, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->hv_acc_sl_status, 0u, 0xffu);

    return (4);
}

int te_r23_hv_acc_sl_unpack(
    struct te_r23_hv_acc_sl_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->hv_acc_sl_bms = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->hv_acc_sl_imd = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->hv_acc_sl_tsms = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->hv_acc_sl_status = unpack_right_shift_u8(src_p[3], 0u, 0xffu);

    return (0);
}

int te_r23_hv_acc_sl_init(struct te_r23_hv_acc_sl_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct te_r23_hv_acc_sl_t));

    return 0;
}

uint8_t te_r23_hv_acc_sl_hv_acc_sl_bms_encode(float value)
{
    return (uint8_t)(value);
}

float te_r23_hv_acc_sl_hv_acc_sl_bms_decode(uint8_t value)
{
    return ((float)value);
}

bool te_r23_hv_acc_sl_hv_acc_sl_bms_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t te_r23_hv_acc_sl_hv_acc_sl_imd_encode(float value)
{
    return (uint8_t)(value);
}

float te_r23_hv_acc_sl_hv_acc_sl_imd_decode(uint8_t value)
{
    return ((float)value);
}

bool te_r23_hv_acc_sl_hv_acc_sl_imd_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t te_r23_hv_acc_sl_hv_acc_sl_tsms_encode(float value)
{
    return (uint8_t)(value);
}

float te_r23_hv_acc_sl_hv_acc_sl_tsms_decode(uint8_t value)
{
    return ((float)value);
}

bool te_r23_hv_acc_sl_hv_acc_sl_tsms_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t te_r23_hv_acc_sl_hv_acc_sl_status_encode(float value)
{
    return (uint8_t)(value);
}

float te_r23_hv_acc_sl_hv_acc_sl_status_decode(uint8_t value)
{
    return ((float)value);
}

bool te_r23_hv_acc_sl_hv_acc_sl_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}
