/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.5 Thu Apr 11 17:33:10 2024.
 */

#ifndef TER_H
#define TER_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define TER_TEMP_RR_FRAME_ID (0x3f8u)
#define TER_TEMP_RL_FRAME_ID (0x3fcu)
#define TER_TEMP_FR_FRAME_ID (0x3f4u)
#define TER_TEMP_FL_FRAME_ID (0x3f0u)
#define TER_BUTTONS_BIT_MAP_FRAME_ID (0x09u)
#define TER_APPS_FRAME_ID (0x03u)
#define TER_COMMAND_FRAME_ID (0x01u)
#define TER_BPPS_FRAME_ID (0x04u)
#define TER_STEER_FRAME_ID (0x05u)
#define TER_FRONT_RPM_FRAME_ID (0x115u)
#define TER_FRONT_V_FRAME_ID (0x116u)
#define TER_YPR_FRAME_ID (0x117u)
#define TER_LV_VOLTAGES_FRAME_ID (0x10u)
#define TER_LV_TEMPS_FRAME_ID (0x11u)
#define TER_LV_STATUS_FRAME_ID (0x12u)
#define TER_ANG_RATE_FRAME_ID (0x118u)
#define TER_GPS_LAT_LONG_FRAME_ID (0x119u)
#define TER_GPS_ALTITUDE_PRES_FRAME_ID (0x120u)
#define TER_ACCEL_FRAME_ID (0x121u)
#define TER_MAG_FRAME_ID (0x122u)
#define TER_VEL_BODY_FRAME_ID (0x123u)
#define TER_IMU_STATUS_FRAME_ID (0x124u)
#define TER_ECU_STATUS_FRAME_ID (0x25u)
#define TER_RESPONSE_FRAME_ID (0x02u)
#define TER_CHRG_STATUS_FRAME_ID (0x205u)

/* Frame lengths in bytes. */
#define TER_TEMP_RR_LENGTH (8u)
#define TER_TEMP_RL_LENGTH (8u)
#define TER_TEMP_FR_LENGTH (8u)
#define TER_TEMP_FL_LENGTH (8u)
#define TER_BUTTONS_BIT_MAP_LENGTH (8u)
#define TER_APPS_LENGTH (8u)
#define TER_COMMAND_LENGTH (8u)
#define TER_BPPS_LENGTH (1u)
#define TER_STEER_LENGTH (8u)
#define TER_FRONT_RPM_LENGTH (8u)
#define TER_FRONT_V_LENGTH (8u)
#define TER_YPR_LENGTH (8u)
#define TER_LV_VOLTAGES_LENGTH (8u)
#define TER_LV_TEMPS_LENGTH (3u)
#define TER_LV_STATUS_LENGTH (8u)
#define TER_ANG_RATE_LENGTH (8u)
#define TER_GPS_LAT_LONG_LENGTH (8u)
#define TER_GPS_ALTITUDE_PRES_LENGTH (8u)
#define TER_ACCEL_LENGTH (8u)
#define TER_MAG_LENGTH (8u)
#define TER_VEL_BODY_LENGTH (8u)
#define TER_IMU_STATUS_LENGTH (8u)
#define TER_ECU_STATUS_LENGTH (2u)
#define TER_RESPONSE_LENGTH (8u)
#define TER_CHRG_STATUS_LENGTH (8u)

/* Extended or standard frame types. */
#define TER_TEMP_RR_IS_EXTENDED (0)
#define TER_TEMP_RL_IS_EXTENDED (0)
#define TER_TEMP_FR_IS_EXTENDED (0)
#define TER_TEMP_FL_IS_EXTENDED (0)
#define TER_BUTTONS_BIT_MAP_IS_EXTENDED (0)
#define TER_APPS_IS_EXTENDED (0)
#define TER_COMMAND_IS_EXTENDED (0)
#define TER_BPPS_IS_EXTENDED (0)
#define TER_STEER_IS_EXTENDED (0)
#define TER_FRONT_RPM_IS_EXTENDED (0)
#define TER_FRONT_V_IS_EXTENDED (0)
#define TER_YPR_IS_EXTENDED (0)
#define TER_LV_VOLTAGES_IS_EXTENDED (0)
#define TER_LV_TEMPS_IS_EXTENDED (0)
#define TER_LV_STATUS_IS_EXTENDED (0)
#define TER_ANG_RATE_IS_EXTENDED (0)
#define TER_GPS_LAT_LONG_IS_EXTENDED (0)
#define TER_GPS_ALTITUDE_PRES_IS_EXTENDED (0)
#define TER_ACCEL_IS_EXTENDED (0)
#define TER_MAG_IS_EXTENDED (0)
#define TER_VEL_BODY_IS_EXTENDED (0)
#define TER_IMU_STATUS_IS_EXTENDED (0)
#define TER_ECU_STATUS_IS_EXTENDED (0)
#define TER_RESPONSE_IS_EXTENDED (1)
#define TER_CHRG_STATUS_IS_EXTENDED (1)

/* Frame cycle times in milliseconds. */


/* Signal choices. */
#define TER_COMMAND_CMD_CALIBRATE_APPS_MIN_CHOICE (1u)
#define TER_COMMAND_CMD_CALIBRATE_APPS_MAX_CHOICE (2u)
#define TER_COMMAND_CMD_CALIBRATE_BPPS_MIN_CHOICE (3u)
#define TER_COMMAND_CMD_CALIBRATE_BPPS_MAX_CHOICE (4u)
#define TER_COMMAND_CMD_CALIBRATE_STEER_LEFTEST_CHOICE (5u)
#define TER_COMMAND_CMD_CALIBRATE_STEER_RIGHTEST_CHOICE (6u)
#define TER_COMMAND_CMD_RESET_APPS_IMPLAUSABILITY_CHOICE (7u)
#define TER_COMMAND_CMD_PRECHARGE_CHOICE (8u)
#define TER_COMMAND_CMD_DISCHARGE_CHOICE (9u)
#define TER_COMMAND_CMD_BEEP_CHOICE (10u)
#define TER_COMMAND_CMD_READY2DRIVE_CHOICE (11u)
#define TER_COMMAND_CMD_POWER_LIMIT_CHOICE (128u)

#define TER_ECU_STATUS_STATE_WAIT_SL_CHOICE (0u)
#define TER_ECU_STATUS_STATE_READY2_PRECH_CHOICE (1u)
#define TER_ECU_STATUS_STATE_PRECHARGING_CHOICE (2u)
#define TER_ECU_STATUS_STATE_PRECHARGED_CHOICE (3u)
#define TER_ECU_STATUS_STATE_DRIVING_CHOICE (4u)

#define TER_RESPONSE_CODE_OK_CHOICE (1u)
#define TER_RESPONSE_CODE_ERROR_CHOICE (2u)
#define TER_RESPONSE_CODE_INVALID_STATE_CHOICE (3u)
#define TER_RESPONSE_CODE_OUT_OF_RANGE_CHOICE (4u)

#define TER_CHRG_STATUS_STATE_IDLE_CHOICE (0u)
#define TER_CHRG_STATUS_STATE_READY_CHOICE (1u)
#define TER_CHRG_STATUS_STATE_PRECHARGING_CHOICE (2u)
#define TER_CHRG_STATUS_STATE_PRECHARGED_CHOICE (3u)
#define TER_CHRG_STATUS_STATE_CHARGING_CHOICE (4u)

/* Frame Names. */
#define TER_TEMP_RR_NAME "Temp_RR"
#define TER_TEMP_RL_NAME "Temp_RL"
#define TER_TEMP_FR_NAME "Temp_FR"
#define TER_TEMP_FL_NAME "Temp_FL"
#define TER_BUTTONS_BIT_MAP_NAME "Buttons_BitMap"
#define TER_APPS_NAME "APPS"
#define TER_COMMAND_NAME "COMMAND"
#define TER_BPPS_NAME "BPPS"
#define TER_STEER_NAME "STEER"
#define TER_FRONT_RPM_NAME "Front_RPM"
#define TER_FRONT_V_NAME "Front_V"
#define TER_YPR_NAME "YPR"
#define TER_LV_VOLTAGES_NAME "LV_Voltages"
#define TER_LV_TEMPS_NAME "LV_Temps"
#define TER_LV_STATUS_NAME "LV_Status"
#define TER_ANG_RATE_NAME "AngRate"
#define TER_GPS_LAT_LONG_NAME "GPS_Lat_Long"
#define TER_GPS_ALTITUDE_PRES_NAME "GPS_Altitude_Pres"
#define TER_ACCEL_NAME "Accel"
#define TER_MAG_NAME "Mag"
#define TER_VEL_BODY_NAME "VelBody"
#define TER_IMU_STATUS_NAME "ImuStatus"
#define TER_ECU_STATUS_NAME "ECU_Status"
#define TER_RESPONSE_NAME "RESPONSE"
#define TER_CHRG_STATUS_NAME "CHRG_Status"

/* Signal Names. */
#define TER_TEMP_RR_TW1_NAME "TW1"
#define TER_TEMP_RR_TW2_NAME "TW2"
#define TER_TEMP_RR_TW3_NAME "TW3"
#define TER_TEMP_RR_TW4_NAME "TW4"
#define TER_TEMP_RL_TW1_NAME "TW1"
#define TER_TEMP_RL_TW2_NAME "TW2"
#define TER_TEMP_RL_TW3_NAME "TW3"
#define TER_TEMP_RL_TW4_NAME "TW4"
#define TER_TEMP_FR_TW1_NAME "TW1"
#define TER_TEMP_FR_TW2_NAME "TW2"
#define TER_TEMP_FR_TW3_NAME "TW3"
#define TER_TEMP_FR_TW4_NAME "TW4"
#define TER_TEMP_FL_TW1_NAME "TW1"
#define TER_TEMP_FL_TW2_NAME "TW2"
#define TER_TEMP_FL_TW3_NAME "TW3"
#define TER_TEMP_FL_TW4_NAME "TW4"
#define TER_BUTTONS_BIT_MAP_LD_NAME "LD"
#define TER_BUTTONS_BIT_MAP_LI_NAME "LI"
#define TER_BUTTONS_BIT_MAP_R1_NAME "r1"
#define TER_BUTTONS_BIT_MAP_R2_NAME "r2"
#define TER_BUTTONS_BIT_MAP_R3_NAME "r3"
#define TER_BUTTONS_BIT_MAP_R4_NAME "r4"
#define TER_BUTTONS_BIT_MAP_R5_NAME "r5"
#define TER_BUTTONS_BIT_MAP_R6_NAME "r6"
#define TER_APPS_APPS_1_NAME "APPS_1"
#define TER_APPS_APPS_2_NAME "APPS_2"
#define TER_APPS_APPS_AV_NAME "APPS_AV"
#define TER_APPS_IMP_FLAG_NAME "IMP_FLAG"
#define TER_COMMAND_CMD_NAME "CMD"
#define TER_COMMAND_KW_LIM_NAME "kwLim"
#define TER_BPPS_BPPS_NAME "BPPS"
#define TER_STEER_ANGLE_NAME "ANGLE"
#define TER_FRONT_RPM_RPM_L_NAME "RPM_L"
#define TER_FRONT_RPM_RPM_R_NAME "RPM_R"
#define TER_FRONT_V_VX_L_NAME "vx_l"
#define TER_FRONT_V_VX_R_NAME "vx_r"
#define TER_FRONT_V_VX_AV_NAME "vx_av"
#define TER_YPR_PITCH_NAME "PITCH"
#define TER_YPR_ROLL_NAME "ROLL"
#define TER_YPR_YAW_NAME "YAW"
#define TER_LV_VOLTAGES_V1_NAME "V1"
#define TER_LV_VOLTAGES_V2_NAME "V2"
#define TER_LV_VOLTAGES_V3_NAME "V3"
#define TER_LV_VOLTAGES_V4_NAME "V4"
#define TER_LV_VOLTAGES_V5_NAME "V5"
#define TER_LV_VOLTAGES_V6_NAME "V6"
#define TER_LV_TEMPS_T1_NAME "T1"
#define TER_LV_TEMPS_T2_NAME "T2"
#define TER_LV_TEMPS_T3_NAME "T3"
#define TER_LV_STATUS_LV_STATUS_NAME "LV_Status"
#define TER_LV_STATUS_LV_VOLTAGE_OK_NAME "LV_VoltageOK"
#define TER_LV_STATUS_LV_TEMP_OK_NAME "LV_TempOK"
#define TER_LV_STATUS_LV_CURRENT_OK_NAME "LV_CurrentOK"
#define TER_LV_STATUS_REFRI_ON_NAME "REFRI_ON"
#define TER_LV_STATUS_LV_ON_NAME "LV_ON"
#define TER_LV_STATUS_LV_CURRENT_NAME "LV_Current"
#define TER_LV_STATUS_V_MAX_NAME "V_max"
#define TER_LV_STATUS_V_MEAN_NAME "V_mean"
#define TER_LV_STATUS_V_MIN_NAME "V_min"
#define TER_LV_STATUS_V_TOT_NAME "V_tot"
#define TER_ANG_RATE_ROLL_RATE_X_NAME "Roll_Rate_x"
#define TER_ANG_RATE_PITCH_RATE_Y_NAME "Pitch_Rate_y"
#define TER_ANG_RATE_YAW_RATE_Z_NAME "Yaw_Rate_z"
#define TER_GPS_LAT_LONG_LATITUDE_NAME "Latitude"
#define TER_GPS_LAT_LONG_LONGITUDE_NAME "Longitude"
#define TER_GPS_ALTITUDE_PRES_ALTIDUDE_NAME "Altidude"
#define TER_GPS_ALTITUDE_PRES_BAROMETRIC_PRESSURE_NAME "Barometric_Pressure"
#define TER_ACCEL_A_X_NAME "a_x"
#define TER_ACCEL_A_Y_NAME "a_y"
#define TER_ACCEL_A_Z_NAME "a_z"
#define TER_MAG_HEADING_NAME "Heading"
#define TER_VEL_BODY_V_X_NAME "v_x"
#define TER_VEL_BODY_V_Y_NAME "v_y"
#define TER_VEL_BODY_V_Z_NAME "v_z"
#define TER_IMU_STATUS_STATUS_NAME "Status"
#define TER_IMU_STATUS_POS_U_NAME "PosU"
#define TER_IMU_STATUS_VEL_U_NAME "VelU"
#define TER_ECU_STATUS_SL_STATUS_NAME "SL_Status"
#define TER_ECU_STATUS_STATE_NAME "State"
#define TER_ECU_STATUS_R2D_NAME "r2d"
#define TER_ECU_STATUS_BSPD_STATUS_NAME "BSPD_Status"
#define TER_RESPONSE_CMD_NAME "CMD"
#define TER_RESPONSE_CODE_NAME "CODE"
#define TER_CHRG_STATUS_STATE_NAME "State"
#define TER_CHRG_STATUS_VOLTAGE_NAME "Voltage"
#define TER_CHRG_STATUS_CURRENT_NAME "Current"

/**
 * Signals in message Temp_RR.
 *
 * All signal values are as on the CAN bus.
 */
struct ter_temp_rr_t {
    /**
     * Range: -32768..32767 (-3276.8..3276.7 -)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t tw1;

    /**
     * Range: -32768..32767 (-3276.8..3276.7 -)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t tw2;

    /**
     * Range: -32768..32767 (-3276.8..3276.7 -)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t tw3;

    /**
     * Range: -32768..32767 (-3276.8..3276.7 -)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t tw4;
};

/**
 * Signals in message Temp_RL.
 *
 * All signal values are as on the CAN bus.
 */
struct ter_temp_rl_t {
    /**
     * Range: -32768..32767 (-3276.8..3276.7 -)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t tw1;

    /**
     * Range: -32768..32767 (-3276.8..3276.7 -)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t tw2;

    /**
     * Range: -32768..32767 (-3276.8..3276.7 -)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t tw3;

    /**
     * Range: -32768..32767 (-3276.8..3276.7 -)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t tw4;
};

/**
 * Signals in message Temp_FR.
 *
 * All signal values are as on the CAN bus.
 */
struct ter_temp_fr_t {
    /**
     * Range: -32768..32767 (-3276.8..3276.7 -)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t tw1;

    /**
     * Range: -32768..32767 (-3276.8..3276.7 -)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t tw2;

    /**
     * Range: -32768..32767 (-3276.8..3276.7 -)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t tw3;

    /**
     * Range: -32768..32767 (-3276.8..3276.7 -)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t tw4;
};

/**
 * Signals in message Temp_FL.
 *
 * All signal values are as on the CAN bus.
 */
struct ter_temp_fl_t {
    /**
     * Range: -32768..32767 (-3276.8..3276.7 -)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t tw1;

    /**
     * Range: -32768..32767 (-3276.8..3276.7 -)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t tw2;

    /**
     * Range: -32768..32767 (-3276.8..3276.7 -)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t tw3;

    /**
     * Range: -32768..32767 (-3276.8..3276.7 -)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t tw4;
};

/**
 * Signals in message Buttons_BitMap.
 *
 * All signal values are as on the CAN bus.
 */
struct ter_buttons_bit_map_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t ld;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t li;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t r1;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t r2;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t r3;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t r4;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t r5;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t r6;
};

/**
 * Signals in message APPS.
 *
 * All signal values are as on the CAN bus.
 */
struct ter_apps_t {
    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t apps_1;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t apps_2;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t apps_av;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t imp_flag;
};

/**
 * Signals in message COMMAND.
 *
 * Command Subsystem
 *
 * All signal values are as on the CAN bus.
 */
struct ter_command_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t cmd;

    /**
     * Power_Limit_in_KW
     *
     * Range: 0..120 (0..120 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t kw_lim;
};

/**
 * Signals in message BPPS.
 *
 * All signal values are as on the CAN bus.
 */
struct ter_bpps_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t bpps;
};

/**
 * Signals in message STEER.
 *
 * All signal values are as on the CAN bus.
 */
struct ter_steer_t {
    /**
     * Range: -360..360 (-360..360 Grad)
     * Scale: 1
     * Offset: 0
     */
    int16_t angle;
};

/**
 * Signals in message Front_RPM.
 *
 * All signal values are as on the CAN bus.
 */
struct ter_front_rpm_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint16_t rpm_l;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint16_t rpm_r;
};

/**
 * Signals in message Front_V.
 *
 * All signal values are as on the CAN bus.
 */
struct ter_front_v_t {
    /**
     * Range: 0..100 (0..1 -)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t vx_l;

    /**
     * Range: 0..100 (0..1 -)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t vx_r;

    /**
     * Range: 0..100 (0..1 -)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t vx_av;
};

/**
 * Signals in message YPR.
 *
 * All signal values are as on the CAN bus.
 */
struct ter_ypr_t {
    /**
     * Range: 0..100 (0..1 -)
     * Scale: 0.01
     * Offset: 0
     */
    int32_t pitch;

    /**
     * Range: 0..100 (0..1 -)
     * Scale: 0.01
     * Offset: 0
     */
    int32_t roll;

    /**
     * Range: 0..100 (0..1 -)
     * Scale: 0.01
     * Offset: 0
     */
    int32_t yaw;
};

/**
 * Signals in message LV_Voltages.
 *
 * All signal values are as on the CAN bus.
 */
struct ter_lv_voltages_t {
    /**
     * Range: 0..100 (0..1 -)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t v1;

    /**
     * Range: 0..100 (0..1 -)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t v2;

    /**
     * Range: 0..100 (0..1 -)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t v3;

    /**
     * Range: 0..100 (0..1 -)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t v4;

    /**
     * Range: 0..100 (0..1 -)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t v5;

    /**
     * Range: 0..100 (0..1 -)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t v6;
};

/**
 * Signals in message LV_Temps.
 *
 * All signal values are as on the CAN bus.
 */
struct ter_lv_temps_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t t1;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t t2;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t t3;
};

/**
 * Signals in message LV_Status.
 *
 * All signal values are as on the CAN bus.
 */
struct ter_lv_status_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t lv_status;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t lv_voltage_ok;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t lv_temp_ok;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t lv_current_ok;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t refri_on;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t lv_on;

    /**
     * Range: 0..10 (0..1 -)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t lv_current;

    /**
     * Range: -
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t v_max;

    /**
     * Range: -
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t v_mean;

    /**
     * Range: -
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t v_min;

    /**
     * Range: -
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t v_tot;
};

/**
 * Signals in message AngRate.
 *
 * All signal values are as on the CAN bus.
 */
struct ter_ang_rate_t {
    /**
     * Range: 0..1000 (0..1 -)
     * Scale: 0.001
     * Offset: 0
     */
    int32_t roll_rate_x;

    /**
     * Range: 0..1000 (0..1 -)
     * Scale: 0.001
     * Offset: 0
     */
    int32_t pitch_rate_y;

    /**
     * Range: 0..1000 (0..1 -)
     * Scale: 0.001
     * Offset: 0
     */
    int32_t yaw_rate_z;
};

/**
 * Signals in message GPS_Lat_Long.
 *
 * All signal values are as on the CAN bus.
 */
struct ter_gps_lat_long_t {
    /**
     * Range: 0..10000000 (0..1 -)
     * Scale: 1e-07
     * Offset: 0
     */
    int32_t latitude;

    /**
     * Range: 0..10000000 (0..1 -)
     * Scale: 1e-07
     * Offset: 0
     */
    int32_t longitude;
};

/**
 * Signals in message GPS_Altitude_Pres.
 *
 * All signal values are as on the CAN bus.
 */
struct ter_gps_altitude_pres_t {
    /**
     * Range: 0..10000000 (0..1 -)
     * Scale: 1e-07
     * Offset: 0
     */
    int32_t altidude;

    /**
     * Range: 0..10000000 (0..1 -)
     * Scale: 1e-07
     * Offset: 0
     */
    int16_t barometric_pressure;
};

/**
 * Signals in message Accel.
 *
 * All signal values are as on the CAN bus.
 */
struct ter_accel_t {
    /**
     * Range: 0..1000 (0..1 -)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t a_x;

    /**
     * Range: 0..1000 (0..1 -)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t a_y;

    /**
     * Range: 0..1000 (0..1 -)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t a_z;
};

/**
 * Signals in message Mag.
 *
 * All signal values are as on the CAN bus.
 */
struct ter_mag_t {
    /**
     * Range: 0..100 (0..1 -)
     * Scale: 0.01
     * Offset: 0
     */
    int16_t heading;
};

/**
 * Signals in message VelBody.
 *
 * All signal values are as on the CAN bus.
 */
struct ter_vel_body_t {
    /**
     * Range: 0..1000 (0..1 -)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t v_x;

    /**
     * Range: 0..1000 (0..1 -)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t v_y;

    /**
     * Range: 0..1000 (0..1 -)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t v_z;
};

/**
 * Signals in message ImuStatus.
 *
 * All signal values are as on the CAN bus.
 */
struct ter_imu_status_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    int16_t status;

    /**
     * Range: 0..1000 (0..1 -)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t pos_u;

    /**
     * Range: 0..1000 (0..1 -)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t vel_u;
};

/**
 * Signals in message ECU_Status.
 *
 * All signal values are as on the CAN bus.
 */
struct ter_ecu_status_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t sl_status;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t state;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t r2d;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t bspd_status;
};

/**
 * Signals in message RESPONSE.
 *
 * All signal values are as on the CAN bus.
 */
struct ter_response_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t cmd;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t code;
};

/**
 * Signals in message CHRG_Status.
 *
 * All signal values are as on the CAN bus.
 */
struct ter_chrg_status_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t state;

    /**
     * Range: 0..1 (0..1 V)
     * Scale: 1
     * Offset: 0
     */
    uint16_t voltage;

    /**
     * Range: 0..1 (0..1 A)
     * Scale: 1
     * Offset: 0
     */
    uint8_t current;
};

/**
 * Pack message Temp_RR.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ter_temp_rr_pack(
    uint8_t *dst_p,
    const struct ter_temp_rr_t *src_p,
    size_t size);

/**
 * Unpack message Temp_RR.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ter_temp_rr_unpack(
    struct ter_temp_rr_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Temp_RR.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ter_temp_rr_init(struct ter_temp_rr_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ter_temp_rr_tw1_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_temp_rr_tw1_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_temp_rr_tw1_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ter_temp_rr_tw2_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_temp_rr_tw2_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_temp_rr_tw2_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ter_temp_rr_tw3_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_temp_rr_tw3_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_temp_rr_tw3_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ter_temp_rr_tw4_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_temp_rr_tw4_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_temp_rr_tw4_is_in_range(int16_t value);

/**
 * Pack message Temp_RL.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ter_temp_rl_pack(
    uint8_t *dst_p,
    const struct ter_temp_rl_t *src_p,
    size_t size);

/**
 * Unpack message Temp_RL.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ter_temp_rl_unpack(
    struct ter_temp_rl_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Temp_RL.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ter_temp_rl_init(struct ter_temp_rl_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ter_temp_rl_tw1_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_temp_rl_tw1_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_temp_rl_tw1_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ter_temp_rl_tw2_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_temp_rl_tw2_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_temp_rl_tw2_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ter_temp_rl_tw3_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_temp_rl_tw3_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_temp_rl_tw3_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ter_temp_rl_tw4_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_temp_rl_tw4_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_temp_rl_tw4_is_in_range(int16_t value);

/**
 * Pack message Temp_FR.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ter_temp_fr_pack(
    uint8_t *dst_p,
    const struct ter_temp_fr_t *src_p,
    size_t size);

/**
 * Unpack message Temp_FR.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ter_temp_fr_unpack(
    struct ter_temp_fr_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Temp_FR.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ter_temp_fr_init(struct ter_temp_fr_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ter_temp_fr_tw1_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_temp_fr_tw1_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_temp_fr_tw1_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ter_temp_fr_tw2_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_temp_fr_tw2_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_temp_fr_tw2_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ter_temp_fr_tw3_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_temp_fr_tw3_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_temp_fr_tw3_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ter_temp_fr_tw4_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_temp_fr_tw4_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_temp_fr_tw4_is_in_range(int16_t value);

/**
 * Pack message Temp_FL.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ter_temp_fl_pack(
    uint8_t *dst_p,
    const struct ter_temp_fl_t *src_p,
    size_t size);

/**
 * Unpack message Temp_FL.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ter_temp_fl_unpack(
    struct ter_temp_fl_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Temp_FL.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ter_temp_fl_init(struct ter_temp_fl_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ter_temp_fl_tw1_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_temp_fl_tw1_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_temp_fl_tw1_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ter_temp_fl_tw2_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_temp_fl_tw2_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_temp_fl_tw2_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ter_temp_fl_tw3_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_temp_fl_tw3_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_temp_fl_tw3_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ter_temp_fl_tw4_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_temp_fl_tw4_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_temp_fl_tw4_is_in_range(int16_t value);

/**
 * Pack message Buttons_BitMap.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ter_buttons_bit_map_pack(
    uint8_t *dst_p,
    const struct ter_buttons_bit_map_t *src_p,
    size_t size);

/**
 * Unpack message Buttons_BitMap.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ter_buttons_bit_map_unpack(
    struct ter_buttons_bit_map_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Buttons_BitMap.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ter_buttons_bit_map_init(struct ter_buttons_bit_map_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_buttons_bit_map_ld_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_buttons_bit_map_ld_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_buttons_bit_map_ld_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_buttons_bit_map_li_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_buttons_bit_map_li_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_buttons_bit_map_li_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_buttons_bit_map_r1_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_buttons_bit_map_r1_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_buttons_bit_map_r1_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_buttons_bit_map_r2_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_buttons_bit_map_r2_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_buttons_bit_map_r2_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_buttons_bit_map_r3_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_buttons_bit_map_r3_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_buttons_bit_map_r3_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_buttons_bit_map_r4_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_buttons_bit_map_r4_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_buttons_bit_map_r4_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_buttons_bit_map_r5_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_buttons_bit_map_r5_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_buttons_bit_map_r5_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_buttons_bit_map_r6_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_buttons_bit_map_r6_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_buttons_bit_map_r6_is_in_range(uint8_t value);

/**
 * Pack message APPS.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ter_apps_pack(
    uint8_t *dst_p,
    const struct ter_apps_t *src_p,
    size_t size);

/**
 * Unpack message APPS.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ter_apps_unpack(
    struct ter_apps_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from APPS.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ter_apps_init(struct ter_apps_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_apps_apps_1_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_apps_apps_1_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_apps_apps_1_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_apps_apps_2_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_apps_apps_2_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_apps_apps_2_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_apps_apps_av_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_apps_apps_av_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_apps_apps_av_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_apps_imp_flag_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_apps_imp_flag_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_apps_imp_flag_is_in_range(uint8_t value);

/**
 * Pack message COMMAND.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ter_command_pack(
    uint8_t *dst_p,
    const struct ter_command_t *src_p,
    size_t size);

/**
 * Unpack message COMMAND.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ter_command_unpack(
    struct ter_command_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from COMMAND.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ter_command_init(struct ter_command_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_command_cmd_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_command_cmd_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_command_cmd_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_command_kw_lim_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_command_kw_lim_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_command_kw_lim_is_in_range(uint8_t value);

/**
 * Pack message BPPS.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ter_bpps_pack(
    uint8_t *dst_p,
    const struct ter_bpps_t *src_p,
    size_t size);

/**
 * Unpack message BPPS.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ter_bpps_unpack(
    struct ter_bpps_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BPPS.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ter_bpps_init(struct ter_bpps_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_bpps_bpps_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_bpps_bpps_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_bpps_bpps_is_in_range(uint8_t value);

/**
 * Pack message STEER.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ter_steer_pack(
    uint8_t *dst_p,
    const struct ter_steer_t *src_p,
    size_t size);

/**
 * Unpack message STEER.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ter_steer_unpack(
    struct ter_steer_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from STEER.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ter_steer_init(struct ter_steer_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ter_steer_angle_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_steer_angle_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_steer_angle_is_in_range(int16_t value);

/**
 * Pack message Front_RPM.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ter_front_rpm_pack(
    uint8_t *dst_p,
    const struct ter_front_rpm_t *src_p,
    size_t size);

/**
 * Unpack message Front_RPM.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ter_front_rpm_unpack(
    struct ter_front_rpm_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Front_RPM.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ter_front_rpm_init(struct ter_front_rpm_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ter_front_rpm_rpm_l_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_front_rpm_rpm_l_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_front_rpm_rpm_l_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ter_front_rpm_rpm_r_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_front_rpm_rpm_r_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_front_rpm_rpm_r_is_in_range(uint16_t value);

/**
 * Pack message Front_V.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ter_front_v_pack(
    uint8_t *dst_p,
    const struct ter_front_v_t *src_p,
    size_t size);

/**
 * Unpack message Front_V.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ter_front_v_unpack(
    struct ter_front_v_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Front_V.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ter_front_v_init(struct ter_front_v_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ter_front_v_vx_l_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_front_v_vx_l_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_front_v_vx_l_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ter_front_v_vx_r_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_front_v_vx_r_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_front_v_vx_r_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ter_front_v_vx_av_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_front_v_vx_av_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_front_v_vx_av_is_in_range(uint16_t value);

/**
 * Pack message YPR.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ter_ypr_pack(
    uint8_t *dst_p,
    const struct ter_ypr_t *src_p,
    size_t size);

/**
 * Unpack message YPR.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ter_ypr_unpack(
    struct ter_ypr_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from YPR.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ter_ypr_init(struct ter_ypr_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t ter_ypr_pitch_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_ypr_pitch_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_ypr_pitch_is_in_range(int32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t ter_ypr_roll_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_ypr_roll_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_ypr_roll_is_in_range(int32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t ter_ypr_yaw_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_ypr_yaw_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_ypr_yaw_is_in_range(int32_t value);

/**
 * Pack message LV_Voltages.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ter_lv_voltages_pack(
    uint8_t *dst_p,
    const struct ter_lv_voltages_t *src_p,
    size_t size);

/**
 * Unpack message LV_Voltages.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ter_lv_voltages_unpack(
    struct ter_lv_voltages_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from LV_Voltages.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ter_lv_voltages_init(struct ter_lv_voltages_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ter_lv_voltages_v1_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_lv_voltages_v1_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_lv_voltages_v1_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ter_lv_voltages_v2_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_lv_voltages_v2_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_lv_voltages_v2_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ter_lv_voltages_v3_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_lv_voltages_v3_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_lv_voltages_v3_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ter_lv_voltages_v4_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_lv_voltages_v4_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_lv_voltages_v4_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ter_lv_voltages_v5_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_lv_voltages_v5_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_lv_voltages_v5_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ter_lv_voltages_v6_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_lv_voltages_v6_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_lv_voltages_v6_is_in_range(uint16_t value);

/**
 * Pack message LV_Temps.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ter_lv_temps_pack(
    uint8_t *dst_p,
    const struct ter_lv_temps_t *src_p,
    size_t size);

/**
 * Unpack message LV_Temps.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ter_lv_temps_unpack(
    struct ter_lv_temps_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from LV_Temps.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ter_lv_temps_init(struct ter_lv_temps_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_lv_temps_t1_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_lv_temps_t1_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_lv_temps_t1_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_lv_temps_t2_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_lv_temps_t2_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_lv_temps_t2_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_lv_temps_t3_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_lv_temps_t3_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_lv_temps_t3_is_in_range(uint8_t value);

/**
 * Pack message LV_Status.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ter_lv_status_pack(
    uint8_t *dst_p,
    const struct ter_lv_status_t *src_p,
    size_t size);

/**
 * Unpack message LV_Status.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ter_lv_status_unpack(
    struct ter_lv_status_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from LV_Status.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ter_lv_status_init(struct ter_lv_status_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_lv_status_lv_status_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_lv_status_lv_status_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_lv_status_lv_status_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_lv_status_lv_voltage_ok_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_lv_status_lv_voltage_ok_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_lv_status_lv_voltage_ok_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_lv_status_lv_temp_ok_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_lv_status_lv_temp_ok_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_lv_status_lv_temp_ok_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_lv_status_lv_current_ok_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_lv_status_lv_current_ok_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_lv_status_lv_current_ok_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_lv_status_refri_on_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_lv_status_refri_on_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_lv_status_refri_on_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_lv_status_lv_on_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_lv_status_lv_on_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_lv_status_lv_on_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ter_lv_status_lv_current_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_lv_status_lv_current_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_lv_status_lv_current_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ter_lv_status_v_max_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_lv_status_v_max_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_lv_status_v_max_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ter_lv_status_v_mean_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_lv_status_v_mean_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_lv_status_v_mean_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ter_lv_status_v_min_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_lv_status_v_min_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_lv_status_v_min_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ter_lv_status_v_tot_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_lv_status_v_tot_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_lv_status_v_tot_is_in_range(uint16_t value);

/**
 * Pack message AngRate.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ter_ang_rate_pack(
    uint8_t *dst_p,
    const struct ter_ang_rate_t *src_p,
    size_t size);

/**
 * Unpack message AngRate.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ter_ang_rate_unpack(
    struct ter_ang_rate_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from AngRate.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ter_ang_rate_init(struct ter_ang_rate_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t ter_ang_rate_roll_rate_x_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_ang_rate_roll_rate_x_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_ang_rate_roll_rate_x_is_in_range(int32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t ter_ang_rate_pitch_rate_y_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_ang_rate_pitch_rate_y_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_ang_rate_pitch_rate_y_is_in_range(int32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t ter_ang_rate_yaw_rate_z_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_ang_rate_yaw_rate_z_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_ang_rate_yaw_rate_z_is_in_range(int32_t value);

/**
 * Pack message GPS_Lat_Long.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ter_gps_lat_long_pack(
    uint8_t *dst_p,
    const struct ter_gps_lat_long_t *src_p,
    size_t size);

/**
 * Unpack message GPS_Lat_Long.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ter_gps_lat_long_unpack(
    struct ter_gps_lat_long_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from GPS_Lat_Long.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ter_gps_lat_long_init(struct ter_gps_lat_long_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t ter_gps_lat_long_latitude_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_gps_lat_long_latitude_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_gps_lat_long_latitude_is_in_range(int32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t ter_gps_lat_long_longitude_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_gps_lat_long_longitude_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_gps_lat_long_longitude_is_in_range(int32_t value);

/**
 * Pack message GPS_Altitude_Pres.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ter_gps_altitude_pres_pack(
    uint8_t *dst_p,
    const struct ter_gps_altitude_pres_t *src_p,
    size_t size);

/**
 * Unpack message GPS_Altitude_Pres.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ter_gps_altitude_pres_unpack(
    struct ter_gps_altitude_pres_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from GPS_Altitude_Pres.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ter_gps_altitude_pres_init(struct ter_gps_altitude_pres_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t ter_gps_altitude_pres_altidude_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_gps_altitude_pres_altidude_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_gps_altitude_pres_altidude_is_in_range(int32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ter_gps_altitude_pres_barometric_pressure_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_gps_altitude_pres_barometric_pressure_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_gps_altitude_pres_barometric_pressure_is_in_range(int16_t value);

/**
 * Pack message Accel.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ter_accel_pack(
    uint8_t *dst_p,
    const struct ter_accel_t *src_p,
    size_t size);

/**
 * Unpack message Accel.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ter_accel_unpack(
    struct ter_accel_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Accel.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ter_accel_init(struct ter_accel_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ter_accel_a_x_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_accel_a_x_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_accel_a_x_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ter_accel_a_y_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_accel_a_y_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_accel_a_y_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ter_accel_a_z_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_accel_a_z_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_accel_a_z_is_in_range(int16_t value);

/**
 * Pack message Mag.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ter_mag_pack(
    uint8_t *dst_p,
    const struct ter_mag_t *src_p,
    size_t size);

/**
 * Unpack message Mag.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ter_mag_unpack(
    struct ter_mag_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Mag.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ter_mag_init(struct ter_mag_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ter_mag_heading_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_mag_heading_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_mag_heading_is_in_range(int16_t value);

/**
 * Pack message VelBody.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ter_vel_body_pack(
    uint8_t *dst_p,
    const struct ter_vel_body_t *src_p,
    size_t size);

/**
 * Unpack message VelBody.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ter_vel_body_unpack(
    struct ter_vel_body_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from VelBody.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ter_vel_body_init(struct ter_vel_body_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ter_vel_body_v_x_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_vel_body_v_x_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_vel_body_v_x_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ter_vel_body_v_y_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_vel_body_v_y_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_vel_body_v_y_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ter_vel_body_v_z_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_vel_body_v_z_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_vel_body_v_z_is_in_range(int16_t value);

/**
 * Pack message ImuStatus.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ter_imu_status_pack(
    uint8_t *dst_p,
    const struct ter_imu_status_t *src_p,
    size_t size);

/**
 * Unpack message ImuStatus.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ter_imu_status_unpack(
    struct ter_imu_status_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ImuStatus.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ter_imu_status_init(struct ter_imu_status_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ter_imu_status_status_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_imu_status_status_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_imu_status_status_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ter_imu_status_pos_u_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_imu_status_pos_u_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_imu_status_pos_u_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ter_imu_status_vel_u_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_imu_status_vel_u_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_imu_status_vel_u_is_in_range(int16_t value);

/**
 * Pack message ECU_Status.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ter_ecu_status_pack(
    uint8_t *dst_p,
    const struct ter_ecu_status_t *src_p,
    size_t size);

/**
 * Unpack message ECU_Status.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ter_ecu_status_unpack(
    struct ter_ecu_status_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ECU_Status.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ter_ecu_status_init(struct ter_ecu_status_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_ecu_status_sl_status_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_ecu_status_sl_status_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_ecu_status_sl_status_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_ecu_status_state_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_ecu_status_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_ecu_status_state_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_ecu_status_r2d_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_ecu_status_r2d_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_ecu_status_r2d_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_ecu_status_bspd_status_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_ecu_status_bspd_status_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_ecu_status_bspd_status_is_in_range(uint8_t value);

/**
 * Pack message RESPONSE.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ter_response_pack(
    uint8_t *dst_p,
    const struct ter_response_t *src_p,
    size_t size);

/**
 * Unpack message RESPONSE.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ter_response_unpack(
    struct ter_response_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from RESPONSE.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ter_response_init(struct ter_response_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_response_cmd_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_response_cmd_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_response_cmd_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_response_code_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_response_code_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_response_code_is_in_range(uint8_t value);

/**
 * Pack message CHRG_Status.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ter_chrg_status_pack(
    uint8_t *dst_p,
    const struct ter_chrg_status_t *src_p,
    size_t size);

/**
 * Unpack message CHRG_Status.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ter_chrg_status_unpack(
    struct ter_chrg_status_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from CHRG_Status.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ter_chrg_status_init(struct ter_chrg_status_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_chrg_status_state_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_chrg_status_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_chrg_status_state_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ter_chrg_status_voltage_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_chrg_status_voltage_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_chrg_status_voltage_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_chrg_status_current_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_chrg_status_current_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_chrg_status_current_is_in_range(uint8_t value);


#ifdef __cplusplus
}
#endif

#endif
