/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.2.0 Tue Oct 24 19:15:17 2023.
 */

#ifndef TER_H
#define TER_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define TER_APPS_FRAME_ID (0x01u)
#define TER_PEDAL_CMD_FRAME_ID (0x04u)
#define TER_BPPS_FRAME_ID (0x02u)
#define TER_STEER_FRAME_ID (0x05u)
#define TER_R_WHEEL_FRAME_ID (0x115u)
#define TER_L_WHEEL_FRAME_ID (0x116u)

/* Frame lengths in bytes. */
#define TER_APPS_LENGTH (8u)
#define TER_PEDAL_CMD_LENGTH (8u)
#define TER_BPPS_LENGTH (1u)
#define TER_STEER_LENGTH (8u)
#define TER_R_WHEEL_LENGTH (8u)
#define TER_L_WHEEL_LENGTH (8u)

/* Extended or standard frame types. */
#define TER_APPS_IS_EXTENDED (0)
#define TER_PEDAL_CMD_IS_EXTENDED (0)
#define TER_BPPS_IS_EXTENDED (0)
#define TER_STEER_IS_EXTENDED (0)
#define TER_R_WHEEL_IS_EXTENDED (0)
#define TER_L_WHEEL_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */


/* Frame Names. */
#define TER_APPS_NAME "APPS"
#define TER_PEDAL_CMD_NAME "PEDAL_CMD"
#define TER_BPPS_NAME "BPPS"
#define TER_STEER_NAME "STEER"
#define TER_R_WHEEL_NAME "rWheel"
#define TER_L_WHEEL_NAME "lWheel"

/* Signal Names. */
#define TER_APPS_APPS_1_NAME "APPS_1"
#define TER_APPS_APPS_2_NAME "APPS_2"
#define TER_APPS_IMP_FLAG_NAME "IMP_FLAG"
#define TER_PEDAL_CMD_CMD_NAME "CMD"
#define TER_PEDAL_CMD_ARGS_NAME "ARGS"
#define TER_BPPS_BPPS_NAME "BPPS"
#define TER_STEER_ANGLE_NAME "ANGLE"
#define TER_R_WHEEL_RPM_NAME "RPM"
#define TER_L_WHEEL_RPM_NAME "RPM"

/**
 * Signals in message APPS.
 *
 * All signal values are as on the CAN bus.
 */
struct ter_apps_t {
    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t apps_1;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t apps_2;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t imp_flag;
};

/**
 * Signals in message PEDAL_CMD.
 *
 * All signal values are as on the CAN bus.
 */
struct ter_pedal_cmd_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t cmd;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint64_t args;
};

/**
 * Signals in message BPPS.
 *
 * All signal values are as on the CAN bus.
 */
struct ter_bpps_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t bpps;
};

/**
 * Signals in message STEER.
 *
 * All signal values are as on the CAN bus.
 */
struct ter_steer_t {
    /**
     * Range: -360..360 (-360..360 Grad)
     * Scale: 1
     * Offset: 0
     */
    int16_t angle;
};

/**
 * Signals in message rWheel.
 *
 * All signal values are as on the CAN bus.
 */
struct ter_r_wheel_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint16_t rpm;
};

/**
 * Signals in message lWheel.
 *
 * All signal values are as on the CAN bus.
 */
struct ter_l_wheel_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint16_t rpm;
};

/**
 * Pack message APPS.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ter_apps_pack(
    uint8_t *dst_p,
    const struct ter_apps_t *src_p,
    size_t size);

/**
 * Unpack message APPS.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ter_apps_unpack(
    struct ter_apps_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from APPS.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ter_apps_init(struct ter_apps_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_apps_apps_1_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_apps_apps_1_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_apps_apps_1_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_apps_apps_2_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_apps_apps_2_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_apps_apps_2_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_apps_imp_flag_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_apps_imp_flag_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_apps_imp_flag_is_in_range(uint8_t value);

/**
 * Pack message PEDAL_CMD.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ter_pedal_cmd_pack(
    uint8_t *dst_p,
    const struct ter_pedal_cmd_t *src_p,
    size_t size);

/**
 * Unpack message PEDAL_CMD.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ter_pedal_cmd_unpack(
    struct ter_pedal_cmd_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from PEDAL_CMD.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ter_pedal_cmd_init(struct ter_pedal_cmd_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_pedal_cmd_cmd_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_pedal_cmd_cmd_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_pedal_cmd_cmd_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint64_t ter_pedal_cmd_args_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_pedal_cmd_args_decode(uint64_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_pedal_cmd_args_is_in_range(uint64_t value);

/**
 * Pack message BPPS.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ter_bpps_pack(
    uint8_t *dst_p,
    const struct ter_bpps_t *src_p,
    size_t size);

/**
 * Unpack message BPPS.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ter_bpps_unpack(
    struct ter_bpps_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BPPS.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ter_bpps_init(struct ter_bpps_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ter_bpps_bpps_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_bpps_bpps_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_bpps_bpps_is_in_range(uint8_t value);

/**
 * Pack message STEER.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ter_steer_pack(
    uint8_t *dst_p,
    const struct ter_steer_t *src_p,
    size_t size);

/**
 * Unpack message STEER.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ter_steer_unpack(
    struct ter_steer_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from STEER.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ter_steer_init(struct ter_steer_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ter_steer_angle_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_steer_angle_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_steer_angle_is_in_range(int16_t value);

/**
 * Pack message rWheel.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ter_r_wheel_pack(
    uint8_t *dst_p,
    const struct ter_r_wheel_t *src_p,
    size_t size);

/**
 * Unpack message rWheel.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ter_r_wheel_unpack(
    struct ter_r_wheel_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from rWheel.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ter_r_wheel_init(struct ter_r_wheel_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ter_r_wheel_rpm_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_r_wheel_rpm_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_r_wheel_rpm_is_in_range(uint16_t value);

/**
 * Pack message lWheel.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ter_l_wheel_pack(
    uint8_t *dst_p,
    const struct ter_l_wheel_t *src_p,
    size_t size);

/**
 * Unpack message lWheel.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ter_l_wheel_unpack(
    struct ter_l_wheel_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from lWheel.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ter_l_wheel_init(struct ter_l_wheel_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ter_l_wheel_rpm_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ter_l_wheel_rpm_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ter_l_wheel_rpm_is_in_range(uint16_t value);


#ifdef __cplusplus
}
#endif

#endif
