/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.11 Wed Oct 30 16:42:23 2024.
 */

#include <string.h>

#include "ter.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int ter_rr_temp_pack(
    uint8_t *dst_p,
    const struct ter_rr_temp_t *src_p,
    size_t size)
{
    uint16_t tw1;
    uint16_t tw2;
    uint16_t tw3;
    uint16_t tw4;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    tw1 = (uint16_t)src_p->tw1;
    dst_p[0] |= pack_right_shift_u16(tw1, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(tw1, 0u, 0xffu);
    tw2 = (uint16_t)src_p->tw2;
    dst_p[2] |= pack_right_shift_u16(tw2, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(tw2, 0u, 0xffu);
    tw3 = (uint16_t)src_p->tw3;
    dst_p[4] |= pack_right_shift_u16(tw3, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(tw3, 0u, 0xffu);
    tw4 = (uint16_t)src_p->tw4;
    dst_p[6] |= pack_right_shift_u16(tw4, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(tw4, 0u, 0xffu);

    return (8);
}

int ter_rr_temp_unpack(
    struct ter_rr_temp_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t tw1;
    uint16_t tw2;
    uint16_t tw3;
    uint16_t tw4;

    if (size < 8u) {
        return (-EINVAL);
    }

    tw1 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    tw1 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->tw1 = (int16_t)tw1;
    tw2 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    tw2 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->tw2 = (int16_t)tw2;
    tw3 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    tw3 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->tw3 = (int16_t)tw3;
    tw4 = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    tw4 |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
    dst_p->tw4 = (int16_t)tw4;

    return (0);
}

int ter_rr_temp_init(struct ter_rr_temp_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_rr_temp_t));

    return 0;
}

int16_t ter_rr_temp_tw1_encode(float value)
{
    return (int16_t)(value / 0.1f);
}

float ter_rr_temp_tw1_decode(int16_t value)
{
    return ((float)value * 0.1f);
}

bool ter_rr_temp_tw1_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ter_rr_temp_tw2_encode(float value)
{
    return (int16_t)(value / 0.1f);
}

float ter_rr_temp_tw2_decode(int16_t value)
{
    return ((float)value * 0.1f);
}

bool ter_rr_temp_tw2_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ter_rr_temp_tw3_encode(float value)
{
    return (int16_t)(value / 0.1f);
}

float ter_rr_temp_tw3_decode(int16_t value)
{
    return ((float)value * 0.1f);
}

bool ter_rr_temp_tw3_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ter_rr_temp_tw4_encode(float value)
{
    return (int16_t)(value / 0.1f);
}

float ter_rr_temp_tw4_decode(int16_t value)
{
    return ((float)value * 0.1f);
}

bool ter_rr_temp_tw4_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int ter_rl_temp_pack(
    uint8_t *dst_p,
    const struct ter_rl_temp_t *src_p,
    size_t size)
{
    uint16_t tw1;
    uint16_t tw2;
    uint16_t tw3;
    uint16_t tw4;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    tw1 = (uint16_t)src_p->tw1;
    dst_p[0] |= pack_right_shift_u16(tw1, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(tw1, 0u, 0xffu);
    tw2 = (uint16_t)src_p->tw2;
    dst_p[2] |= pack_right_shift_u16(tw2, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(tw2, 0u, 0xffu);
    tw3 = (uint16_t)src_p->tw3;
    dst_p[4] |= pack_right_shift_u16(tw3, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(tw3, 0u, 0xffu);
    tw4 = (uint16_t)src_p->tw4;
    dst_p[6] |= pack_right_shift_u16(tw4, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(tw4, 0u, 0xffu);

    return (8);
}

int ter_rl_temp_unpack(
    struct ter_rl_temp_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t tw1;
    uint16_t tw2;
    uint16_t tw3;
    uint16_t tw4;

    if (size < 8u) {
        return (-EINVAL);
    }

    tw1 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    tw1 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->tw1 = (int16_t)tw1;
    tw2 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    tw2 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->tw2 = (int16_t)tw2;
    tw3 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    tw3 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->tw3 = (int16_t)tw3;
    tw4 = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    tw4 |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
    dst_p->tw4 = (int16_t)tw4;

    return (0);
}

int ter_rl_temp_init(struct ter_rl_temp_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_rl_temp_t));

    return 0;
}

int16_t ter_rl_temp_tw1_encode(float value)
{
    return (int16_t)(value / 0.1f);
}

float ter_rl_temp_tw1_decode(int16_t value)
{
    return ((float)value * 0.1f);
}

bool ter_rl_temp_tw1_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ter_rl_temp_tw2_encode(float value)
{
    return (int16_t)(value / 0.1f);
}

float ter_rl_temp_tw2_decode(int16_t value)
{
    return ((float)value * 0.1f);
}

bool ter_rl_temp_tw2_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ter_rl_temp_tw3_encode(float value)
{
    return (int16_t)(value / 0.1f);
}

float ter_rl_temp_tw3_decode(int16_t value)
{
    return ((float)value * 0.1f);
}

bool ter_rl_temp_tw3_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ter_rl_temp_tw4_encode(float value)
{
    return (int16_t)(value / 0.1f);
}

float ter_rl_temp_tw4_decode(int16_t value)
{
    return ((float)value * 0.1f);
}

bool ter_rl_temp_tw4_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int ter_fr_temp_pack(
    uint8_t *dst_p,
    const struct ter_fr_temp_t *src_p,
    size_t size)
{
    uint16_t tw1;
    uint16_t tw2;
    uint16_t tw3;
    uint16_t tw4;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    tw1 = (uint16_t)src_p->tw1;
    dst_p[0] |= pack_right_shift_u16(tw1, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(tw1, 0u, 0xffu);
    tw2 = (uint16_t)src_p->tw2;
    dst_p[2] |= pack_right_shift_u16(tw2, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(tw2, 0u, 0xffu);
    tw3 = (uint16_t)src_p->tw3;
    dst_p[4] |= pack_right_shift_u16(tw3, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(tw3, 0u, 0xffu);
    tw4 = (uint16_t)src_p->tw4;
    dst_p[6] |= pack_right_shift_u16(tw4, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(tw4, 0u, 0xffu);

    return (8);
}

int ter_fr_temp_unpack(
    struct ter_fr_temp_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t tw1;
    uint16_t tw2;
    uint16_t tw3;
    uint16_t tw4;

    if (size < 8u) {
        return (-EINVAL);
    }

    tw1 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    tw1 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->tw1 = (int16_t)tw1;
    tw2 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    tw2 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->tw2 = (int16_t)tw2;
    tw3 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    tw3 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->tw3 = (int16_t)tw3;
    tw4 = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    tw4 |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
    dst_p->tw4 = (int16_t)tw4;

    return (0);
}

int ter_fr_temp_init(struct ter_fr_temp_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_fr_temp_t));

    return 0;
}

int16_t ter_fr_temp_tw1_encode(float value)
{
    return (int16_t)(value / 0.1f);
}

float ter_fr_temp_tw1_decode(int16_t value)
{
    return ((float)value * 0.1f);
}

bool ter_fr_temp_tw1_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ter_fr_temp_tw2_encode(float value)
{
    return (int16_t)(value / 0.1f);
}

float ter_fr_temp_tw2_decode(int16_t value)
{
    return ((float)value * 0.1f);
}

bool ter_fr_temp_tw2_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ter_fr_temp_tw3_encode(float value)
{
    return (int16_t)(value / 0.1f);
}

float ter_fr_temp_tw3_decode(int16_t value)
{
    return ((float)value * 0.1f);
}

bool ter_fr_temp_tw3_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ter_fr_temp_tw4_encode(float value)
{
    return (int16_t)(value / 0.1f);
}

float ter_fr_temp_tw4_decode(int16_t value)
{
    return ((float)value * 0.1f);
}

bool ter_fr_temp_tw4_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int ter_fl_temp_pack(
    uint8_t *dst_p,
    const struct ter_fl_temp_t *src_p,
    size_t size)
{
    uint16_t tw1;
    uint16_t tw2;
    uint16_t tw3;
    uint16_t tw4;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    tw1 = (uint16_t)src_p->tw1;
    dst_p[0] |= pack_right_shift_u16(tw1, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(tw1, 0u, 0xffu);
    tw2 = (uint16_t)src_p->tw2;
    dst_p[2] |= pack_right_shift_u16(tw2, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(tw2, 0u, 0xffu);
    tw3 = (uint16_t)src_p->tw3;
    dst_p[4] |= pack_right_shift_u16(tw3, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(tw3, 0u, 0xffu);
    tw4 = (uint16_t)src_p->tw4;
    dst_p[6] |= pack_right_shift_u16(tw4, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(tw4, 0u, 0xffu);

    return (8);
}

int ter_fl_temp_unpack(
    struct ter_fl_temp_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t tw1;
    uint16_t tw2;
    uint16_t tw3;
    uint16_t tw4;

    if (size < 8u) {
        return (-EINVAL);
    }

    tw1 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    tw1 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->tw1 = (int16_t)tw1;
    tw2 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    tw2 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->tw2 = (int16_t)tw2;
    tw3 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    tw3 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->tw3 = (int16_t)tw3;
    tw4 = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    tw4 |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
    dst_p->tw4 = (int16_t)tw4;

    return (0);
}

int ter_fl_temp_init(struct ter_fl_temp_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_fl_temp_t));

    return 0;
}

int16_t ter_fl_temp_tw1_encode(float value)
{
    return (int16_t)(value / 0.1f);
}

float ter_fl_temp_tw1_decode(int16_t value)
{
    return ((float)value * 0.1f);
}

bool ter_fl_temp_tw1_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ter_fl_temp_tw2_encode(float value)
{
    return (int16_t)(value / 0.1f);
}

float ter_fl_temp_tw2_decode(int16_t value)
{
    return ((float)value * 0.1f);
}

bool ter_fl_temp_tw2_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ter_fl_temp_tw3_encode(float value)
{
    return (int16_t)(value / 0.1f);
}

float ter_fl_temp_tw3_decode(int16_t value)
{
    return ((float)value * 0.1f);
}

bool ter_fl_temp_tw3_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ter_fl_temp_tw4_encode(float value)
{
    return (int16_t)(value / 0.1f);
}

float ter_fl_temp_tw4_decode(int16_t value)
{
    return ((float)value * 0.1f);
}

bool ter_fl_temp_tw4_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int ter_btn_pack(
    uint8_t *dst_p,
    const struct ter_btn_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->ld, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->li, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->b1, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->b2, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->b3, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->b4, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->er, 6u, 0x40u);
    dst_p[0] |= pack_left_shift_u8(src_p->el, 7u, 0x80u);
    dst_p[1] |= pack_left_shift_u8(src_p->eb, 0u, 0x01u);

    return (8);
}

int ter_btn_unpack(
    struct ter_btn_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->ld = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->li = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->b1 = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->b2 = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->b3 = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->b4 = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->er = unpack_right_shift_u8(src_p[0], 6u, 0x40u);
    dst_p->el = unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    dst_p->eb = unpack_right_shift_u8(src_p[1], 0u, 0x01u);

    return (0);
}

int ter_btn_init(struct ter_btn_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_btn_t));

    return 0;
}

uint8_t ter_btn_ld_encode(float value)
{
    return (uint8_t)(value);
}

float ter_btn_ld_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_btn_ld_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_btn_li_encode(float value)
{
    return (uint8_t)(value);
}

float ter_btn_li_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_btn_li_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_btn_b1_encode(float value)
{
    return (uint8_t)(value);
}

float ter_btn_b1_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_btn_b1_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_btn_b2_encode(float value)
{
    return (uint8_t)(value);
}

float ter_btn_b2_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_btn_b2_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_btn_b3_encode(float value)
{
    return (uint8_t)(value);
}

float ter_btn_b3_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_btn_b3_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_btn_b4_encode(float value)
{
    return (uint8_t)(value);
}

float ter_btn_b4_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_btn_b4_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_btn_er_encode(float value)
{
    return (uint8_t)(value);
}

float ter_btn_er_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_btn_er_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_btn_el_encode(float value)
{
    return (uint8_t)(value);
}

float ter_btn_el_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_btn_el_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_btn_eb_encode(float value)
{
    return (uint8_t)(value);
}

float ter_btn_eb_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_btn_eb_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int ter_apps_pack(
    uint8_t *dst_p,
    const struct ter_apps_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->apps_1, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->apps_2, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->apps_av, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->imp_flag, 0u, 0xffu);

    return (8);
}

int ter_apps_unpack(
    struct ter_apps_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->apps_1 = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->apps_2 = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->apps_av = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->imp_flag = unpack_right_shift_u8(src_p[3], 0u, 0xffu);

    return (0);
}

int ter_apps_init(struct ter_apps_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_apps_t));

    return 0;
}

uint8_t ter_apps_apps_1_encode(float value)
{
    return (uint8_t)(value);
}

float ter_apps_apps_1_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_apps_apps_1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ter_apps_apps_2_encode(float value)
{
    return (uint8_t)(value);
}

float ter_apps_apps_2_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_apps_apps_2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ter_apps_apps_av_encode(float value)
{
    return (uint8_t)(value);
}

float ter_apps_apps_av_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_apps_apps_av_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ter_apps_imp_flag_encode(float value)
{
    return (uint8_t)(value);
}

float ter_apps_imp_flag_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_apps_imp_flag_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int ter_command_pack(
    uint8_t *dst_p,
    const struct ter_command_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->cmd, 0u, 0xffu);

    switch (src_p->cmd) {

    case 0:
        break;

    case 1:
        break;

    case 2:
        break;

    case 5:
        break;

    case 6:
        break;

    case 8:
        break;

    case 9:
        break;

    case 10:
        break;

    case 11:
        break;

    case 12:
        break;

    case 13:
        break;

    case 14:
        break;

    case 64:
        dst_p[1] |= pack_left_shift_u8(src_p->onoff, 0u, 0xffu);
        break;

    case 65:
        break;

    case 128:
        dst_p[1] |= pack_left_shift_u32(src_p->value, 0u, 0xffu);
        dst_p[2] |= pack_right_shift_u32(src_p->value, 8u, 0xffu);
        dst_p[3] |= pack_right_shift_u32(src_p->value, 16u, 0xffu);
        dst_p[4] |= pack_right_shift_u32(src_p->value, 24u, 0xffu);
        break;

    case 193:
        dst_p[1] |= pack_left_shift_u8(src_p->kw_limit, 0u, 0xffu);
        dst_p[2] |= pack_left_shift_u8(src_p->trq_limit, 0u, 0xffu);
        dst_p[3] |= pack_left_shift_u8(src_p->speed_limit, 0u, 0xffu);
        break;

    case 194:
        dst_p[1] |= pack_left_shift_u8(src_p->cfg_limiter, 0u, 0xffu);
        dst_p[2] |= pack_left_shift_u8(src_p->cfg_mode, 0u, 0xffu);
        dst_p[3] |= pack_left_shift_u8(src_p->cfg_traction_control, 0u, 0xffu);
        break;

    case 195:
        break;

    default:
        break;
    }

    return (8);
}

int ter_command_unpack(
    struct ter_command_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->cmd = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    switch (dst_p->cmd) {

    case 0:
        break;

    case 1:
        break;

    case 2:
        break;

    case 5:
        break;

    case 6:
        break;

    case 8:
        break;

    case 9:
        break;

    case 10:
        break;

    case 11:
        break;

    case 12:
        break;

    case 13:
        break;

    case 14:
        break;

    case 64:
        dst_p->onoff = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
        break;

    case 65:
        break;

    case 128:
        dst_p->value = unpack_right_shift_u32(src_p[1], 0u, 0xffu);
        dst_p->value |= unpack_left_shift_u32(src_p[2], 8u, 0xffu);
        dst_p->value |= unpack_left_shift_u32(src_p[3], 16u, 0xffu);
        dst_p->value |= unpack_left_shift_u32(src_p[4], 24u, 0xffu);
        break;

    case 193:
        dst_p->kw_limit = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
        dst_p->trq_limit = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
        dst_p->speed_limit = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
        break;

    case 194:
        dst_p->cfg_limiter = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
        dst_p->cfg_mode = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
        dst_p->cfg_traction_control = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
        break;

    case 195:
        break;

    default:
        break;
    }

    return (0);
}

int ter_command_init(struct ter_command_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_command_t));

    return 0;
}

uint8_t ter_command_cmd_encode(float value)
{
    return (uint8_t)(value);
}

float ter_command_cmd_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_command_cmd_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_command_kw_limit_encode(float value)
{
    return (uint8_t)(value);
}

float ter_command_kw_limit_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_command_kw_limit_is_in_range(uint8_t value)
{
    return ((value >= 1u) && (value <= 120u));
}

uint8_t ter_command_cfg_limiter_encode(float value)
{
    return (uint8_t)(value);
}

float ter_command_cfg_limiter_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_command_cfg_limiter_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_command_onoff_encode(float value)
{
    return (uint8_t)(value);
}

float ter_command_onoff_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_command_onoff_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint32_t ter_command_value_encode(float value)
{
    return (uint32_t)(value);
}

float ter_command_value_decode(uint32_t value)
{
    return ((float)value);
}

bool ter_command_value_is_in_range(uint32_t value)
{
    return (value <= 1u);
}

uint8_t ter_command_trq_limit_encode(float value)
{
    return (uint8_t)(value);
}

float ter_command_trq_limit_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_command_trq_limit_is_in_range(uint8_t value)
{
    return ((value >= 1u) && (value <= 180u));
}

uint8_t ter_command_cfg_mode_encode(float value)
{
    return (uint8_t)(value);
}

float ter_command_cfg_mode_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_command_cfg_mode_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_command_speed_limit_encode(float value)
{
    return (uint8_t)(value);
}

float ter_command_speed_limit_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_command_speed_limit_is_in_range(uint8_t value)
{
    return ((value >= 1u) && (value <= 120u));
}

uint8_t ter_command_cfg_traction_control_encode(float value)
{
    return (uint8_t)(value);
}

float ter_command_cfg_traction_control_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_command_cfg_traction_control_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int ter_bpps_pack(
    uint8_t *dst_p,
    const struct ter_bpps_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->bpps, 0u, 0xffu);

    return (1);
}

int ter_bpps_unpack(
    struct ter_bpps_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->bpps = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int ter_bpps_init(struct ter_bpps_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_bpps_t));

    return 0;
}

uint8_t ter_bpps_bpps_encode(float value)
{
    return (uint8_t)(value);
}

float ter_bpps_bpps_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_bpps_bpps_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int ter_steer_pack(
    uint8_t *dst_p,
    const struct ter_steer_t *src_p,
    size_t size)
{
    uint16_t angle;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    angle = (uint16_t)src_p->angle;
    dst_p[0] |= pack_left_shift_u16(angle, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(angle, 8u, 0xffu);

    return (8);
}

int ter_steer_unpack(
    struct ter_steer_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t angle;

    if (size < 8u) {
        return (-EINVAL);
    }

    angle = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    angle |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->angle = (int16_t)angle;

    return (0);
}

int ter_steer_init(struct ter_steer_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_steer_t));

    return 0;
}

int16_t ter_steer_angle_encode(float value)
{
    return (int16_t)(value);
}

float ter_steer_angle_decode(int16_t value)
{
    return ((float)value);
}

bool ter_steer_angle_is_in_range(int16_t value)
{
    return ((value >= -360) && (value <= 360));
}

int ter_front_rpm_pack(
    uint8_t *dst_p,
    const struct ter_front_rpm_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->rpm_l, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->rpm_l, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->rpm_r, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->rpm_r, 8u, 0xffu);

    return (8);
}

int ter_front_rpm_unpack(
    struct ter_front_rpm_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rpm_l = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->rpm_l |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->rpm_r = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->rpm_r |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);

    return (0);
}

int ter_front_rpm_init(struct ter_front_rpm_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_front_rpm_t));

    return 0;
}

uint16_t ter_front_rpm_rpm_l_encode(float value)
{
    return (uint16_t)(value);
}

float ter_front_rpm_rpm_l_decode(uint16_t value)
{
    return ((float)value);
}

bool ter_front_rpm_rpm_l_is_in_range(uint16_t value)
{
    return (value <= 1u);
}

uint16_t ter_front_rpm_rpm_r_encode(float value)
{
    return (uint16_t)(value);
}

float ter_front_rpm_rpm_r_decode(uint16_t value)
{
    return ((float)value);
}

bool ter_front_rpm_rpm_r_is_in_range(uint16_t value)
{
    return (value <= 1u);
}

int ter_front_v_pack(
    uint8_t *dst_p,
    const struct ter_front_v_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->vx_l, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->vx_l, 8u, 0x0fu);
    dst_p[1] |= pack_left_shift_u16(src_p->vx_r, 4u, 0xf0u);
    dst_p[2] |= pack_right_shift_u16(src_p->vx_r, 4u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->vx_av, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->vx_av, 8u, 0x0fu);

    return (8);
}

int ter_front_v_unpack(
    struct ter_front_v_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->vx_l = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->vx_l |= unpack_left_shift_u16(src_p[1], 8u, 0x0fu);
    dst_p->vx_r = unpack_right_shift_u16(src_p[1], 4u, 0xf0u);
    dst_p->vx_r |= unpack_left_shift_u16(src_p[2], 4u, 0xffu);
    dst_p->vx_av = unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->vx_av |= unpack_left_shift_u16(src_p[4], 8u, 0x0fu);

    return (0);
}

int ter_front_v_init(struct ter_front_v_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_front_v_t));

    return 0;
}

uint16_t ter_front_v_vx_l_encode(float value)
{
    return (uint16_t)(value / 0.01f);
}

float ter_front_v_vx_l_decode(uint16_t value)
{
    return ((float)value * 0.01f);
}

bool ter_front_v_vx_l_is_in_range(uint16_t value)
{
    return (value <= 100u);
}

uint16_t ter_front_v_vx_r_encode(float value)
{
    return (uint16_t)(value / 0.01f);
}

float ter_front_v_vx_r_decode(uint16_t value)
{
    return ((float)value * 0.01f);
}

bool ter_front_v_vx_r_is_in_range(uint16_t value)
{
    return (value <= 100u);
}

uint16_t ter_front_v_vx_av_encode(float value)
{
    return (uint16_t)(value / 0.01f);
}

float ter_front_v_vx_av_decode(uint16_t value)
{
    return ((float)value * 0.01f);
}

bool ter_front_v_vx_av_is_in_range(uint16_t value)
{
    return (value <= 100u);
}

int ter_ypr_pack(
    uint8_t *dst_p,
    const struct ter_ypr_t *src_p,
    size_t size)
{
    uint32_t pitch;
    uint32_t roll;
    uint32_t yaw;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    pitch = (uint32_t)src_p->pitch;
    dst_p[0] |= pack_left_shift_u32(pitch, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(pitch, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(pitch, 16u, 0x0fu);
    roll = (uint32_t)src_p->roll;
    dst_p[2] |= pack_left_shift_u32(roll, 4u, 0xf0u);
    dst_p[3] |= pack_right_shift_u32(roll, 4u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(roll, 12u, 0xffu);
    yaw = (uint32_t)src_p->yaw;
    dst_p[5] |= pack_left_shift_u32(yaw, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(yaw, 8u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(yaw, 16u, 0x0fu);

    return (8);
}

int ter_ypr_unpack(
    struct ter_ypr_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t pitch;
    uint32_t roll;
    uint32_t yaw;

    if (size < 8u) {
        return (-EINVAL);
    }

    pitch = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    pitch |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    pitch |= unpack_left_shift_u32(src_p[2], 16u, 0x0fu);

    if ((pitch & (1u << 19)) != 0u) {
        pitch |= 0xfff00000u;
    }

    dst_p->pitch = (int32_t)pitch;
    roll = unpack_right_shift_u32(src_p[2], 4u, 0xf0u);
    roll |= unpack_left_shift_u32(src_p[3], 4u, 0xffu);
    roll |= unpack_left_shift_u32(src_p[4], 12u, 0xffu);

    if ((roll & (1u << 19)) != 0u) {
        roll |= 0xfff00000u;
    }

    dst_p->roll = (int32_t)roll;
    yaw = unpack_right_shift_u32(src_p[5], 0u, 0xffu);
    yaw |= unpack_left_shift_u32(src_p[6], 8u, 0xffu);
    yaw |= unpack_left_shift_u32(src_p[7], 16u, 0x0fu);

    if ((yaw & (1u << 19)) != 0u) {
        yaw |= 0xfff00000u;
    }

    dst_p->yaw = (int32_t)yaw;

    return (0);
}

int ter_ypr_init(struct ter_ypr_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_ypr_t));

    return 0;
}

int32_t ter_ypr_pitch_encode(float value)
{
    return (int32_t)(value / 0.01f);
}

float ter_ypr_pitch_decode(int32_t value)
{
    return ((float)value * 0.01f);
}

bool ter_ypr_pitch_is_in_range(int32_t value)
{
    return ((value >= 0) && (value <= 100));
}

int32_t ter_ypr_roll_encode(float value)
{
    return (int32_t)(value / 0.01f);
}

float ter_ypr_roll_decode(int32_t value)
{
    return ((float)value * 0.01f);
}

bool ter_ypr_roll_is_in_range(int32_t value)
{
    return ((value >= 0) && (value <= 100));
}

int32_t ter_ypr_yaw_encode(float value)
{
    return (int32_t)(value / 0.01f);
}

float ter_ypr_yaw_decode(int32_t value)
{
    return ((float)value * 0.01f);
}

bool ter_ypr_yaw_is_in_range(int32_t value)
{
    return ((value >= 0) && (value <= 100));
}

int ter_lv_voltages_pack(
    uint8_t *dst_p,
    const struct ter_lv_voltages_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->v1, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->v1, 8u, 0x03u);
    dst_p[1] |= pack_left_shift_u16(src_p->v2, 2u, 0xfcu);
    dst_p[2] |= pack_right_shift_u16(src_p->v2, 6u, 0x0fu);
    dst_p[2] |= pack_left_shift_u16(src_p->v3, 4u, 0xf0u);
    dst_p[3] |= pack_right_shift_u16(src_p->v3, 4u, 0x3fu);
    dst_p[3] |= pack_left_shift_u16(src_p->v4, 6u, 0xc0u);
    dst_p[4] |= pack_right_shift_u16(src_p->v4, 2u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->v5, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->v5, 8u, 0x03u);
    dst_p[6] |= pack_left_shift_u16(src_p->v6, 2u, 0xfcu);
    dst_p[7] |= pack_right_shift_u16(src_p->v6, 6u, 0x0fu);

    return (8);
}

int ter_lv_voltages_unpack(
    struct ter_lv_voltages_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->v1 = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->v1 |= unpack_left_shift_u16(src_p[1], 8u, 0x03u);
    dst_p->v2 = unpack_right_shift_u16(src_p[1], 2u, 0xfcu);
    dst_p->v2 |= unpack_left_shift_u16(src_p[2], 6u, 0x0fu);
    dst_p->v3 = unpack_right_shift_u16(src_p[2], 4u, 0xf0u);
    dst_p->v3 |= unpack_left_shift_u16(src_p[3], 4u, 0x3fu);
    dst_p->v4 = unpack_right_shift_u16(src_p[3], 6u, 0xc0u);
    dst_p->v4 |= unpack_left_shift_u16(src_p[4], 2u, 0xffu);
    dst_p->v5 = unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->v5 |= unpack_left_shift_u16(src_p[6], 8u, 0x03u);
    dst_p->v6 = unpack_right_shift_u16(src_p[6], 2u, 0xfcu);
    dst_p->v6 |= unpack_left_shift_u16(src_p[7], 6u, 0x0fu);

    return (0);
}

int ter_lv_voltages_init(struct ter_lv_voltages_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_lv_voltages_t));

    return 0;
}

uint16_t ter_lv_voltages_v1_encode(float value)
{
    return (uint16_t)(value / 0.01f);
}

float ter_lv_voltages_v1_decode(uint16_t value)
{
    return ((float)value * 0.01f);
}

bool ter_lv_voltages_v1_is_in_range(uint16_t value)
{
    return (value <= 100u);
}

uint16_t ter_lv_voltages_v2_encode(float value)
{
    return (uint16_t)(value / 0.01f);
}

float ter_lv_voltages_v2_decode(uint16_t value)
{
    return ((float)value * 0.01f);
}

bool ter_lv_voltages_v2_is_in_range(uint16_t value)
{
    return (value <= 100u);
}

uint16_t ter_lv_voltages_v3_encode(float value)
{
    return (uint16_t)(value / 0.01f);
}

float ter_lv_voltages_v3_decode(uint16_t value)
{
    return ((float)value * 0.01f);
}

bool ter_lv_voltages_v3_is_in_range(uint16_t value)
{
    return (value <= 100u);
}

uint16_t ter_lv_voltages_v4_encode(float value)
{
    return (uint16_t)(value / 0.01f);
}

float ter_lv_voltages_v4_decode(uint16_t value)
{
    return ((float)value * 0.01f);
}

bool ter_lv_voltages_v4_is_in_range(uint16_t value)
{
    return (value <= 100u);
}

uint16_t ter_lv_voltages_v5_encode(float value)
{
    return (uint16_t)(value / 0.01f);
}

float ter_lv_voltages_v5_decode(uint16_t value)
{
    return ((float)value * 0.01f);
}

bool ter_lv_voltages_v5_is_in_range(uint16_t value)
{
    return (value <= 100u);
}

uint16_t ter_lv_voltages_v6_encode(float value)
{
    return (uint16_t)(value / 0.01f);
}

float ter_lv_voltages_v6_decode(uint16_t value)
{
    return ((float)value * 0.01f);
}

bool ter_lv_voltages_v6_is_in_range(uint16_t value)
{
    return (value <= 100u);
}

int ter_lv_temps_pack(
    uint8_t *dst_p,
    const struct ter_lv_temps_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u16(src_p->t1, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->t1, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->t2, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->t2, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->t3, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->t3, 8u, 0xffu);

    return (6);
}

int ter_lv_temps_unpack(
    struct ter_lv_temps_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->t1 = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->t1 |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->t2 = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->t2 |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->t3 = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->t3 |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);

    return (0);
}

int ter_lv_temps_init(struct ter_lv_temps_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_lv_temps_t));

    return 0;
}

uint16_t ter_lv_temps_t1_encode(float value)
{
    return (uint16_t)(value / 0.1f);
}

float ter_lv_temps_t1_decode(uint16_t value)
{
    return ((float)value * 0.1f);
}

bool ter_lv_temps_t1_is_in_range(uint16_t value)
{
    return (value <= 10u);
}

uint16_t ter_lv_temps_t2_encode(float value)
{
    return (uint16_t)(value / 0.1f);
}

float ter_lv_temps_t2_decode(uint16_t value)
{
    return ((float)value * 0.1f);
}

bool ter_lv_temps_t2_is_in_range(uint16_t value)
{
    return (value <= 10u);
}

uint16_t ter_lv_temps_t3_encode(float value)
{
    return (uint16_t)(value / 0.1f);
}

float ter_lv_temps_t3_decode(uint16_t value)
{
    return ((float)value * 0.1f);
}

bool ter_lv_temps_t3_is_in_range(uint16_t value)
{
    return (value <= 10u);
}

int ter_lv_status_pack(
    uint8_t *dst_p,
    const struct ter_lv_status_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->status, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->voltages_ok, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->temps_ok, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->current_ok, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->refri_on, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->lv_on, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u16(src_p->current, 6u, 0xc0u);
    dst_p[1] |= pack_right_shift_u16(src_p->current, 2u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->current, 10u, 0x3fu);
    dst_p[2] |= pack_left_shift_u16(src_p->v_max, 6u, 0xc0u);
    dst_p[3] |= pack_right_shift_u16(src_p->v_max, 2u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->v_mean, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->v_mean, 8u, 0x03u);
    dst_p[5] |= pack_left_shift_u16(src_p->v_min, 2u, 0xfcu);
    dst_p[6] |= pack_right_shift_u16(src_p->v_min, 6u, 0x0fu);
    dst_p[6] |= pack_left_shift_u16(src_p->v_tot, 4u, 0xf0u);
    dst_p[7] |= pack_right_shift_u16(src_p->v_tot, 4u, 0xffu);

    return (8);
}

int ter_lv_status_unpack(
    struct ter_lv_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->status = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->voltages_ok = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->temps_ok = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->current_ok = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->refri_on = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->lv_on = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->current = unpack_right_shift_u16(src_p[0], 6u, 0xc0u);
    dst_p->current |= unpack_left_shift_u16(src_p[1], 2u, 0xffu);
    dst_p->current |= unpack_left_shift_u16(src_p[2], 10u, 0x3fu);
    dst_p->v_max = unpack_right_shift_u16(src_p[2], 6u, 0xc0u);
    dst_p->v_max |= unpack_left_shift_u16(src_p[3], 2u, 0xffu);
    dst_p->v_mean = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->v_mean |= unpack_left_shift_u16(src_p[5], 8u, 0x03u);
    dst_p->v_min = unpack_right_shift_u16(src_p[5], 2u, 0xfcu);
    dst_p->v_min |= unpack_left_shift_u16(src_p[6], 6u, 0x0fu);
    dst_p->v_tot = unpack_right_shift_u16(src_p[6], 4u, 0xf0u);
    dst_p->v_tot |= unpack_left_shift_u16(src_p[7], 4u, 0xffu);

    return (0);
}

int ter_lv_status_init(struct ter_lv_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_lv_status_t));

    return 0;
}

uint8_t ter_lv_status_status_encode(float value)
{
    return (uint8_t)(value);
}

float ter_lv_status_status_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_lv_status_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_lv_status_voltages_ok_encode(float value)
{
    return (uint8_t)(value);
}

float ter_lv_status_voltages_ok_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_lv_status_voltages_ok_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_lv_status_temps_ok_encode(float value)
{
    return (uint8_t)(value);
}

float ter_lv_status_temps_ok_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_lv_status_temps_ok_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_lv_status_current_ok_encode(float value)
{
    return (uint8_t)(value);
}

float ter_lv_status_current_ok_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_lv_status_current_ok_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_lv_status_refri_on_encode(float value)
{
    return (uint8_t)(value);
}

float ter_lv_status_refri_on_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_lv_status_refri_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_lv_status_lv_on_encode(float value)
{
    return (uint8_t)(value);
}

float ter_lv_status_lv_on_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_lv_status_lv_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t ter_lv_status_current_encode(float value)
{
    return (uint16_t)(value / 0.1f);
}

float ter_lv_status_current_decode(uint16_t value)
{
    return ((float)value * 0.1f);
}

bool ter_lv_status_current_is_in_range(uint16_t value)
{
    return (value <= 10u);
}

uint16_t ter_lv_status_v_max_encode(float value)
{
    return (uint16_t)(value / 0.01f);
}

float ter_lv_status_v_max_decode(uint16_t value)
{
    return ((float)value * 0.01f);
}

bool ter_lv_status_v_max_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint16_t ter_lv_status_v_mean_encode(float value)
{
    return (uint16_t)(value / 0.01f);
}

float ter_lv_status_v_mean_decode(uint16_t value)
{
    return ((float)value * 0.01f);
}

bool ter_lv_status_v_mean_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint16_t ter_lv_status_v_min_encode(float value)
{
    return (uint16_t)(value / 0.01f);
}

float ter_lv_status_v_min_decode(uint16_t value)
{
    return ((float)value * 0.01f);
}

bool ter_lv_status_v_min_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint16_t ter_lv_status_v_tot_encode(float value)
{
    return (uint16_t)(value / 0.01f);
}

float ter_lv_status_v_tot_decode(uint16_t value)
{
    return ((float)value * 0.01f);
}

bool ter_lv_status_v_tot_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

int ter_ang_rate_pack(
    uint8_t *dst_p,
    const struct ter_ang_rate_t *src_p,
    size_t size)
{
    uint32_t pitch_rate_y;
    uint32_t roll_rate_x;
    uint32_t yaw_rate_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    roll_rate_x = (uint32_t)src_p->roll_rate_x;
    dst_p[0] |= pack_left_shift_u32(roll_rate_x, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(roll_rate_x, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(roll_rate_x, 16u, 0x0fu);
    pitch_rate_y = (uint32_t)src_p->pitch_rate_y;
    dst_p[2] |= pack_left_shift_u32(pitch_rate_y, 4u, 0xf0u);
    dst_p[3] |= pack_right_shift_u32(pitch_rate_y, 4u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(pitch_rate_y, 12u, 0xffu);
    yaw_rate_z = (uint32_t)src_p->yaw_rate_z;
    dst_p[5] |= pack_left_shift_u32(yaw_rate_z, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(yaw_rate_z, 8u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(yaw_rate_z, 16u, 0x0fu);

    return (8);
}

int ter_ang_rate_unpack(
    struct ter_ang_rate_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t pitch_rate_y;
    uint32_t roll_rate_x;
    uint32_t yaw_rate_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    roll_rate_x = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    roll_rate_x |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    roll_rate_x |= unpack_left_shift_u32(src_p[2], 16u, 0x0fu);

    if ((roll_rate_x & (1u << 19)) != 0u) {
        roll_rate_x |= 0xfff00000u;
    }

    dst_p->roll_rate_x = (int32_t)roll_rate_x;
    pitch_rate_y = unpack_right_shift_u32(src_p[2], 4u, 0xf0u);
    pitch_rate_y |= unpack_left_shift_u32(src_p[3], 4u, 0xffu);
    pitch_rate_y |= unpack_left_shift_u32(src_p[4], 12u, 0xffu);

    if ((pitch_rate_y & (1u << 19)) != 0u) {
        pitch_rate_y |= 0xfff00000u;
    }

    dst_p->pitch_rate_y = (int32_t)pitch_rate_y;
    yaw_rate_z = unpack_right_shift_u32(src_p[5], 0u, 0xffu);
    yaw_rate_z |= unpack_left_shift_u32(src_p[6], 8u, 0xffu);
    yaw_rate_z |= unpack_left_shift_u32(src_p[7], 16u, 0x0fu);

    if ((yaw_rate_z & (1u << 19)) != 0u) {
        yaw_rate_z |= 0xfff00000u;
    }

    dst_p->yaw_rate_z = (int32_t)yaw_rate_z;

    return (0);
}

int ter_ang_rate_init(struct ter_ang_rate_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_ang_rate_t));

    return 0;
}

int32_t ter_ang_rate_roll_rate_x_encode(float value)
{
    return (int32_t)(value / 0.001f);
}

float ter_ang_rate_roll_rate_x_decode(int32_t value)
{
    return ((float)value * 0.001f);
}

bool ter_ang_rate_roll_rate_x_is_in_range(int32_t value)
{
    return ((value >= 0) && (value <= 1000));
}

int32_t ter_ang_rate_pitch_rate_y_encode(float value)
{
    return (int32_t)(value / 0.001f);
}

float ter_ang_rate_pitch_rate_y_decode(int32_t value)
{
    return ((float)value * 0.001f);
}

bool ter_ang_rate_pitch_rate_y_is_in_range(int32_t value)
{
    return ((value >= 0) && (value <= 1000));
}

int32_t ter_ang_rate_yaw_rate_z_encode(float value)
{
    return (int32_t)(value / 0.001f);
}

float ter_ang_rate_yaw_rate_z_decode(int32_t value)
{
    return ((float)value * 0.001f);
}

bool ter_ang_rate_yaw_rate_z_is_in_range(int32_t value)
{
    return ((value >= 0) && (value <= 1000));
}

int ter_gps_lat_long_pack(
    uint8_t *dst_p,
    const struct ter_gps_lat_long_t *src_p,
    size_t size)
{
    uint32_t latitude;
    uint32_t longitude;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    latitude = (uint32_t)src_p->latitude;
    dst_p[0] |= pack_left_shift_u32(latitude, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(latitude, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(latitude, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(latitude, 24u, 0xffu);
    longitude = (uint32_t)src_p->longitude;
    dst_p[4] |= pack_left_shift_u32(longitude, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(longitude, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(longitude, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(longitude, 24u, 0xffu);

    return (8);
}

int ter_gps_lat_long_unpack(
    struct ter_gps_lat_long_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t latitude;
    uint32_t longitude;

    if (size < 8u) {
        return (-EINVAL);
    }

    latitude = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    latitude |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    latitude |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    latitude |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->latitude = (int32_t)latitude;
    longitude = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    longitude |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    longitude |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    longitude |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);
    dst_p->longitude = (int32_t)longitude;

    return (0);
}

int ter_gps_lat_long_init(struct ter_gps_lat_long_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_gps_lat_long_t));

    return 0;
}

int32_t ter_gps_lat_long_latitude_encode(float value)
{
    return (int32_t)(value / 1e-07f);
}

float ter_gps_lat_long_latitude_decode(int32_t value)
{
    return ((float)value * 1e-07f);
}

bool ter_gps_lat_long_latitude_is_in_range(int32_t value)
{
    return ((value >= 0) && (value <= 10000000));
}

int32_t ter_gps_lat_long_longitude_encode(float value)
{
    return (int32_t)(value / 1e-07f);
}

float ter_gps_lat_long_longitude_decode(int32_t value)
{
    return ((float)value * 1e-07f);
}

bool ter_gps_lat_long_longitude_is_in_range(int32_t value)
{
    return ((value >= 0) && (value <= 10000000));
}

int ter_gps_altitude_pres_pack(
    uint8_t *dst_p,
    const struct ter_gps_altitude_pres_t *src_p,
    size_t size)
{
    uint16_t barometric_pressure;
    uint32_t altidude;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    altidude = (uint32_t)src_p->altidude;
    dst_p[0] |= pack_left_shift_u32(altidude, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(altidude, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(altidude, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(altidude, 24u, 0xffu);
    barometric_pressure = (uint16_t)src_p->barometric_pressure;
    dst_p[4] |= pack_left_shift_u16(barometric_pressure, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(barometric_pressure, 8u, 0xffu);

    return (8);
}

int ter_gps_altitude_pres_unpack(
    struct ter_gps_altitude_pres_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t barometric_pressure;
    uint32_t altidude;

    if (size < 8u) {
        return (-EINVAL);
    }

    altidude = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    altidude |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    altidude |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    altidude |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->altidude = (int32_t)altidude;
    barometric_pressure = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    barometric_pressure |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->barometric_pressure = (int16_t)barometric_pressure;

    return (0);
}

int ter_gps_altitude_pres_init(struct ter_gps_altitude_pres_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_gps_altitude_pres_t));

    return 0;
}

int32_t ter_gps_altitude_pres_altidude_encode(float value)
{
    return (int32_t)(value / 1e-07f);
}

float ter_gps_altitude_pres_altidude_decode(int32_t value)
{
    return ((float)value * 1e-07f);
}

bool ter_gps_altitude_pres_altidude_is_in_range(int32_t value)
{
    return ((value >= 0) && (value <= 10000000));
}

int16_t ter_gps_altitude_pres_barometric_pressure_encode(float value)
{
    return (int16_t)(value / 1e-07f);
}

float ter_gps_altitude_pres_barometric_pressure_decode(int16_t value)
{
    return ((float)value * 1e-07f);
}

bool ter_gps_altitude_pres_barometric_pressure_is_in_range(int16_t value)
{
    return (value >= 0);
}

int ter_accel_pack(
    uint8_t *dst_p,
    const struct ter_accel_t *src_p,
    size_t size)
{
    uint16_t a_x;
    uint16_t a_y;
    uint16_t a_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    a_x = (uint16_t)src_p->a_x;
    dst_p[0] |= pack_left_shift_u16(a_x, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(a_x, 8u, 0xffu);
    a_y = (uint16_t)src_p->a_y;
    dst_p[2] |= pack_left_shift_u16(a_y, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(a_y, 8u, 0xffu);
    a_z = (uint16_t)src_p->a_z;
    dst_p[4] |= pack_left_shift_u16(a_z, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(a_z, 8u, 0xffu);

    return (8);
}

int ter_accel_unpack(
    struct ter_accel_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t a_x;
    uint16_t a_y;
    uint16_t a_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    a_x = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    a_x |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->a_x = (int16_t)a_x;
    a_y = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    a_y |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->a_y = (int16_t)a_y;
    a_z = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    a_z |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->a_z = (int16_t)a_z;

    return (0);
}

int ter_accel_init(struct ter_accel_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_accel_t));

    return 0;
}

int16_t ter_accel_a_x_encode(float value)
{
    return (int16_t)(value / 0.001f);
}

float ter_accel_a_x_decode(int16_t value)
{
    return ((float)value * 0.001f);
}

bool ter_accel_a_x_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 1000));
}

int16_t ter_accel_a_y_encode(float value)
{
    return (int16_t)(value / 0.001f);
}

float ter_accel_a_y_decode(int16_t value)
{
    return ((float)value * 0.001f);
}

bool ter_accel_a_y_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 1000));
}

int16_t ter_accel_a_z_encode(float value)
{
    return (int16_t)(value / 0.001f);
}

float ter_accel_a_z_decode(int16_t value)
{
    return ((float)value * 0.001f);
}

bool ter_accel_a_z_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 1000));
}

int ter_mag_pack(
    uint8_t *dst_p,
    const struct ter_mag_t *src_p,
    size_t size)
{
    uint16_t heading;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    heading = (uint16_t)src_p->heading;
    dst_p[0] |= pack_left_shift_u16(heading, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(heading, 8u, 0xffu);

    return (8);
}

int ter_mag_unpack(
    struct ter_mag_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t heading;

    if (size < 8u) {
        return (-EINVAL);
    }

    heading = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    heading |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->heading = (int16_t)heading;

    return (0);
}

int ter_mag_init(struct ter_mag_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_mag_t));

    return 0;
}

int16_t ter_mag_heading_encode(float value)
{
    return (int16_t)(value / 0.01f);
}

float ter_mag_heading_decode(int16_t value)
{
    return ((float)value * 0.01f);
}

bool ter_mag_heading_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 100));
}

int ter_vel_body_pack(
    uint8_t *dst_p,
    const struct ter_vel_body_t *src_p,
    size_t size)
{
    uint16_t v_x;
    uint16_t v_y;
    uint16_t v_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    v_x = (uint16_t)src_p->v_x;
    dst_p[0] |= pack_left_shift_u16(v_x, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(v_x, 8u, 0xffu);
    v_y = (uint16_t)src_p->v_y;
    dst_p[2] |= pack_left_shift_u16(v_y, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(v_y, 8u, 0xffu);
    v_z = (uint16_t)src_p->v_z;
    dst_p[4] |= pack_left_shift_u16(v_z, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(v_z, 8u, 0xffu);

    return (8);
}

int ter_vel_body_unpack(
    struct ter_vel_body_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t v_x;
    uint16_t v_y;
    uint16_t v_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    v_x = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    v_x |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->v_x = (int16_t)v_x;
    v_y = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    v_y |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->v_y = (int16_t)v_y;
    v_z = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    v_z |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->v_z = (int16_t)v_z;

    return (0);
}

int ter_vel_body_init(struct ter_vel_body_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_vel_body_t));

    return 0;
}

int16_t ter_vel_body_v_x_encode(float value)
{
    return (int16_t)(value / 0.001f);
}

float ter_vel_body_v_x_decode(int16_t value)
{
    return ((float)value * 0.001f);
}

bool ter_vel_body_v_x_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 1000));
}

int16_t ter_vel_body_v_y_encode(float value)
{
    return (int16_t)(value / 0.001f);
}

float ter_vel_body_v_y_decode(int16_t value)
{
    return ((float)value * 0.001f);
}

bool ter_vel_body_v_y_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 1000));
}

int16_t ter_vel_body_v_z_encode(float value)
{
    return (int16_t)(value / 0.001f);
}

float ter_vel_body_v_z_decode(int16_t value)
{
    return ((float)value * 0.001f);
}

bool ter_vel_body_v_z_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 1000));
}

int ter_imu_status_pack(
    uint8_t *dst_p,
    const struct ter_imu_status_t *src_p,
    size_t size)
{
    uint16_t pos_u;
    uint16_t status;
    uint16_t vel_u;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    status = (uint16_t)src_p->status;
    dst_p[0] |= pack_left_shift_u16(status, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(status, 8u, 0xffu);
    pos_u = (uint16_t)src_p->pos_u;
    dst_p[2] |= pack_left_shift_u16(pos_u, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(pos_u, 8u, 0xffu);
    vel_u = (uint16_t)src_p->vel_u;
    dst_p[4] |= pack_left_shift_u16(vel_u, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(vel_u, 8u, 0xffu);

    return (8);
}

int ter_imu_status_unpack(
    struct ter_imu_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t pos_u;
    uint16_t status;
    uint16_t vel_u;

    if (size < 8u) {
        return (-EINVAL);
    }

    status = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    status |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->status = (int16_t)status;
    pos_u = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    pos_u |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->pos_u = (int16_t)pos_u;
    vel_u = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    vel_u |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->vel_u = (int16_t)vel_u;

    return (0);
}

int ter_imu_status_init(struct ter_imu_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_imu_status_t));

    return 0;
}

int16_t ter_imu_status_status_encode(float value)
{
    return (int16_t)(value);
}

float ter_imu_status_status_decode(int16_t value)
{
    return ((float)value);
}

bool ter_imu_status_status_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 1));
}

int16_t ter_imu_status_pos_u_encode(float value)
{
    return (int16_t)(value / 0.001f);
}

float ter_imu_status_pos_u_decode(int16_t value)
{
    return ((float)value * 0.001f);
}

bool ter_imu_status_pos_u_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 1000));
}

int16_t ter_imu_status_vel_u_encode(float value)
{
    return (int16_t)(value / 0.001f);
}

float ter_imu_status_vel_u_decode(int16_t value)
{
    return ((float)value * 0.001f);
}

bool ter_imu_status_vel_u_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 1000));
}

int ter_ter_status_pack(
    uint8_t *dst_p,
    const struct ter_ter_status_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u8(src_p->state, 0u, 0x0fu);
    dst_p[0] |= pack_left_shift_u8(src_p->r2_d, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->scs, 5u, 0x20u);
    dst_p[1] |= pack_left_shift_u8(src_p->sl, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->bspd, 1u, 0x02u);
    dst_p[1] |= pack_left_shift_u8(src_p->imd, 2u, 0x04u);
    dst_p[1] |= pack_left_shift_u8(src_p->ams, 3u, 0x08u);
    dst_p[2] |= pack_left_shift_u8(src_p->apps, 0u, 0x01u);
    dst_p[2] |= pack_left_shift_u8(src_p->imu, 1u, 0x02u);
    dst_p[2] |= pack_left_shift_u8(src_p->refri, 2u, 0x04u);
    dst_p[3] |= pack_left_shift_u8(src_p->right_inv, 0u, 0x01u);
    dst_p[3] |= pack_left_shift_u8(src_p->left_inv, 1u, 0x02u);

    return (4);
}

int ter_ter_status_unpack(
    struct ter_ter_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->state = unpack_right_shift_u8(src_p[0], 0u, 0x0fu);
    dst_p->r2_d = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->scs = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->sl = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->bspd = unpack_right_shift_u8(src_p[1], 1u, 0x02u);
    dst_p->imd = unpack_right_shift_u8(src_p[1], 2u, 0x04u);
    dst_p->ams = unpack_right_shift_u8(src_p[1], 3u, 0x08u);
    dst_p->apps = unpack_right_shift_u8(src_p[2], 0u, 0x01u);
    dst_p->imu = unpack_right_shift_u8(src_p[2], 1u, 0x02u);
    dst_p->refri = unpack_right_shift_u8(src_p[2], 2u, 0x04u);
    dst_p->right_inv = unpack_right_shift_u8(src_p[3], 0u, 0x01u);
    dst_p->left_inv = unpack_right_shift_u8(src_p[3], 1u, 0x02u);

    return (0);
}

int ter_ter_status_init(struct ter_ter_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_ter_status_t));

    return 0;
}

uint8_t ter_ter_status_state_encode(float value)
{
    return (uint8_t)(value);
}

float ter_ter_status_state_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_ter_status_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_ter_status_r2_d_encode(float value)
{
    return (uint8_t)(value);
}

float ter_ter_status_r2_d_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_ter_status_r2_d_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_ter_status_scs_encode(float value)
{
    return (uint8_t)(value);
}

float ter_ter_status_scs_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_ter_status_scs_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_ter_status_sl_encode(float value)
{
    return (uint8_t)(value);
}

float ter_ter_status_sl_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_ter_status_sl_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_ter_status_bspd_encode(float value)
{
    return (uint8_t)(value);
}

float ter_ter_status_bspd_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_ter_status_bspd_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_ter_status_imd_encode(float value)
{
    return (uint8_t)(value);
}

float ter_ter_status_imd_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_ter_status_imd_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_ter_status_ams_encode(float value)
{
    return (uint8_t)(value);
}

float ter_ter_status_ams_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_ter_status_ams_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_ter_status_apps_encode(float value)
{
    return (uint8_t)(value);
}

float ter_ter_status_apps_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_ter_status_apps_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_ter_status_imu_encode(float value)
{
    return (uint8_t)(value);
}

float ter_ter_status_imu_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_ter_status_imu_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_ter_status_refri_encode(float value)
{
    return (uint8_t)(value);
}

float ter_ter_status_refri_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_ter_status_refri_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_ter_status_right_inv_encode(float value)
{
    return (uint8_t)(value);
}

float ter_ter_status_right_inv_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_ter_status_right_inv_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_ter_status_left_inv_encode(float value)
{
    return (uint8_t)(value);
}

float ter_ter_status_left_inv_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_ter_status_left_inv_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int ter_response_pack(
    uint8_t *dst_p,
    const struct ter_response_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->cmd, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->code, 0u, 0xffu);

    return (8);
}

int ter_response_unpack(
    struct ter_response_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->cmd = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->code = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int ter_response_init(struct ter_response_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_response_t));

    return 0;
}

uint8_t ter_response_cmd_encode(float value)
{
    return (uint8_t)(value);
}

float ter_response_cmd_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_response_cmd_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_response_code_encode(float value)
{
    return (uint8_t)(value);
}

float ter_response_code_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_response_code_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int ter_chrg_status_pack(
    uint8_t *dst_p,
    const struct ter_chrg_status_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->state, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->voltage, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->voltage, 8u, 0x03u);
    dst_p[2] |= pack_left_shift_u8(src_p->current, 2u, 0xfcu);
    dst_p[3] |= pack_left_shift_u8(src_p->ams, 0u, 0x01u);
    dst_p[3] |= pack_left_shift_u8(src_p->imd, 1u, 0x02u);
    dst_p[3] |= pack_left_shift_u8(src_p->sl, 2u, 0x04u);

    return (8);
}

int ter_chrg_status_unpack(
    struct ter_chrg_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->state = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->voltage = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->voltage |= unpack_left_shift_u16(src_p[2], 8u, 0x03u);
    dst_p->current = unpack_right_shift_u8(src_p[2], 2u, 0xfcu);
    dst_p->ams = unpack_right_shift_u8(src_p[3], 0u, 0x01u);
    dst_p->imd = unpack_right_shift_u8(src_p[3], 1u, 0x02u);
    dst_p->sl = unpack_right_shift_u8(src_p[3], 2u, 0x04u);

    return (0);
}

int ter_chrg_status_init(struct ter_chrg_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_chrg_status_t));

    return 0;
}

uint8_t ter_chrg_status_state_encode(float value)
{
    return (uint8_t)(value);
}

float ter_chrg_status_state_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_chrg_status_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t ter_chrg_status_voltage_encode(float value)
{
    return (uint16_t)(value);
}

float ter_chrg_status_voltage_decode(uint16_t value)
{
    return ((float)value);
}

bool ter_chrg_status_voltage_is_in_range(uint16_t value)
{
    return (value <= 1u);
}

uint8_t ter_chrg_status_current_encode(float value)
{
    return (uint8_t)(value);
}

float ter_chrg_status_current_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_chrg_status_current_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_chrg_status_ams_encode(float value)
{
    return (uint8_t)(value);
}

float ter_chrg_status_ams_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_chrg_status_ams_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_chrg_status_imd_encode(float value)
{
    return (uint8_t)(value);
}

float ter_chrg_status_imd_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_chrg_status_imd_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_chrg_status_sl_encode(float value)
{
    return (uint8_t)(value);
}

float ter_chrg_status_sl_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_chrg_status_sl_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int ter_dynamic_config_pack(
    uint8_t *dst_p,
    const struct ter_dynamic_config_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->limiter, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->mode, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->traction_control, 0u, 0xffu);

    switch (src_p->limiter) {

    case 0:
        dst_p[3] |= pack_left_shift_u8(src_p->trq_limit, 0u, 0xffu);
        break;

    case 1:
        dst_p[3] |= pack_left_shift_u8(src_p->speed_limit, 0u, 0xffu);
        break;

    case 2:
        dst_p[3] |= pack_left_shift_u8(src_p->kw_limit, 0u, 0xffu);
        break;

    case 3:
        break;

    default:
        break;
    }

    return (8);
}

int ter_dynamic_config_unpack(
    struct ter_dynamic_config_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->limiter = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->mode = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->traction_control = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    switch (dst_p->limiter) {

    case 0:
        dst_p->trq_limit = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
        break;

    case 1:
        dst_p->speed_limit = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
        break;

    case 2:
        dst_p->kw_limit = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
        break;

    case 3:
        break;

    default:
        break;
    }

    return (0);
}

int ter_dynamic_config_init(struct ter_dynamic_config_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_dynamic_config_t));

    return 0;
}

uint8_t ter_dynamic_config_limiter_encode(float value)
{
    return (uint8_t)(value);
}

float ter_dynamic_config_limiter_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_dynamic_config_limiter_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_dynamic_config_mode_encode(float value)
{
    return (uint8_t)(value);
}

float ter_dynamic_config_mode_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_dynamic_config_mode_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_dynamic_config_traction_control_encode(float value)
{
    return (uint8_t)(value);
}

float ter_dynamic_config_traction_control_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_dynamic_config_traction_control_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_dynamic_config_kw_limit_encode(float value)
{
    return (uint8_t)(value);
}

float ter_dynamic_config_kw_limit_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_dynamic_config_kw_limit_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_dynamic_config_trq_limit_encode(float value)
{
    return (uint8_t)(value);
}

float ter_dynamic_config_trq_limit_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_dynamic_config_trq_limit_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_dynamic_config_speed_limit_encode(float value)
{
    return (uint8_t)(value);
}

float ter_dynamic_config_speed_limit_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_dynamic_config_speed_limit_is_in_range(uint8_t value)
{
    return (value <= 120u);
}

int ter_wheel_info_pack(
    uint8_t *dst_p,
    const struct ter_wheel_info_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->rr_rpm, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->rr_rpm, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->rr_trq, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->rl_rpm, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->rl_rpm, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->rl_trq, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->speed, 0u, 0xffu);

    return (8);
}

int ter_wheel_info_unpack(
    struct ter_wheel_info_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rr_rpm = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->rr_rpm |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->rr_trq = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->rl_rpm = unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->rl_rpm |= unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->rl_trq = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->speed = unpack_right_shift_u8(src_p[6], 0u, 0xffu);

    return (0);
}

int ter_wheel_info_init(struct ter_wheel_info_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_wheel_info_t));

    return 0;
}

uint16_t ter_wheel_info_rr_rpm_encode(float value)
{
    return (uint16_t)(value);
}

float ter_wheel_info_rr_rpm_decode(uint16_t value)
{
    return ((float)value);
}

bool ter_wheel_info_rr_rpm_is_in_range(uint16_t value)
{
    return (value <= 1u);
}

uint8_t ter_wheel_info_rr_trq_encode(float value)
{
    return (uint8_t)(value);
}

float ter_wheel_info_rr_trq_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_wheel_info_rr_trq_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t ter_wheel_info_rl_rpm_encode(float value)
{
    return (uint16_t)(value);
}

float ter_wheel_info_rl_rpm_decode(uint16_t value)
{
    return ((float)value);
}

bool ter_wheel_info_rl_rpm_is_in_range(uint16_t value)
{
    return (value <= 1u);
}

uint8_t ter_wheel_info_rl_trq_encode(float value)
{
    return (uint8_t)(value);
}

float ter_wheel_info_rl_trq_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_wheel_info_rl_trq_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_wheel_info_speed_encode(float value)
{
    return (uint8_t)(value);
}

float ter_wheel_info_speed_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_wheel_info_speed_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int ter_inverter_info_pack(
    uint8_t *dst_p,
    const struct ter_inverter_info_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->left_dem, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->right_dem, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->left_power_stage_temp, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->right_power_stage_temp, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->left_motor_temp, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->right_motor_temp, 0u, 0xffu);

    return (8);
}

int ter_inverter_info_unpack(
    struct ter_inverter_info_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->left_dem = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->right_dem = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->left_power_stage_temp = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->right_power_stage_temp = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->left_motor_temp = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->right_motor_temp = unpack_right_shift_u8(src_p[5], 0u, 0xffu);

    return (0);
}

int ter_inverter_info_init(struct ter_inverter_info_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_inverter_info_t));

    return 0;
}

uint8_t ter_inverter_info_left_dem_encode(float value)
{
    return (uint8_t)(value);
}

float ter_inverter_info_left_dem_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_inverter_info_left_dem_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_inverter_info_right_dem_encode(float value)
{
    return (uint8_t)(value);
}

float ter_inverter_info_right_dem_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_inverter_info_right_dem_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_inverter_info_left_power_stage_temp_encode(float value)
{
    return (uint8_t)(value);
}

float ter_inverter_info_left_power_stage_temp_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_inverter_info_left_power_stage_temp_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_inverter_info_right_power_stage_temp_encode(float value)
{
    return (uint8_t)(value);
}

float ter_inverter_info_right_power_stage_temp_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_inverter_info_right_power_stage_temp_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_inverter_info_left_motor_temp_encode(float value)
{
    return (uint8_t)(value);
}

float ter_inverter_info_left_motor_temp_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_inverter_info_left_motor_temp_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_inverter_info_right_motor_temp_encode(float value)
{
    return (uint8_t)(value);
}

float ter_inverter_info_right_motor_temp_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_inverter_info_right_motor_temp_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int ter_front_temps_pack(
    uint8_t *dst_p,
    const struct ter_front_temps_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->temp_l, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->temp_l, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->temp_r, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->temp_r, 8u, 0xffu);

    return (8);
}

int ter_front_temps_unpack(
    struct ter_front_temps_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->temp_l = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->temp_l |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->temp_r = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->temp_r |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);

    return (0);
}

int ter_front_temps_init(struct ter_front_temps_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_front_temps_t));

    return 0;
}

uint16_t ter_front_temps_temp_l_encode(float value)
{
    return (uint16_t)(value / 0.1f);
}

float ter_front_temps_temp_l_decode(uint16_t value)
{
    return ((float)value * 0.1f);
}

bool ter_front_temps_temp_l_is_in_range(uint16_t value)
{
    return (value <= 10u);
}

uint16_t ter_front_temps_temp_r_encode(float value)
{
    return (uint16_t)(value / 0.1f);
}

float ter_front_temps_temp_r_decode(uint16_t value)
{
    return ((float)value * 0.1f);
}

bool ter_front_temps_temp_r_is_in_range(uint16_t value)
{
    return (value <= 10u);
}

int ter_front_susp_pack(
    uint8_t *dst_p,
    const struct ter_front_susp_t *src_p,
    size_t size)
{
    uint16_t fl_disp;
    uint16_t fr_disp;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    fr_disp = (uint16_t)src_p->fr_disp;
    dst_p[0] |= pack_left_shift_u16(fr_disp, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(fr_disp, 8u, 0xffu);
    fl_disp = (uint16_t)src_p->fl_disp;
    dst_p[2] |= pack_left_shift_u16(fl_disp, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(fl_disp, 8u, 0xffu);

    return (8);
}

int ter_front_susp_unpack(
    struct ter_front_susp_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t fl_disp;
    uint16_t fr_disp;

    if (size < 8u) {
        return (-EINVAL);
    }

    fr_disp = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    fr_disp |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->fr_disp = (int16_t)fr_disp;
    fl_disp = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    fl_disp |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->fl_disp = (int16_t)fl_disp;

    return (0);
}

int ter_front_susp_init(struct ter_front_susp_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_front_susp_t));

    return 0;
}

int16_t ter_front_susp_fr_disp_encode(float value)
{
    return (int16_t)(value / 0.1f);
}

float ter_front_susp_fr_disp_decode(int16_t value)
{
    return ((float)value * 0.1f);
}

bool ter_front_susp_fr_disp_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 10));
}

int16_t ter_front_susp_fl_disp_encode(float value)
{
    return (int16_t)(value / 0.1f);
}

float ter_front_susp_fl_disp_decode(int16_t value)
{
    return ((float)value * 0.1f);
}

bool ter_front_susp_fl_disp_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 10));
}
