/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.2.0 Fri Nov  3 00:12:47 2023.
 */

#include <string.h>

#include "ter.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint64_t unpack_left_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

static inline uint64_t unpack_right_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) >> shift);
}

int ter_apps_pack(
    uint8_t *dst_p,
    const struct ter_apps_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->apps_1, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->apps_2, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->imp_flag, 0u, 0xffu);

    return (8);
}

int ter_apps_unpack(
    struct ter_apps_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->apps_1 = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->apps_2 = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->imp_flag = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

int ter_apps_init(struct ter_apps_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_apps_t));

    return 0;
}

uint8_t ter_apps_apps_1_encode(double value)
{
    return (uint8_t)(value);
}

double ter_apps_apps_1_decode(uint8_t value)
{
    return ((double)value);
}

bool ter_apps_apps_1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ter_apps_apps_2_encode(double value)
{
    return (uint8_t)(value);
}

double ter_apps_apps_2_decode(uint8_t value)
{
    return ((double)value);
}

bool ter_apps_apps_2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ter_apps_imp_flag_encode(double value)
{
    return (uint8_t)(value);
}

double ter_apps_imp_flag_decode(uint8_t value)
{
    return ((double)value);
}

bool ter_apps_imp_flag_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int ter_pedal_cmd_pack(
    uint8_t *dst_p,
    const struct ter_pedal_cmd_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->cmd, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u64(src_p->args, 48u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(src_p->args, 40u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(src_p->args, 32u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->args, 24u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->args, 16u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(src_p->args, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u64(src_p->args, 0u, 0xffu);

    return (8);
}

int ter_pedal_cmd_unpack(
    struct ter_pedal_cmd_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->cmd = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->args = unpack_left_shift_u64(src_p[1], 48u, 0xffu);
    dst_p->args |= unpack_left_shift_u64(src_p[2], 40u, 0xffu);
    dst_p->args |= unpack_left_shift_u64(src_p[3], 32u, 0xffu);
    dst_p->args |= unpack_left_shift_u64(src_p[4], 24u, 0xffu);
    dst_p->args |= unpack_left_shift_u64(src_p[5], 16u, 0xffu);
    dst_p->args |= unpack_left_shift_u64(src_p[6], 8u, 0xffu);
    dst_p->args |= unpack_right_shift_u64(src_p[7], 0u, 0xffu);

    return (0);
}

int ter_pedal_cmd_init(struct ter_pedal_cmd_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_pedal_cmd_t));

    return 0;
}

uint8_t ter_pedal_cmd_cmd_encode(double value)
{
    return (uint8_t)(value);
}

double ter_pedal_cmd_cmd_decode(uint8_t value)
{
    return ((double)value);
}

bool ter_pedal_cmd_cmd_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint64_t ter_pedal_cmd_args_encode(double value)
{
    return (uint64_t)(value);
}

double ter_pedal_cmd_args_decode(uint64_t value)
{
    return ((double)value);
}

bool ter_pedal_cmd_args_is_in_range(uint64_t value)
{
    return (value <= 1ull);
}

int ter_bpps_pack(
    uint8_t *dst_p,
    const struct ter_bpps_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->bpps, 0u, 0xffu);

    return (1);
}

int ter_bpps_unpack(
    struct ter_bpps_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->bpps = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int ter_bpps_init(struct ter_bpps_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_bpps_t));

    return 0;
}

uint8_t ter_bpps_bpps_encode(double value)
{
    return (uint8_t)(value);
}

double ter_bpps_bpps_decode(uint8_t value)
{
    return ((double)value);
}

bool ter_bpps_bpps_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int ter_steer_pack(
    uint8_t *dst_p,
    const struct ter_steer_t *src_p,
    size_t size)
{
    uint16_t angle;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    angle = (uint16_t)src_p->angle;
    dst_p[0] |= pack_right_shift_u16(angle, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(angle, 0u, 0xffu);

    return (8);
}

int ter_steer_unpack(
    struct ter_steer_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t angle;

    if (size < 8u) {
        return (-EINVAL);
    }

    angle = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    angle |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->angle = (int16_t)angle;

    return (0);
}

int ter_steer_init(struct ter_steer_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_steer_t));

    return 0;
}

int16_t ter_steer_angle_encode(double value)
{
    return (int16_t)(value);
}

double ter_steer_angle_decode(int16_t value)
{
    return ((double)value);
}

bool ter_steer_angle_is_in_range(int16_t value)
{
    return ((value >= -360) && (value <= 360));
}

int ter_r_wheel_pack(
    uint8_t *dst_p,
    const struct ter_r_wheel_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->rpm, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->rpm, 0u, 0xffu);

    return (8);
}

int ter_r_wheel_unpack(
    struct ter_r_wheel_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rpm = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->rpm |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);

    return (0);
}

int ter_r_wheel_init(struct ter_r_wheel_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_r_wheel_t));

    return 0;
}

uint16_t ter_r_wheel_rpm_encode(double value)
{
    return (uint16_t)(value);
}

double ter_r_wheel_rpm_decode(uint16_t value)
{
    return ((double)value);
}

bool ter_r_wheel_rpm_is_in_range(uint16_t value)
{
    return (value <= 1u);
}

int ter_l_wheel_pack(
    uint8_t *dst_p,
    const struct ter_l_wheel_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->rpm, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->rpm, 0u, 0xffu);

    return (8);
}

int ter_l_wheel_unpack(
    struct ter_l_wheel_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rpm = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->rpm |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);

    return (0);
}

int ter_l_wheel_init(struct ter_l_wheel_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_l_wheel_t));

    return 0;
}

uint16_t ter_l_wheel_rpm_encode(double value)
{
    return (uint16_t)(value);
}

double ter_l_wheel_rpm_decode(uint16_t value)
{
    return ((double)value);
}

bool ter_l_wheel_rpm_is_in_range(uint16_t value)
{
    return (value <= 1u);
}

int ter_ypr_pack(
    uint8_t *dst_p,
    const struct ter_ypr_t *src_p,
    size_t size)
{
    uint32_t pitch;
    uint32_t roll;
    uint32_t yaw;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->mux, 0u, 0xffu);

    switch (src_p->mux) {

    case 0:
        yaw = (uint32_t)src_p->yaw;
        dst_p[1] |= pack_left_shift_u32(yaw, 7u, 0x80u);
        dst_p[2] |= pack_right_shift_u32(yaw, 1u, 0xffu);
        dst_p[3] |= pack_right_shift_u32(yaw, 9u, 0xffu);
        dst_p[4] |= pack_right_shift_u32(yaw, 17u, 0xffu);
        dst_p[5] |= pack_right_shift_u32(yaw, 25u, 0x7fu);
        break;

    case 1:
        pitch = (uint32_t)src_p->pitch;
        dst_p[1] |= pack_left_shift_u32(pitch, 7u, 0x80u);
        dst_p[2] |= pack_right_shift_u32(pitch, 1u, 0xffu);
        dst_p[3] |= pack_right_shift_u32(pitch, 9u, 0xffu);
        dst_p[4] |= pack_right_shift_u32(pitch, 17u, 0xffu);
        dst_p[5] |= pack_right_shift_u32(pitch, 25u, 0x7fu);
        break;

    case 2:
        roll = (uint32_t)src_p->roll;
        dst_p[1] |= pack_left_shift_u32(roll, 7u, 0x80u);
        dst_p[2] |= pack_right_shift_u32(roll, 1u, 0xffu);
        dst_p[3] |= pack_right_shift_u32(roll, 9u, 0xffu);
        dst_p[4] |= pack_right_shift_u32(roll, 17u, 0xffu);
        dst_p[5] |= pack_right_shift_u32(roll, 25u, 0x7fu);
        break;

    default:
        break;
    }

    return (8);
}

int ter_ypr_unpack(
    struct ter_ypr_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t pitch;
    uint32_t roll;
    uint32_t yaw;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->mux = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    switch (dst_p->mux) {

    case 0:
        yaw = unpack_right_shift_u32(src_p[1], 7u, 0x80u);
        yaw |= unpack_left_shift_u32(src_p[2], 1u, 0xffu);
        yaw |= unpack_left_shift_u32(src_p[3], 9u, 0xffu);
        yaw |= unpack_left_shift_u32(src_p[4], 17u, 0xffu);
        yaw |= unpack_left_shift_u32(src_p[5], 25u, 0x7fu);
        dst_p->yaw = (int32_t)yaw;
        break;

    case 1:
        pitch = unpack_right_shift_u32(src_p[1], 7u, 0x80u);
        pitch |= unpack_left_shift_u32(src_p[2], 1u, 0xffu);
        pitch |= unpack_left_shift_u32(src_p[3], 9u, 0xffu);
        pitch |= unpack_left_shift_u32(src_p[4], 17u, 0xffu);
        pitch |= unpack_left_shift_u32(src_p[5], 25u, 0x7fu);
        dst_p->pitch = (int32_t)pitch;
        break;

    case 2:
        roll = unpack_right_shift_u32(src_p[1], 7u, 0x80u);
        roll |= unpack_left_shift_u32(src_p[2], 1u, 0xffu);
        roll |= unpack_left_shift_u32(src_p[3], 9u, 0xffu);
        roll |= unpack_left_shift_u32(src_p[4], 17u, 0xffu);
        roll |= unpack_left_shift_u32(src_p[5], 25u, 0x7fu);
        dst_p->roll = (int32_t)roll;
        break;

    default:
        break;
    }

    return (0);
}

int ter_ypr_init(struct ter_ypr_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_ypr_t));

    return 0;
}

uint8_t ter_ypr_mux_encode(double value)
{
    return (uint8_t)(value);
}

double ter_ypr_mux_decode(uint8_t value)
{
    return ((double)value);
}

bool ter_ypr_mux_is_in_range(uint8_t value)
{
    return (value <= 2u);
}

int32_t ter_ypr_yaw_encode(double value)
{
    return (int32_t)(value);
}

double ter_ypr_yaw_decode(int32_t value)
{
    return ((double)value);
}

bool ter_ypr_yaw_is_in_range(int32_t value)
{
    return ((value >= 0) && (value <= 1));
}

int32_t ter_ypr_pitch_encode(double value)
{
    return (int32_t)(value);
}

double ter_ypr_pitch_decode(int32_t value)
{
    return ((double)value);
}

bool ter_ypr_pitch_is_in_range(int32_t value)
{
    return ((value >= 0) && (value <= 1));
}

int32_t ter_ypr_roll_encode(double value)
{
    return (int32_t)(value);
}

double ter_ypr_roll_decode(int32_t value)
{
    return ((double)value);
}

bool ter_ypr_roll_is_in_range(int32_t value)
{
    return ((value >= 0) && (value <= 1));
}
