/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.3 Tue Jan 30 11:55:28 2024.
 */

#include <string.h>

#include "ter.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint64_t unpack_left_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

static inline uint64_t unpack_right_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) >> shift);
}

int ter_apps_pack(
    uint8_t *dst_p,
    const struct ter_apps_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->apps_1, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->apps_2, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->imp_flag, 0u, 0xffu);

    return (8);
}

int ter_apps_unpack(
    struct ter_apps_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->apps_1 = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->apps_2 = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->imp_flag = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

int ter_apps_init(struct ter_apps_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_apps_t));

    return 0;
}

uint8_t ter_apps_apps_1_encode(float value)
{
    return (uint8_t)(value);
}

float ter_apps_apps_1_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_apps_apps_1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ter_apps_apps_2_encode(float value)
{
    return (uint8_t)(value);
}

float ter_apps_apps_2_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_apps_apps_2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ter_apps_imp_flag_encode(float value)
{
    return (uint8_t)(value);
}

float ter_apps_imp_flag_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_apps_imp_flag_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int ter_pedal_cmd_pack(
    uint8_t *dst_p,
    const struct ter_pedal_cmd_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->cmd, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u64(src_p->args, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(src_p->args, 8u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(src_p->args, 16u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->args, 24u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->args, 32u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(src_p->args, 40u, 0xffu);
    dst_p[7] |= pack_right_shift_u64(src_p->args, 48u, 0xffu);

    return (8);
}

int ter_pedal_cmd_unpack(
    struct ter_pedal_cmd_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->cmd = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->args = unpack_right_shift_u64(src_p[1], 0u, 0xffu);
    dst_p->args |= unpack_left_shift_u64(src_p[2], 8u, 0xffu);
    dst_p->args |= unpack_left_shift_u64(src_p[3], 16u, 0xffu);
    dst_p->args |= unpack_left_shift_u64(src_p[4], 24u, 0xffu);
    dst_p->args |= unpack_left_shift_u64(src_p[5], 32u, 0xffu);
    dst_p->args |= unpack_left_shift_u64(src_p[6], 40u, 0xffu);
    dst_p->args |= unpack_left_shift_u64(src_p[7], 48u, 0xffu);

    return (0);
}

int ter_pedal_cmd_init(struct ter_pedal_cmd_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_pedal_cmd_t));

    return 0;
}

uint8_t ter_pedal_cmd_cmd_encode(float value)
{
    return (uint8_t)(value);
}

float ter_pedal_cmd_cmd_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_pedal_cmd_cmd_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint64_t ter_pedal_cmd_args_encode(float value)
{
    return (uint64_t)(value);
}

float ter_pedal_cmd_args_decode(uint64_t value)
{
    return ((float)value);
}

bool ter_pedal_cmd_args_is_in_range(uint64_t value)
{
    return (value <= 1ull);
}

int ter_bpps_pack(
    uint8_t *dst_p,
    const struct ter_bpps_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->bpps, 0u, 0xffu);

    return (1);
}

int ter_bpps_unpack(
    struct ter_bpps_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->bpps = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int ter_bpps_init(struct ter_bpps_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_bpps_t));

    return 0;
}

uint8_t ter_bpps_bpps_encode(float value)
{
    return (uint8_t)(value);
}

float ter_bpps_bpps_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_bpps_bpps_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int ter_steer_pack(
    uint8_t *dst_p,
    const struct ter_steer_t *src_p,
    size_t size)
{
    uint16_t angle;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    angle = (uint16_t)src_p->angle;
    dst_p[0] |= pack_left_shift_u16(angle, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(angle, 8u, 0xffu);

    return (8);
}

int ter_steer_unpack(
    struct ter_steer_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t angle;

    if (size < 8u) {
        return (-EINVAL);
    }

    angle = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    angle |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->angle = (int16_t)angle;

    return (0);
}

int ter_steer_init(struct ter_steer_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_steer_t));

    return 0;
}

int16_t ter_steer_angle_encode(float value)
{
    return (int16_t)(value);
}

float ter_steer_angle_decode(int16_t value)
{
    return ((float)value);
}

bool ter_steer_angle_is_in_range(int16_t value)
{
    return ((value >= -360) && (value <= 360));
}

int ter_r_wheel_pack(
    uint8_t *dst_p,
    const struct ter_r_wheel_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->rpm, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->rpm, 8u, 0xffu);

    return (8);
}

int ter_r_wheel_unpack(
    struct ter_r_wheel_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rpm = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->rpm |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

int ter_r_wheel_init(struct ter_r_wheel_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_r_wheel_t));

    return 0;
}

uint16_t ter_r_wheel_rpm_encode(float value)
{
    return (uint16_t)(value);
}

float ter_r_wheel_rpm_decode(uint16_t value)
{
    return ((float)value);
}

bool ter_r_wheel_rpm_is_in_range(uint16_t value)
{
    return (value <= 1u);
}

int ter_l_wheel_pack(
    uint8_t *dst_p,
    const struct ter_l_wheel_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->rpm, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->rpm, 8u, 0xffu);

    return (8);
}

int ter_l_wheel_unpack(
    struct ter_l_wheel_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rpm = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->rpm |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

int ter_l_wheel_init(struct ter_l_wheel_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_l_wheel_t));

    return 0;
}

uint16_t ter_l_wheel_rpm_encode(float value)
{
    return (uint16_t)(value);
}

float ter_l_wheel_rpm_decode(uint16_t value)
{
    return ((float)value);
}

bool ter_l_wheel_rpm_is_in_range(uint16_t value)
{
    return (value <= 1u);
}

int ter_ypr_pack(
    uint8_t *dst_p,
    const struct ter_ypr_t *src_p,
    size_t size)
{
    uint32_t pitch;
    uint32_t roll;
    uint32_t yaw;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    pitch = (uint32_t)src_p->pitch;
    dst_p[0] |= pack_left_shift_u32(pitch, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(pitch, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(pitch, 16u, 0x0fu);
    roll = (uint32_t)src_p->roll;
    dst_p[2] |= pack_left_shift_u32(roll, 4u, 0xf0u);
    dst_p[3] |= pack_right_shift_u32(roll, 4u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(roll, 12u, 0xffu);
    yaw = (uint32_t)src_p->yaw;
    dst_p[5] |= pack_left_shift_u32(yaw, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(yaw, 8u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(yaw, 16u, 0x0fu);

    return (8);
}

int ter_ypr_unpack(
    struct ter_ypr_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t pitch;
    uint32_t roll;
    uint32_t yaw;

    if (size < 8u) {
        return (-EINVAL);
    }

    pitch = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    pitch |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    pitch |= unpack_left_shift_u32(src_p[2], 16u, 0x0fu);

    if ((pitch & (1u << 19)) != 0u) {
        pitch |= 0xfff00000u;
    }

    dst_p->pitch = (int32_t)pitch;
    roll = unpack_right_shift_u32(src_p[2], 4u, 0xf0u);
    roll |= unpack_left_shift_u32(src_p[3], 4u, 0xffu);
    roll |= unpack_left_shift_u32(src_p[4], 12u, 0xffu);

    if ((roll & (1u << 19)) != 0u) {
        roll |= 0xfff00000u;
    }

    dst_p->roll = (int32_t)roll;
    yaw = unpack_right_shift_u32(src_p[5], 0u, 0xffu);
    yaw |= unpack_left_shift_u32(src_p[6], 8u, 0xffu);
    yaw |= unpack_left_shift_u32(src_p[7], 16u, 0x0fu);

    if ((yaw & (1u << 19)) != 0u) {
        yaw |= 0xfff00000u;
    }

    dst_p->yaw = (int32_t)yaw;

    return (0);
}

int ter_ypr_init(struct ter_ypr_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_ypr_t));

    return 0;
}

int32_t ter_ypr_pitch_encode(float value)
{
    return (int32_t)(value / 0.01f);
}

float ter_ypr_pitch_decode(int32_t value)
{
    return ((float)value * 0.01f);
}

bool ter_ypr_pitch_is_in_range(int32_t value)
{
    return ((value >= 0) && (value <= 100));
}

int32_t ter_ypr_roll_encode(float value)
{
    return (int32_t)(value / 0.01f);
}

float ter_ypr_roll_decode(int32_t value)
{
    return ((float)value * 0.01f);
}

bool ter_ypr_roll_is_in_range(int32_t value)
{
    return ((value >= 0) && (value <= 100));
}

int32_t ter_ypr_yaw_encode(float value)
{
    return (int32_t)(value / 0.01f);
}

float ter_ypr_yaw_decode(int32_t value)
{
    return ((float)value * 0.01f);
}

bool ter_ypr_yaw_is_in_range(int32_t value)
{
    return ((value >= 0) && (value <= 100));
}

int ter_lv_voltages_pack(
    uint8_t *dst_p,
    const struct ter_lv_voltages_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->v1, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->v1, 8u, 0x03u);
    dst_p[1] |= pack_left_shift_u16(src_p->v2, 2u, 0xfcu);
    dst_p[2] |= pack_right_shift_u16(src_p->v2, 6u, 0x0fu);
    dst_p[2] |= pack_left_shift_u16(src_p->v3, 4u, 0xf0u);
    dst_p[3] |= pack_right_shift_u16(src_p->v3, 4u, 0x3fu);
    dst_p[3] |= pack_left_shift_u16(src_p->v4, 6u, 0xc0u);
    dst_p[4] |= pack_right_shift_u16(src_p->v4, 2u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->v5, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->v5, 8u, 0x03u);
    dst_p[6] |= pack_left_shift_u16(src_p->v6, 2u, 0xfcu);
    dst_p[7] |= pack_right_shift_u16(src_p->v6, 6u, 0x0fu);

    return (8);
}

int ter_lv_voltages_unpack(
    struct ter_lv_voltages_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->v1 = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->v1 |= unpack_left_shift_u16(src_p[1], 8u, 0x03u);
    dst_p->v2 = unpack_right_shift_u16(src_p[1], 2u, 0xfcu);
    dst_p->v2 |= unpack_left_shift_u16(src_p[2], 6u, 0x0fu);
    dst_p->v3 = unpack_right_shift_u16(src_p[2], 4u, 0xf0u);
    dst_p->v3 |= unpack_left_shift_u16(src_p[3], 4u, 0x3fu);
    dst_p->v4 = unpack_right_shift_u16(src_p[3], 6u, 0xc0u);
    dst_p->v4 |= unpack_left_shift_u16(src_p[4], 2u, 0xffu);
    dst_p->v5 = unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->v5 |= unpack_left_shift_u16(src_p[6], 8u, 0x03u);
    dst_p->v6 = unpack_right_shift_u16(src_p[6], 2u, 0xfcu);
    dst_p->v6 |= unpack_left_shift_u16(src_p[7], 6u, 0x0fu);

    return (0);
}

int ter_lv_voltages_init(struct ter_lv_voltages_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_lv_voltages_t));

    return 0;
}

uint16_t ter_lv_voltages_v1_encode(float value)
{
    return (uint16_t)(value / 0.01f);
}

float ter_lv_voltages_v1_decode(uint16_t value)
{
    return ((float)value * 0.01f);
}

bool ter_lv_voltages_v1_is_in_range(uint16_t value)
{
    return (value <= 100u);
}

uint16_t ter_lv_voltages_v2_encode(float value)
{
    return (uint16_t)(value / 0.01f);
}

float ter_lv_voltages_v2_decode(uint16_t value)
{
    return ((float)value * 0.01f);
}

bool ter_lv_voltages_v2_is_in_range(uint16_t value)
{
    return (value <= 100u);
}

uint16_t ter_lv_voltages_v3_encode(float value)
{
    return (uint16_t)(value / 0.01f);
}

float ter_lv_voltages_v3_decode(uint16_t value)
{
    return ((float)value * 0.01f);
}

bool ter_lv_voltages_v3_is_in_range(uint16_t value)
{
    return (value <= 100u);
}

uint16_t ter_lv_voltages_v4_encode(float value)
{
    return (uint16_t)(value / 0.01f);
}

float ter_lv_voltages_v4_decode(uint16_t value)
{
    return ((float)value * 0.01f);
}

bool ter_lv_voltages_v4_is_in_range(uint16_t value)
{
    return (value <= 100u);
}

uint16_t ter_lv_voltages_v5_encode(float value)
{
    return (uint16_t)(value / 0.01f);
}

float ter_lv_voltages_v5_decode(uint16_t value)
{
    return ((float)value * 0.01f);
}

bool ter_lv_voltages_v5_is_in_range(uint16_t value)
{
    return (value <= 100u);
}

uint16_t ter_lv_voltages_v6_encode(float value)
{
    return (uint16_t)(value / 0.01f);
}

float ter_lv_voltages_v6_decode(uint16_t value)
{
    return ((float)value * 0.01f);
}

bool ter_lv_voltages_v6_is_in_range(uint16_t value)
{
    return (value <= 100u);
}

int ter_lv_temps_pack(
    uint8_t *dst_p,
    const struct ter_lv_temps_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u8(src_p->t1, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->t2, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->t3, 0u, 0xffu);

    return (3);
}

int ter_lv_temps_unpack(
    struct ter_lv_temps_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    dst_p->t1 = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->t2 = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->t3 = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

int ter_lv_temps_init(struct ter_lv_temps_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_lv_temps_t));

    return 0;
}

uint8_t ter_lv_temps_t1_encode(float value)
{
    return (uint8_t)(value);
}

float ter_lv_temps_t1_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_lv_temps_t1_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_lv_temps_t2_encode(float value)
{
    return (uint8_t)(value);
}

float ter_lv_temps_t2_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_lv_temps_t2_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_lv_temps_t3_encode(float value)
{
    return (uint8_t)(value);
}

float ter_lv_temps_t3_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_lv_temps_t3_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int ter_lv_status_pack(
    uint8_t *dst_p,
    const struct ter_lv_status_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u8(src_p->refri_on, 6u, 0x40u);
    dst_p[0] |= pack_left_shift_u8(src_p->lv_on, 7u, 0x80u);
    dst_p[1] |= pack_left_shift_u16(src_p->lv_current, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->lv_current, 8u, 0xffu);

    return (3);
}

int ter_lv_status_unpack(
    struct ter_lv_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    dst_p->refri_on = unpack_right_shift_u8(src_p[0], 6u, 0x40u);
    dst_p->lv_on = unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    dst_p->lv_current = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->lv_current |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);

    return (0);
}

int ter_lv_status_init(struct ter_lv_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_lv_status_t));

    return 0;
}

uint8_t ter_lv_status_refri_on_encode(float value)
{
    return (uint8_t)(value);
}

float ter_lv_status_refri_on_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_lv_status_refri_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ter_lv_status_lv_on_encode(float value)
{
    return (uint8_t)(value);
}

float ter_lv_status_lv_on_decode(uint8_t value)
{
    return ((float)value);
}

bool ter_lv_status_lv_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t ter_lv_status_lv_current_encode(float value)
{
    return (uint16_t)(value / 0.1f);
}

float ter_lv_status_lv_current_decode(uint16_t value)
{
    return ((float)value * 0.1f);
}

bool ter_lv_status_lv_current_is_in_range(uint16_t value)
{
    return (value <= 10u);
}

int ter_ang_rate_pack(
    uint8_t *dst_p,
    const struct ter_ang_rate_t *src_p,
    size_t size)
{
    uint32_t pitch_rate_y;
    uint32_t roll_rate_x;
    uint32_t yaw_rate_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    roll_rate_x = (uint32_t)src_p->roll_rate_x;
    dst_p[0] |= pack_left_shift_u32(roll_rate_x, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(roll_rate_x, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(roll_rate_x, 16u, 0x0fu);
    pitch_rate_y = (uint32_t)src_p->pitch_rate_y;
    dst_p[2] |= pack_left_shift_u32(pitch_rate_y, 4u, 0xf0u);
    dst_p[3] |= pack_right_shift_u32(pitch_rate_y, 4u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(pitch_rate_y, 12u, 0xffu);
    yaw_rate_z = (uint32_t)src_p->yaw_rate_z;
    dst_p[5] |= pack_left_shift_u32(yaw_rate_z, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(yaw_rate_z, 8u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(yaw_rate_z, 16u, 0x0fu);

    return (8);
}

int ter_ang_rate_unpack(
    struct ter_ang_rate_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t pitch_rate_y;
    uint32_t roll_rate_x;
    uint32_t yaw_rate_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    roll_rate_x = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    roll_rate_x |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    roll_rate_x |= unpack_left_shift_u32(src_p[2], 16u, 0x0fu);

    if ((roll_rate_x & (1u << 19)) != 0u) {
        roll_rate_x |= 0xfff00000u;
    }

    dst_p->roll_rate_x = (int32_t)roll_rate_x;
    pitch_rate_y = unpack_right_shift_u32(src_p[2], 4u, 0xf0u);
    pitch_rate_y |= unpack_left_shift_u32(src_p[3], 4u, 0xffu);
    pitch_rate_y |= unpack_left_shift_u32(src_p[4], 12u, 0xffu);

    if ((pitch_rate_y & (1u << 19)) != 0u) {
        pitch_rate_y |= 0xfff00000u;
    }

    dst_p->pitch_rate_y = (int32_t)pitch_rate_y;
    yaw_rate_z = unpack_right_shift_u32(src_p[5], 0u, 0xffu);
    yaw_rate_z |= unpack_left_shift_u32(src_p[6], 8u, 0xffu);
    yaw_rate_z |= unpack_left_shift_u32(src_p[7], 16u, 0x0fu);

    if ((yaw_rate_z & (1u << 19)) != 0u) {
        yaw_rate_z |= 0xfff00000u;
    }

    dst_p->yaw_rate_z = (int32_t)yaw_rate_z;

    return (0);
}

int ter_ang_rate_init(struct ter_ang_rate_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_ang_rate_t));

    return 0;
}

int32_t ter_ang_rate_roll_rate_x_encode(float value)
{
    return (int32_t)(value / 0.001f);
}

float ter_ang_rate_roll_rate_x_decode(int32_t value)
{
    return ((float)value * 0.001f);
}

bool ter_ang_rate_roll_rate_x_is_in_range(int32_t value)
{
    return ((value >= 0) && (value <= 1000));
}

int32_t ter_ang_rate_pitch_rate_y_encode(float value)
{
    return (int32_t)(value / 0.001f);
}

float ter_ang_rate_pitch_rate_y_decode(int32_t value)
{
    return ((float)value * 0.001f);
}

bool ter_ang_rate_pitch_rate_y_is_in_range(int32_t value)
{
    return ((value >= 0) && (value <= 1000));
}

int32_t ter_ang_rate_yaw_rate_z_encode(float value)
{
    return (int32_t)(value / 0.001f);
}

float ter_ang_rate_yaw_rate_z_decode(int32_t value)
{
    return ((float)value * 0.001f);
}

bool ter_ang_rate_yaw_rate_z_is_in_range(int32_t value)
{
    return ((value >= 0) && (value <= 1000));
}

int ter_gps_lat_long_pack(
    uint8_t *dst_p,
    const struct ter_gps_lat_long_t *src_p,
    size_t size)
{
    uint32_t latitude;
    uint32_t longitude;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    latitude = (uint32_t)src_p->latitude;
    dst_p[0] |= pack_left_shift_u32(latitude, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(latitude, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(latitude, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(latitude, 24u, 0xffu);
    longitude = (uint32_t)src_p->longitude;
    dst_p[4] |= pack_left_shift_u32(longitude, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(longitude, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(longitude, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(longitude, 24u, 0xffu);

    return (8);
}

int ter_gps_lat_long_unpack(
    struct ter_gps_lat_long_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t latitude;
    uint32_t longitude;

    if (size < 8u) {
        return (-EINVAL);
    }

    latitude = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    latitude |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    latitude |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    latitude |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->latitude = (int32_t)latitude;
    longitude = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    longitude |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    longitude |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    longitude |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);
    dst_p->longitude = (int32_t)longitude;

    return (0);
}

int ter_gps_lat_long_init(struct ter_gps_lat_long_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_gps_lat_long_t));

    return 0;
}

int32_t ter_gps_lat_long_latitude_encode(float value)
{
    return (int32_t)(value / 1e-07f);
}

float ter_gps_lat_long_latitude_decode(int32_t value)
{
    return ((float)value * 1e-07f);
}

bool ter_gps_lat_long_latitude_is_in_range(int32_t value)
{
    return ((value >= 0) && (value <= 10000000));
}

int32_t ter_gps_lat_long_longitude_encode(float value)
{
    return (int32_t)(value / 1e-07f);
}

float ter_gps_lat_long_longitude_decode(int32_t value)
{
    return ((float)value * 1e-07f);
}

bool ter_gps_lat_long_longitude_is_in_range(int32_t value)
{
    return ((value >= 0) && (value <= 10000000));
}

int ter_gps_altitude_pres_pack(
    uint8_t *dst_p,
    const struct ter_gps_altitude_pres_t *src_p,
    size_t size)
{
    uint16_t barometric_pressure;
    uint32_t altidude;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    altidude = (uint32_t)src_p->altidude;
    dst_p[0] |= pack_left_shift_u32(altidude, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(altidude, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(altidude, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(altidude, 24u, 0xffu);
    barometric_pressure = (uint16_t)src_p->barometric_pressure;
    dst_p[4] |= pack_left_shift_u16(barometric_pressure, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(barometric_pressure, 8u, 0xffu);

    return (8);
}

int ter_gps_altitude_pres_unpack(
    struct ter_gps_altitude_pres_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t barometric_pressure;
    uint32_t altidude;

    if (size < 8u) {
        return (-EINVAL);
    }

    altidude = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    altidude |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    altidude |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    altidude |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->altidude = (int32_t)altidude;
    barometric_pressure = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    barometric_pressure |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->barometric_pressure = (int16_t)barometric_pressure;

    return (0);
}

int ter_gps_altitude_pres_init(struct ter_gps_altitude_pres_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_gps_altitude_pres_t));

    return 0;
}

int32_t ter_gps_altitude_pres_altidude_encode(float value)
{
    return (int32_t)(value / 1e-07f);
}

float ter_gps_altitude_pres_altidude_decode(int32_t value)
{
    return ((float)value * 1e-07f);
}

bool ter_gps_altitude_pres_altidude_is_in_range(int32_t value)
{
    return ((value >= 0) && (value <= 10000000));
}

int16_t ter_gps_altitude_pres_barometric_pressure_encode(float value)
{
    return (int16_t)(value / 1e-07f);
}

float ter_gps_altitude_pres_barometric_pressure_decode(int16_t value)
{
    return ((float)value * 1e-07f);
}

bool ter_gps_altitude_pres_barometric_pressure_is_in_range(int16_t value)
{
    return (value >= 0);
}

int ter_accel_pack(
    uint8_t *dst_p,
    const struct ter_accel_t *src_p,
    size_t size)
{
    uint16_t a_x;
    uint16_t a_y;
    uint16_t a_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    a_x = (uint16_t)src_p->a_x;
    dst_p[0] |= pack_left_shift_u16(a_x, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(a_x, 8u, 0xffu);
    a_y = (uint16_t)src_p->a_y;
    dst_p[2] |= pack_left_shift_u16(a_y, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(a_y, 8u, 0xffu);
    a_z = (uint16_t)src_p->a_z;
    dst_p[4] |= pack_left_shift_u16(a_z, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(a_z, 8u, 0xffu);

    return (8);
}

int ter_accel_unpack(
    struct ter_accel_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t a_x;
    uint16_t a_y;
    uint16_t a_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    a_x = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    a_x |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->a_x = (int16_t)a_x;
    a_y = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    a_y |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->a_y = (int16_t)a_y;
    a_z = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    a_z |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->a_z = (int16_t)a_z;

    return (0);
}

int ter_accel_init(struct ter_accel_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_accel_t));

    return 0;
}

int16_t ter_accel_a_x_encode(float value)
{
    return (int16_t)(value / 0.001f);
}

float ter_accel_a_x_decode(int16_t value)
{
    return ((float)value * 0.001f);
}

bool ter_accel_a_x_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 1000));
}

int16_t ter_accel_a_y_encode(float value)
{
    return (int16_t)(value / 0.001f);
}

float ter_accel_a_y_decode(int16_t value)
{
    return ((float)value * 0.001f);
}

bool ter_accel_a_y_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 1000));
}

int16_t ter_accel_a_z_encode(float value)
{
    return (int16_t)(value / 0.001f);
}

float ter_accel_a_z_decode(int16_t value)
{
    return ((float)value * 0.001f);
}

bool ter_accel_a_z_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 1000));
}

int ter_mag_pack(
    uint8_t *dst_p,
    const struct ter_mag_t *src_p,
    size_t size)
{
    uint16_t heading;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    heading = (uint16_t)src_p->heading;
    dst_p[0] |= pack_left_shift_u16(heading, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(heading, 8u, 0xffu);

    return (8);
}

int ter_mag_unpack(
    struct ter_mag_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t heading;

    if (size < 8u) {
        return (-EINVAL);
    }

    heading = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    heading |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->heading = (int16_t)heading;

    return (0);
}

int ter_mag_init(struct ter_mag_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_mag_t));

    return 0;
}

int16_t ter_mag_heading_encode(float value)
{
    return (int16_t)(value / 0.01f);
}

float ter_mag_heading_decode(int16_t value)
{
    return ((float)value * 0.01f);
}

bool ter_mag_heading_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 100));
}

int ter_vel_body_pack(
    uint8_t *dst_p,
    const struct ter_vel_body_t *src_p,
    size_t size)
{
    uint16_t v_x;
    uint16_t v_y;
    uint16_t v_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    v_x = (uint16_t)src_p->v_x;
    dst_p[0] |= pack_left_shift_u16(v_x, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(v_x, 8u, 0xffu);
    v_y = (uint16_t)src_p->v_y;
    dst_p[2] |= pack_left_shift_u16(v_y, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(v_y, 8u, 0xffu);
    v_z = (uint16_t)src_p->v_z;
    dst_p[4] |= pack_left_shift_u16(v_z, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(v_z, 8u, 0xffu);

    return (8);
}

int ter_vel_body_unpack(
    struct ter_vel_body_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t v_x;
    uint16_t v_y;
    uint16_t v_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    v_x = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    v_x |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->v_x = (int16_t)v_x;
    v_y = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    v_y |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->v_y = (int16_t)v_y;
    v_z = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    v_z |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->v_z = (int16_t)v_z;

    return (0);
}

int ter_vel_body_init(struct ter_vel_body_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_vel_body_t));

    return 0;
}

int16_t ter_vel_body_v_x_encode(float value)
{
    return (int16_t)(value / 0.001f);
}

float ter_vel_body_v_x_decode(int16_t value)
{
    return ((float)value * 0.001f);
}

bool ter_vel_body_v_x_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 1000));
}

int16_t ter_vel_body_v_y_encode(float value)
{
    return (int16_t)(value / 0.001f);
}

float ter_vel_body_v_y_decode(int16_t value)
{
    return ((float)value * 0.001f);
}

bool ter_vel_body_v_y_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 1000));
}

int16_t ter_vel_body_v_z_encode(float value)
{
    return (int16_t)(value / 0.001f);
}

float ter_vel_body_v_z_decode(int16_t value)
{
    return ((float)value * 0.001f);
}

bool ter_vel_body_v_z_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 1000));
}

int ter_imu_status_pack(
    uint8_t *dst_p,
    const struct ter_imu_status_t *src_p,
    size_t size)
{
    uint16_t pos_u;
    uint16_t status;
    uint16_t vel_u;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    status = (uint16_t)src_p->status;
    dst_p[0] |= pack_left_shift_u16(status, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(status, 8u, 0xffu);
    pos_u = (uint16_t)src_p->pos_u;
    dst_p[2] |= pack_left_shift_u16(pos_u, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(pos_u, 8u, 0xffu);
    vel_u = (uint16_t)src_p->vel_u;
    dst_p[4] |= pack_left_shift_u16(vel_u, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(vel_u, 8u, 0xffu);

    return (8);
}

int ter_imu_status_unpack(
    struct ter_imu_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t pos_u;
    uint16_t status;
    uint16_t vel_u;

    if (size < 8u) {
        return (-EINVAL);
    }

    status = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    status |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->status = (int16_t)status;
    pos_u = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    pos_u |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->pos_u = (int16_t)pos_u;
    vel_u = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    vel_u |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->vel_u = (int16_t)vel_u;

    return (0);
}

int ter_imu_status_init(struct ter_imu_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ter_imu_status_t));

    return 0;
}

int16_t ter_imu_status_status_encode(float value)
{
    return (int16_t)(value);
}

float ter_imu_status_status_decode(int16_t value)
{
    return ((float)value);
}

bool ter_imu_status_status_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 1));
}

int16_t ter_imu_status_pos_u_encode(float value)
{
    return (int16_t)(value / 0.001f);
}

float ter_imu_status_pos_u_decode(int16_t value)
{
    return ((float)value * 0.001f);
}

bool ter_imu_status_pos_u_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 1000));
}

int16_t ter_imu_status_vel_u_encode(float value)
{
    return (int16_t)(value / 0.001f);
}

float ter_imu_status_vel_u_decode(int16_t value)
{
    return ((float)value * 0.001f);
}

bool ter_imu_status_vel_u_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 1000));
}
